In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
from ast import literal_eval
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from scipy.optimize import minimize
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
import os

In [30]:
# Define helper functions
def load_csv(filename):
    return pd.read_csv(filename, sep=',')

def calculate_group_average(df):
    return df.groupby(['Label', 'Conc']).mean()

def transform_label(label):
    # Check for condition 1: Replace specific strings with 'Reference'
    if label in (["['AF']", "['AgNR@SiO2']", "['DMEM']"]):
        return "['Reference']"
    
    # Check for condition 2: Replace 'COVNL63' or 'CoVNL63' with 'CoVNL63'
    if 'COVNL63' in label or 'CoVNL63' in label:
        label = label.replace('COVNL63', 'CoVNL63')
        label = label.replace('CoVNL63', 'CoVNL63')
        label = label.replace('CovNL63', 'CoVNL63')
    
    return label

def inspect_dataframe(df):
    """
    Inspects a DataFrame to understand its structure, particularly the Label and Conc columns.
    """
    print("DataFrame shape:", df.shape)
    print("\nColumn names:", df.columns.tolist())
    
    # Inspect index structure
    print("\nIndex type:", type(df.index))
    print("First 5 index values:", df.index[:5])
    
    if 'Label' in df.columns or ('Label' in df.index.names):
        # Get unique labels
        if 'Label' in df.columns:
            labels = df['Label'].unique()
        else:
            # For MultiIndex
            labels = df.index.get_level_values('Label').unique()
        
        print("\nUnique Label values (first 10):")
        for i, label in enumerate(labels[:10]):
            print(f"{i+1}. {repr(label)} (Type: {type(label)})")
    
    if 'Conc' in df.columns or ('Conc' in df.index.names):
        # Get unique concentrations
        if 'Conc' in df.columns:
            concs = df['Conc'].unique()
        else:
            # For MultiIndex
            concs = df.index.get_level_values('Conc').unique()
        
        print("\nUnique Conc values (first 10):")
        for i, conc in enumerate(concs[:10]):
            print(f"{i+1}. {repr(conc)} (Type: {type(conc)})")
    
    # Check for problematic mixed virus entries
    if isinstance(df.index, pd.MultiIndex) and 'Label' in df.index.names:
        print("\nChecking for mixed virus entries:")
        for idx in df.index:
            label = idx[df.index.names.index('Label')]
            if "__" in str(label):
                print(f"Found mixed virus: {repr(label)}")
                # Print the full row for this index
                print(f"  Row data: {idx}")
                break

def parse_mixed_virus_data(fixed_df):
    """
    Parse virus names and concentrations from mixed virus data.
    Uses ast.literal_eval to safely parse the Label strings as Python literals,
    ensuring accurate virus type detection.
    """
    import ast  # For safely evaluating the label as a Python literal
    
    # Create dictionary to store parsed results
    parsed_data = {}
    
    # Reset index to access the Label and Conc columns
    fixed_df_reset = fixed_df.reset_index()
    
    # Process each row
    for idx, row in fixed_df_reset.iterrows():
        label = row['Label']
        conc = row['Conc']
        
        # Parse the virus names from the label using literal_eval
        virus_names = []
        if isinstance(label, str):
            try:
                # Parse the label as a Python literal (usually a list of strings)
                parsed_label = ast.literal_eval(label)
                
                if isinstance(parsed_label, list):
                    # Successfully parsed as a list
                    virus_names = parsed_label
                else:
                    # Not a list, just use the single item
                    virus_names = [str(parsed_label)]
            except (SyntaxError, ValueError):
                # If parsing fails, fall back to simple string handling
                clean_label = label.strip("[]' ")
                virus_names = [clean_label]
        
        # Parse the concentrations from the conc - for clean CSV format with brackets
        concentrations = []
        if isinstance(conc, str):
            try:
                # Try to parse the concentration as a Python literal first
                parsed_conc = ast.literal_eval(conc)
                
                if isinstance(parsed_conc, list):
                    # It's a list of concentrations
                    concentrations = [float(c) for c in parsed_conc]
                else:
                    # Single concentration
                    concentrations = [float(parsed_conc)]
            except (SyntaxError, ValueError):
                # If parsing fails, fall back to string splitting
                # First, remove any surrounding brackets if present
                clean_conc = conc.strip()
                if clean_conc.startswith('[') and clean_conc.endswith(']'):
                    clean_conc = clean_conc[1:-1]  # Remove the brackets
                
                # Handle the format with comma separators
                if "," in clean_conc:
                    # Split by comma and convert each part to float
                    parts = clean_conc.split(",")
                    for part in parts:
                        part = part.strip()
                        if part:  # Skip empty strings
                            try:
                                concentrations.append(float(part))
                            except ValueError:
                                print(f"Warning: Could not convert '{part}' to float")
                else:
                    # No separators, just a single value
                    if clean_conc:
                        try:
                            concentrations.append(float(clean_conc))
                        except ValueError:
                            print(f"Warning: Could not convert '{clean_conc}' to float")
        elif isinstance(conc, (int, float)):
            concentrations.append(conc)
        
        # Determine the type of mixture
        if len(virus_names) == 1:
            parsed_type = "single"
        elif len(virus_names) == 2:
            parsed_type = "double"
        elif len(virus_names) == 3:
            parsed_type = "triple"
        else:
            parsed_type = f"multiple({len(virus_names)})"
        
        # Store the parsed data using the original index as key
        original_idx = (label, conc)
        parsed_data[original_idx] = {
            "type": parsed_type,
            "virus_names": virus_names,
            "concentrations": concentrations
        }
    
    return parsed_data

def get_single_virus_highest_concentration_rows(avg_df):
    """
    Get the highest concentration row for each single virus (excluding mixed virus samples).
    Updated to handle the clean CSV format with bracketed values.
    
    Args:
        avg_df: DataFrame with virus data, may include mixed virus samples
        
    Returns:
        DataFrame with highest concentration row for each single virus
    """
    avg_df_reset = avg_df.reset_index()
    
    print("Extracting single virus data...")
    
    # Filter for single virus labels only
    single_virus_mask = avg_df_reset['Label'].apply(
        lambda x: isinstance(x, str) and 
                 not '__' in x and  # Skip mixed virus labels with '__'
                 len(x.strip("[]").replace("'", "").split(", ")) == 1
    )
    
    single_virus_df = avg_df_reset[single_virus_mask].copy()
    print(f"Found {len(single_virus_df)} single virus samples")
    
    if single_virus_df.empty:
        print("No single virus samples found!")
        return pd.DataFrame()
    
    # Print some example concentration values for debugging
    print("Example concentration values:")
    print(single_virus_df['Conc'].head(5).to_list())
    
    # Parse concentration values for single virus samples - Updated for clean CSV format with brackets
    def parse_conc(x):
        try:
            if isinstance(x, str):
                # First, remove any surrounding brackets if present
                clean_str = x.strip()
                if clean_str.startswith('[') and clean_str.endswith(']'):
                    clean_str = clean_str[1:-1]  # Remove the first and last characters (brackets)
                
                # Handle new format with comma separators
                if "," in clean_str:
                    # For single virus, just take the first value before comma
                    first_value = clean_str.split(",")[0].strip()
                    return float(first_value)
                else:
                    # Just try to convert to float directly
                    return float(clean_str)
            elif isinstance(x, list):
                # If it's already a list, return the first element
                return float(x[0])
            else:
                # If it's a scalar value, return it as is
                return float(x)
        except Exception as e:
            print(f"Error parsing concentration: {x}, Error: {e}")
            # Return the original value if parsing fails
            return x
    
    # Apply the parsing function
    single_virus_df['Conc_parsed'] = single_virus_df['Conc'].apply(parse_conc)
    
    # For debugging
    print("After parsing concentrations:")
    print(single_virus_df[['Label', 'Conc', 'Conc_parsed']].head())
    
    # Get unique single virus labels
    unique_virus_labels = single_virus_df['Label'].unique()
    print(f"Found {len(unique_virus_labels)} unique single virus types")
    
    # Get highest concentration for each virus
    highest_conc_rows = []
    for label in unique_virus_labels:
        label_rows = single_virus_df[single_virus_df['Label'] == label]
        if not label_rows.empty:
            try:
                # Sort by parsed concentration and get highest
                highest_conc_row = label_rows.sort_values(by='Conc_parsed', ascending=False).iloc[0]
                # Remove the temporary Conc_parsed column before adding to results
                highest_conc_row = highest_conc_row.drop('Conc_parsed')
                highest_conc_rows.append(highest_conc_row)
                print(f"Highest concentration for {label}: {highest_conc_row['Conc']}")
            except Exception as e:
                print(f"Error processing {label}: {str(e)}")
    
    result_df = pd.DataFrame(highest_conc_rows)
    print(f"Final result has {len(result_df)} rows")
    return result_df
    
def fit_least_squares(components, target, lam=1.0, regularization="None"):
    X = np.column_stack(components)
    y = target.values.reshape(-1, 1).ravel()
    num_vars = X.shape[1]
    
    # Objective function: Sum of squared residuals with regularization
    def objective(coefs):
        predictions = X @ coefs
        residuals = y - predictions
        reg_term = 0
        if regularization == "ridge":
            reg_term = lam * np.sum(coefs**2)
        elif regularization == "lasso":
            reg_term = lam * np.sum(np.abs(coefs))
        elif regularization == "None":
            reg_term = 0
        return np.sum(residuals**2) + reg_term
    
    # Constraints: Coefficients sum to 1
    cons = {'type': 'eq', 'fun': lambda coefs: np.sum(coefs) - 1}
    
    # Bounds: Coefficients are non-negative
    bounds = [(1e-10, 1) for _ in range(num_vars)]
    
    # Initial guess: all ones
    initial_coefs = np.ones(num_vars)
    
    # Perform optimization
    result = minimize(objective, initial_coefs, bounds=bounds, constraints=cons)
    
    if not result.success:
        raise ValueError("Constrained optimization failed!")
    
    coefficients = result.x
    
    return coefficients, 0

def process_dataframe(fixed_df, parsed_data, highest_single_virus_conc_df, reference_series):
    """
    Process the dataframe and return predicted spectra and fit results.
    """
    # Initialize DataFrame to store results
    predicted_df = pd.DataFrame()
    result_df = pd.DataFrame(columns=['Label', 'Conc', 'Coefficients', 'Intercept', 'MAE', 'RMSE', 'R2'])
    
    # Process each sample
    for (label, conc), target_avg in fixed_df.iterrows():
        if 'Reference' not in str(label):  # Skip reference samples
            print(f"\nProcessing sample: Label={label}, Conc={conc}")
            
            try:
                # Get the parsed virus names and concentrations
                parsed_idx = (label, conc)
                if parsed_idx in parsed_data:
                    virus_data = parsed_data[parsed_idx]
                    virus_names = virus_data["virus_names"]
                    concentrations = virus_data["concentrations"]
                else:
                    print(f"Warning: No parsed data found for {parsed_idx}")
                    continue
                    
                print(f"Parsed viruses: {virus_names}")
                print(f"Parsed concentrations: {concentrations}")
                
                # Get the average values for each of the single-virus components
                components = []
                for virus_name in virus_names:
                    # Format the virus name for lookup
                    formatted_virus = f"['{virus_name}']"
                    matching_rows = highest_single_virus_conc_df[highest_single_virus_conc_df['Label'] == formatted_virus]
                    
                    if matching_rows.empty:
                        print(f"Warning: No data found for virus '{virus_name}'")
                        continue
                    
                    # Get the highest concentration data for this virus
                    virus_component = matching_rows.iloc[0, 2:].astype(float)
                    components.append(virus_component)
                
                # Add reference component
                components.append(reference_series)
                
                if len(components) < 2:
                    print(f"Warning: Not enough components found for label {label}")
                    continue
                
                # Perform least squares fitting
                coefficients, intercept = fit_least_squares(components, target_avg)
                print(f"Fitted coefficients: {coefficients}")
                
                # Compute predicted values
                predicted_avg = sum(comp * coef for comp, coef in zip(components, coefficients)) + intercept
                
                # Compute MAE, RMSE, and R2
                mae = mean_absolute_error(target_avg, predicted_avg)
                rmse = np.sqrt(mean_squared_error(target_avg, predicted_avg))
                r2 = r2_score(target_avg, predicted_avg)
                
                # Compute VIFs for predictors
                X_with_const = add_constant(np.column_stack(components))
                
                # Handle NaN or infinite values
                for i, comp in enumerate(components):
                    if not np.isfinite(comp).all():
                        print(f"Warning: Component {i} contains NaNs or infinities")
                        components[i] = comp.fillna(0).replace([np.inf, -np.inf], 0)
                
                # Calculate VIF for each predictor
                vifs = [variance_inflation_factor(X_with_const, i) for i in range(X_with_const.shape[1])]
                vifs = vifs[1:]  # Exclude constant term
                
                # Append results to DataFrame
                data_dict = predicted_avg.to_dict()
                data_dict['Label'] = label
                data_dict['Conc'] = conc
                
                # Add to predicted_df
                predicted_df = pd.concat([predicted_df, pd.DataFrame([data_dict])], ignore_index=True)
                
                # Add to result_df
                result_row = {
                    'Label': label, 
                    'Conc': conc, 
                    'Coefficients': coefficients, 
                    'Intercept': intercept, 
                    'MAE': mae, 
                    'RMSE': rmse, 
                    'R2': r2, 
                    'VIFs': vifs
                }
                result_df = pd.concat([result_df, pd.DataFrame([result_row])], ignore_index=True)
                
            except Exception as e:
                print(f"Error processing label={label}, conc={conc}: {str(e)}")
                import traceback
                traceback.print_exc()
                # Continue to the next sample
                continue
    
    return predicted_df, result_df

In [22]:
# Set up the paths and folders
WORKING_PATH = "/home/zhao/Jiaheng Cui/Coefficient_fitting"
DATA_FOLDER = WORKING_PATH + "/data/linear decomposition"
DATE = "04042025"
RESULT_FOLDER = WORKING_PATH + f"/{DATE} - reconstructed vs real only using GLF"
os.makedirs(RESULT_FOLDER, exist_ok=True)

In [ ]:
# Step 1: Load CSV data
filename = DATA_FOLDER + "/test (virus in water).csv"
df = pd.read_csv(filename, sep=',')

# Apply label transformation
df['Label'] = df['Label'].apply(transform_label)
df

,450.0,451.0,452.0,453.0,454.0,455.0,456.0,457.0,458.0,459.0,...,1693.0,1694.0,1695.0,1696.0,1697.0,1698.0,1699.0,1700.0,Label,Conc
0,0.170,0.171,0.175,0.181,0.192,0.203,0.214,0.223,0.232,0.240,...,0.682,0.664,0.649,0.636,0.624,0.614,0.602,0.589,['Ad5'],[100.0]
1,0.143,0.147,0.152,0.157,0.163,0.170,0.178,0.186,0.193,0.203,...,0.679,0.664,0.653,0.642,0.631,0.620,0.607,0.593,['Ad5'],[100.0]
2,0.168,0.168,0.172,0.179,0.194,0.205,0.216,0.224,0.228,0.230,...,0.663,0.646,0.630,0.615,0.601,0.589,0.576,0.563,['Ad5'],[100.0]
3,0.191,0.191,0.193,0.197,0.205,0.214,0.225,0.236,0.248,0.263,...,0.699,0.682,0.661,0.644,0.630,0.623,0.611,0.596,['Ad5'],[100.0]
4,0.192,0.199,0.205,0.209,0.209,0.211,0.213,0.216,0.221,0.229,...,0.674,0.657,0.642,0.626,0.610,0.594,0.579,0.565,['Ad5'],[100.0]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88699,0.124,0.148,0.160,0.169,0.174,0.175,0.165,0.167,0.173,0.181,...,0.638,0.623,0.621,0.611,0.596,0.569,0.547,0.531,['RSVB1'],[781.0]
88700,0.052,0.066,0.072,0.075,0.075,0.071,0.061,0.061,0.064,0.072,...,0.688,0.678,0.676,0.667,0.655,0.631,0.614,0.604,['RSVB1'],[781.0]
88701,0.140,0.158,0.170,0.179,0.185,0.188,0.185,0.187,0.191,0.196,...,0.699,0.688,0.682,0.674,0.666,0.656,0.647,0.637,['RSVB1'],[781.0]
88702,0.153,0.161,0.163,0.160,0.152,0.141,0.121,0.118,0.123,0.133,...,0.631,0.623,0.621,0.616,0.608,0.595,0.582,0.570,['RSVB1'],[781.0]
88703,0.161,0.155,0.155,0.159,0.167,0.178,0.196,0.205,0.212,0.215,...,0.716,0.705,0.684,0.668,0.653,0.645,0.634,0.620,['RSVB1'],[781.0]

In [24]:
# Group and save the grouped data
grouped_df = df.groupby(['Label', 'Conc'], as_index=False).mean()
grouped_df

,Label,Conc,450.0,451.0,452.0,453.0,454.0,455.0,456.0,457.0,...,1691.0,1692.0,1693.0,1694.0,1695.0,1696.0,1697.0,1698.0,1699.0,1700.0
0,['Ad5'],[100.0],0.188456,0.193579,0.199298,0.205842,0.214035,0.222088,0.230509,0.238614,...,0.724246,0.706123,0.688772,0.672316,0.656649,0.642035,0.628474,0.616544,0.603561,0.589719
1,['Ad5'],[100000.0],0.108017,0.115627,0.123576,0.132051,0.140915,0.149695,0.160068,0.166644,...,1.058237,1.045763,1.033407,1.020407,1.007390,0.992627,0.976119,0.957441,0.937000,0.914610
2,['Ad5'],[12500.0],0.125390,0.136017,0.145695,0.155153,0.164305,0.172593,0.181102,0.186508,...,1.031186,1.019051,1.007000,0.994695,0.982814,0.969153,0.953915,0.936441,0.918119,0.898695
3,['Ad5'],[1562.0],0.144458,0.155678,0.165746,0.175237,0.184034,0.191864,0.199475,0.204407,...,1.011746,1.001780,0.990966,0.979593,0.967610,0.954356,0.939966,0.923898,0.907797,0.891576
4,['Ad5'],[195.0],0.142603,0.152603,0.161483,0.169983,0.177655,0.184931,0.192069,0.197793,...,0.880224,0.866776,0.852776,0.838741,0.824276,0.809707,0.795000,0.779914,0.764931,0.750431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,['RSVB1'],[50.0],0.136810,0.138224,0.141741,0.146172,0.151672,0.158603,0.166310,0.174000,...,0.744603,0.726397,0.707000,0.688672,0.671207,0.653741,0.637914,0.623000,0.611241,0.598483
2576,['RSVB1'],[50000.0],0.154390,0.162458,0.167458,0.171000,0.172881,0.173220,0.170322,0.170288,...,0.860475,0.851661,0.843661,0.836492,0.831085,0.823475,0.813983,0.801017,0.789203,0.778390
2577,['RSVB1'],[6250.0],0.177224,0.182293,0.185483,0.187879,0.189190,0.189483,0.187948,0.187966,...,0.815948,0.802086,0.791810,0.783845,0.781293,0.775534,0.767638,0.754776,0.744207,0.735483
2578,['RSVB1'],[781.0],0.126759,0.135397,0.141224,0.145879,0.149379,0.151500,0.151138,0.153155,...,0.735293,0.720603,0.709017,0.699397,0.694690,0.686190,0.675052,0.658069,0.643534,0.630948
2579,['Reference'],[0.0],0.159350,0.167391,0.175635,0.184376,0.193345,0.202345,0.213487,0.219716,...,0.884071,0.872670,0.861655,0.850949,0.841188,0.829807,0.817056,0.801919,0.786701,0.771223

In [25]:
pd.DataFrame(grouped_df).to_csv(DATA_FOLDER + f"/New folder/{DATE} - average_spectra_grouped_test_only_GLF_with_SiO2.csv", index=False)

In [26]:
# Calculate group average
avg_df = calculate_group_average(df)
print("Average DataFrame shape:", avg_df.shape)

# Inspect the DataFrame to understand its structure
inspect_dataframe(avg_df)
avg_df

Average DataFrame shape: (2580, 1251)
DataFrame shape: (2580, 1251)

Column names: ['450.0', '451.0', '452.0', '453.0', '454.0', '455.0', '456.0', '457.0', '458.0', '459.0', '460.0', '461.0', '462.0', '463.0', '464.0', '465.0', '466.0', '467.0', '468.0', '469.0', '470.0', '471.0', '472.0', '473.0', '474.0', '475.0', '476.0', '477.0', '478.0', '479.0', '480.0', '481.0', '482.0', '483.0', '484.0', '485.0', '486.0', '487.0', '488.0', '489.0', '490.0', '491.0', '492.0', '493.0', '494.0', '495.0', '496.0', '497.0', '498.0', '499.0', '500.0', '501.0', '502.0', '503.0', '504.0', '505.0', '506.0', '507.0', '508.0', '509.0', '510.0', '511.0', '512.0', '513.0', '514.0', '515.0', '516.0', '517.0', '518.0', '519.0', '520.0', '521.0', '522.0', '523.0', '524.0', '525.0', '526.0', '527.0', '528.0', '529.0', '530.0', '531.0', '532.0', '533.0', '534.0', '535.0', '536.0', '537.0', '538.0', '539.0', '540.0', '541.0', '542.0', '543.0', '544.0', '545.0', '546.0', '547.0', '548.0', '549.0', '550.0', '551.0', '552.0', '553.0', '554.0', '555.0', '556.0', '557.0', '558.0', '559.0', '560.0', '561.0', '562.0', '563.0', '564.0', '565.0', '566.0', '567.0', '568.0', '569.0', '570.0', '571.0', '572.0', '573.0', '574.0', '575.0', '576.0', '577.0', '578.0', '579.0', '580.0', '581.0', '582.0', '583.0', '584.0', '585.0', '586.0', '587.0', '588.0', '589.0', '590.0', '591.0', '592.0', '593.0', '594.0', '595.0', '596.0', '597.0', '598.0', '599.0', '600.0', '601.0', '602.0', '603.0', '604.0', '605.0', '606.0', '607.0', '608.0', '609.0', '610.0', '611.0', '612.0', '613.0', '614.0', '615.0', '616.0', '617.0', '618.0', '619.0', '620.0', '621.0', '622.0', '623.0', '624.0', '625.0', '626.0', '627.0', '628.0', '629.0', '630.0', '631.0', '632.0', '633.0', '634.0', '635.0', '636.0', '637.0', '638.0', '639.0', '640.0', '641.0', '642.0', '643.0', '644.0', '645.0', '646.0', '647.0', '648.0', '649.0', '650.0', '651.0', '652.0', '653.0', '654.0', '655.0', '656.0', '657.0', '658.0', '659.0', '660.0', '661.0', '662.0', '663.0', '664.0', '665.0', '666.0', '667.0', '668.0', '669.0', '670.0', '671.0', '672.0', '673.0', '674.0', '675.0', '676.0', '677.0', '678.0', '679.0', '680.0', '681.0', '682.0', '683.0', '684.0', '685.0', '686.0', '687.0', '688.0', '689.0', '690.0', '691.0', '692.0', '693.0', '694.0', '695.0', '696.0', '697.0', '698.0', '699.0', '700.0', '701.0', '702.0', '703.0', '704.0', '705.0', '706.0', '707.0', '708.0', '709.0', '710.0', '711.0', '712.0', '713.0', '714.0', '715.0', '716.0', '717.0', '718.0', '719.0', '720.0', '721.0', '722.0', '723.0', '724.0', '725.0', '726.0', '727.0', '728.0', '729.0', '730.0', '731.0', '732.0', '733.0', '734.0', '735.0', '736.0', '737.0', '738.0', '739.0', '740.0', '741.0', '742.0', '743.0', '744.0', '745.0', '746.0', '747.0', '748.0', '749.0', '750.0', '751.0', '752.0', '753.0', '754.0', '755.0', '756.0', '757.0', '758.0', '759.0', '760.0', '761.0', '762.0', '763.0', '764.0', '765.0', '766.0', '767.0', '768.0', '769.0', '770.0', '771.0', '772.0', '773.0', '774.0', '775.0', '776.0', '777.0', '778.0', '779.0', '780.0', '781.0', '782.0', '783.0', '784.0', '785.0', '786.0', '787.0', '788.0', '789.0', '790.0', '791.0', '792.0', '793.0', '794.0', '795.0', '796.0', '797.0', '798.0', '799.0', '800.0', '801.0', '802.0', '803.0', '804.0', '805.0', '806.0', '807.0', '808.0', '809.0', '810.0', '811.0', '812.0', '813.0', '814.0', '815.0', '816.0', '817.0', '818.0', '819.0', '820.0', '821.0', '822.0', '823.0', '824.0', '825.0', '826.0', '827.0', '828.0', '829.0', '830.0', '831.0', '832.0', '833.0', '834.0', '835.0', '836.0', '837.0', '838.0', '839.0', '840.0', '841.0', '842.0', '843.0', '844.0', '845.0', '846.0', '847.0', '848.0', '849.0', '850.0', '851.0', '852.0', '853.0', '854.0', '855.0', '856.0', '857.0', '858.0', '859.0', '860.0', '861.0', '862.0', '863.0', '864.0', '865.0', '866.0', '867.0', '868.0', '869.0', '870.0', '871.0', '872.0', '873.0', '874.0', '875.0', '876.0', '877.0', '878.0', '879.0', '880.0', '881.0', '882.0', '883.0', '884.0', '885.0', '886.0', '887.0', '888.0', '889.0', '890.0', '891.0', '892.0', '893.0', '894.0', '895.0', '896.0', '897.0', '898.0', '899.0', '900.0', '901.0', '902.0', '903.0', '904.0', '905.0', '906.0', '907.0', '908.0', '909.0', '910.0', '911.0', '912.0', '913.0', '914.0', '915.0', '916.0', '917.0', '918.0', '919.0', '920.0', '921.0', '922.0', '923.0', '924.0', '925.0', '926.0', '927.0', '928.0', '929.0', '930.0', '931.0', '932.0', '933.0', '934.0', '935.0', '936.0', '937.0', '938.0', '939.0', '940.0', '941.0', '942.0', '943.0', '944.0', '945.0', '946.0', '947.0', '948.0', '949.0', '950.0', '951.0', '952.0', '953.0', '954.0', '955.0', '956.0', '957.0', '958.0', '959.0', '960.0', '961.0', '962.0', '963.0', '964.0', '965.0', '966.0', '967.0', '968.0', '969.0', '970.0', '971.0', '972.0', '973.0', '974.0', '975.0', '976.0', '977.0', '978.0', '979.0', '980.0', '981.0', '982.0', '983.0', '984.0', '985.0', '986.0', '987.0', '988.0', '989.0', '990.0', '991.0', '992.0', '993.0', '994.0', '995.0', '996.0', '997.0', '998.0', '999.0', '1000.0', '1001.0', '1002.0', '1003.0', '1004.0', '1005.0', '1006.0', '1007.0', '1008.0', '1009.0', '1010.0', '1011.0', '1012.0', '1013.0', '1014.0', '1015.0', '1016.0', '1017.0', '1018.0', '1019.0', '1020.0', '1021.0', '1022.0', '1023.0', '1024.0', '1025.0', '1026.0', '1027.0', '1028.0', '1029.0', '1030.0', '1031.0', '1032.0', '1033.0', '1034.0', '1035.0', '1036.0', '1037.0', '1038.0', '1039.0', '1040.0', '1041.0', '1042.0', '1043.0', '1044.0', '1045.0', '1046.0', '1047.0', '1048.0', '1049.0', '1050.0', '1051.0', '1052.0', '1053.0', '1054.0', '1055.0', '1056.0', '1057.0', '1058.0', '1059.0', '1060.0', '1061.0', '1062.0', '1063.0', '1064.0', '1065.0', '1066.0', '1067.0', '1068.0', '1069.0', '1070.0', '1071.0', '1072.0', '1073.0', '1074.0', '1075.0', '1076.0', '1077.0', '1078.0', '1079.0', '1080.0', '1081.0', '1082.0', '1083.0', '1084.0', '1085.0', '1086.0', '1087.0', '1088.0', '1089.0', '1090.0', '1091.0', '1092.0', '1093.0', '1094.0', '1095.0', '1096.0', '1097.0', '1098.0', '1099.0', '1100.0', '1101.0', '1102.0', '1103.0', '1104.0', '1105.0', '1106.0', '1107.0', '1108.0', '1109.0', '1110.0', '1111.0', '1112.0', '1113.0', '1114.0', '1115.0', '1116.0', '1117.0', '1118.0', '1119.0', '1120.0', '1121.0', '1122.0', '1123.0', '1124.0', '1125.0', '1126.0', '1127.0', '1128.0', '1129.0', '1130.0', '1131.0', '1132.0', '1133.0', '1134.0', '1135.0', '1136.0', '1137.0', '1138.0', '1139.0', '1140.0', '1141.0', '1142.0', '1143.0', '1144.0', '1145.0', '1146.0', '1147.0', '1148.0', '1149.0', '1150.0', '1151.0', '1152.0', '1153.0', '1154.0', '1155.0', '1156.0', '1157.0', '1158.0', '1159.0', '1160.0', '1161.0', '1162.0', '1163.0', '1164.0', '1165.0', '1166.0', '1167.0', '1168.0', '1169.0', '1170.0', '1171.0', '1172.0', '1173.0', '1174.0', '1175.0', '1176.0', '1177.0', '1178.0', '1179.0', '1180.0', '1181.0', '1182.0', '1183.0', '1184.0', '1185.0', '1186.0', '1187.0', '1188.0', '1189.0', '1190.0', '1191.0', '1192.0', '1193.0', '1194.0', '1195.0', '1196.0', '1197.0', '1198.0', '1199.0', '1200.0', '1201.0', '1202.0', '1203.0', '1204.0', '1205.0', '1206.0', '1207.0', '1208.0', '1209.0', '1210.0', '1211.0', '1212.0', '1213.0', '1214.0', '1215.0', '1216.0', '1217.0', '1218.0', '1219.0', '1220.0', '1221.0', '1222.0', '1223.0', '1224.0', '1225.0', '1226.0', '1227.0', '1228.0', '1229.0', '1230.0', '1231.0', '1232.0', '1233.0', '1234.0', '1235.0', '1236.0', '1237.0', '1238.0', '1239.0', '1240.0', '1241.0', '1242.0', '1243.0', '1244.0', '1245.0', '1246.0', '1247.0', '1248.0', '1249.0', '1250.0', '1251.0', '1252.0', '1253.0', '1254.0', '1255.0', '1256.0', '1257.0', '1258.0', '1259.0', '1260.0', '1261.0', '1262.0', '1263.0', '1264.0', '1265.0', '1266.0', '1267.0', '1268.0', '1269.0', '1270.0', '1271.0', '1272.0', '1273.0', '1274.0', '1275.0', '1276.0', '1277.0', '1278.0', '1279.0', '1280.0', '1281.0', '1282.0', '1283.0', '1284.0', '1285.0', '1286.0', '1287.0', '1288.0', '1289.0', '1290.0', '1291.0', '1292.0', '1293.0', '1294.0', '1295.0', '1296.0', '1297.0', '1298.0', '1299.0', '1300.0', '1301.0', '1302.0', '1303.0', '1304.0', '1305.0', '1306.0', '1307.0', '1308.0', '1309.0', '1310.0', '1311.0', '1312.0', '1313.0', '1314.0', '1315.0', '1316.0', '1317.0', '1318.0', '1319.0', '1320.0', '1321.0', '1322.0', '1323.0', '1324.0', '1325.0', '1326.0', '1327.0', '1328.0', '1329.0', '1330.0', '1331.0', '1332.0', '1333.0', '1334.0', '1335.0', '1336.0', '1337.0', '1338.0', '1339.0', '1340.0', '1341.0', '1342.0', '1343.0', '1344.0', '1345.0', '1346.0', '1347.0', '1348.0', '1349.0', '1350.0', '1351.0', '1352.0', '1353.0', '1354.0', '1355.0', '1356.0', '1357.0', '1358.0', '1359.0', '1360.0', '1361.0', '1362.0', '1363.0', '1364.0', '1365.0', '1366.0', '1367.0', '1368.0', '1369.0', '1370.0', '1371.0', '1372.0', '1373.0', '1374.0', '1375.0', '1376.0', '1377.0', '1378.0', '1379.0', '1380.0', '1381.0', '1382.0', '1383.0', '1384.0', '1385.0', '1386.0', '1387.0', '1388.0', '1389.0', '1390.0', '1391.0', '1392.0', '1393.0', '1394.0', '1395.0', '1396.0', '1397.0', '1398.0', '1399.0', '1400.0', '1401.0', '1402.0', '1403.0', '1404.0', '1405.0', '1406.0', '1407.0', '1408.0', '1409.0', '1410.0', '1411.0', '1412.0', '1413.0', '1414.0', '1415.0', '1416.0', '1417.0', '1418.0', '1419.0', '1420.0', '1421.0', '1422.0', '1423.0', '1424.0', '1425.0', '1426.0', '1427.0', '1428.0', '1429.0', '1430.0', '1431.0', '1432.0', '1433.0', '1434.0', '1435.0', '1436.0', '1437.0', '1438.0', '1439.0', '1440.0', '1441.0', '1442.0', '1443.0', '1444.0', '1445.0', '1446.0', '1447.0', '1448.0', '1449.0', '1450.0', '1451.0', '1452.0', '1453.0', '1454.0', '1455.0', '1456.0', '1457.0', '1458.0', '1459.0', '1460.0', '1461.0', '1462.0', '1463.0', '1464.0', '1465.0', '1466.0', '1467.0', '1468.0', '1469.0', '1470.0', '1471.0', '1472.0', '1473.0', '1474.0', '1475.0', '1476.0', '1477.0', '1478.0', '1479.0', '1480.0', '1481.0', '1482.0', '1483.0', '1484.0', '1485.0', '1486.0', '1487.0', '1488.0', '1489.0', '1490.0', '1491.0', '1492.0', '1493.0', '1494.0', '1495.0', '1496.0', '1497.0', '1498.0', '1499.0', '1500.0', '1501.0', '1502.0', '1503.0', '1504.0', '1505.0', '1506.0', '1507.0', '1508.0', '1509.0', '1510.0', '1511.0', '1512.0', '1513.0', '1514.0', '1515.0', '1516.0', '1517.0', '1518.0', '1519.0', '1520.0', '1521.0', '1522.0', '1523.0', '1524.0', '1525.0', '1526.0', '1527.0', '1528.0', '1529.0', '1530.0', '1531.0', '1532.0', '1533.0', '1534.0', '1535.0', '1536.0', '1537.0', '1538.0', '1539.0', '1540.0', '1541.0', '1542.0', '1543.0', '1544.0', '1545.0', '1546.0', '1547.0', '1548.0', '1549.0', '1550.0', '1551.0', '1552.0', '1553.0', '1554.0', '1555.0', '1556.0', '1557.0', '1558.0', '1559.0', '1560.0', '1561.0', '1562.0', '1563.0', '1564.0', '1565.0', '1566.0', '1567.0', '1568.0', '1569.0', '1570.0', '1571.0', '1572.0', '1573.0', '1574.0', '1575.0', '1576.0', '1577.0', '1578.0', '1579.0', '1580.0', '1581.0', '1582.0', '1583.0', '1584.0', '1585.0', '1586.0', '1587.0', '1588.0', '1589.0', '1590.0', '1591.0', '1592.0', '1593.0', '1594.0', '1595.0', '1596.0', '1597.0', '1598.0', '1599.0', '1600.0', '1601.0', '1602.0', '1603.0', '1604.0', '1605.0', '1606.0', '1607.0', '1608.0', '1609.0', '1610.0', '1611.0', '1612.0', '1613.0', '1614.0', '1615.0', '1616.0', '1617.0', '1618.0', '1619.0', '1620.0', '1621.0', '1622.0', '1623.0', '1624.0', '1625.0', '1626.0', '1627.0', '1628.0', '1629.0', '1630.0', '1631.0', '1632.0', '1633.0', '1634.0', '1635.0', '1636.0', '1637.0', '1638.0', '1639.0', '1640.0', '1641.0', '1642.0', '1643.0', '1644.0', '1645.0', '1646.0', '1647.0', '1648.0', '1649.0', '1650.0', '1651.0', '1652.0', '1653.0', '1654.0', '1655.0', '1656.0', '1657.0', '1658.0', '1659.0', '1660.0', '1661.0', '1662.0', '1663.0', '1664.0', '1665.0', '1666.0', '1667.0', '1668.0', '1669.0', '1670.0', '1671.0', '1672.0', '1673.0', '1674.0', '1675.0', '1676.0', '1677.0', '1678.0', '1679.0', '1680.0', '1681.0', '1682.0', '1683.0', '1684.0', '1685.0', '1686.0', '1687.0', '1688.0', '1689.0', '1690.0', '1691.0', '1692.0', '1693.0', '1694.0', '1695.0', '1696.0', '1697.0', '1698.0', '1699.0', '1700.0']

Index type: <class 'pandas.core.indexes.multi.MultiIndex'>
First 5 index values: MultiIndex([('['Ad5']',    '[100.0]'),
            ('['Ad5']', '[100000.0]'),
            ('['Ad5']',  '[12500.0]'),
            ('['Ad5']',   '[1562.0]'),
            ('['Ad5']',    '[195.0]')],
           names=['Label', 'Conc'])

Unique Label values (first 10):
1. "['Ad5']" (Type: <class 'str'>)
2. "['CoV2']" (Type: <class 'str'>)
3. "['CoV229E']" (Type: <class 'str'>)
4. "['CoV2B1']" (Type: <class 'str'>)
5. "['CoVNL63', 'FluB']" (Type: <class 'str'>)
6. "['CoVNL63', 'H1N1', 'RSVA2']" (Type: <class 'str'>)
7. "['CoVNL63', 'H1N1', 'RSVB1']" (Type: <class 'str'>)
8. "['CoVNL63', 'H1N1']" (Type: <class 'str'>)
9. "['CoVNL63', 'H3N2', 'RSVA2']" (Type: <class 'str'>)
10. "['CoVNL63', 'H3N2', 'RSVB1']" (Type: <class 'str'>)

Unique Conc values (first 10):
1. '[100.0]' (Type: <class 'str'>)
2. '[100000.0]' (Type: <class 'str'>)
3. '[12500.0]' (Type: <class 'str'>)
4. '[1562.0]' (Type: <class 'str'>)
5. '[195.0]' (Type: <class 'str'>)
6. '[25000.0]' (Type: <class 'str'>)
7. '[3125.0]' (Type: <class 'str'>)
8. '[391.0]' (Type: <class 'str'>)
9. '[50000.0]' (Type: <class 'str'>)
10. '[6250.0]' (Type: <class 'str'>)

Checking for mixed virus entries:

                             450.0     451.0     452.0     453.0     454.0  \
Label         Conc
['Ad5']       [100.0]     0.188456  0.193579  0.199298  0.205842  0.214035
              [100000.0]  0.108017  0.115627  0.123576  0.132051  0.140915
              [12500.0]   0.125390  0.136017  0.145695  0.155153  0.164305
              [1562.0]    0.144458  0.155678  0.165746  0.175237  0.184034
              [195.0]     0.142603  0.152603  0.161483  0.169983  0.177655
...                            ...       ...       ...       ...       ...
['RSVB1']     [50.0]      0.136810  0.138224  0.141741  0.146172  0.151672
              [50000.0]   0.154390  0.162458  0.167458  0.171000  0.172881
              [6250.0]    0.177224  0.182293  0.185483  0.187879  0.189190
              [781.0]     0.126759  0.135397  0.141224  0.145879  0.149379
['Reference'] [0.0]       0.159350  0.167391  0.175635  0.184376  0.193345

                             455.0     456.0     457.0     458.0     459.0  \
Label         Conc
['Ad5']       [100.0]     0.222088  0.230509  0.238614  0.246246  0.255404
              [100000.0]  0.149695  0.160068  0.166644  0.171949  0.176271
              [12500.0]   0.172593  0.181102  0.186508  0.190441  0.193508
              [1562.0]    0.191864  0.199475  0.204407  0.207966  0.210695
              [195.0]     0.184931  0.192069  0.197793  0.202759  0.208310
...                            ...       ...       ...       ...       ...
['RSVB1']     [50.0]      0.158603  0.166310  0.174000  0.182017  0.189966
              [50000.0]   0.173220  0.170322  0.170288  0.170932  0.172356
              [6250.0]    0.189483  0.187948  0.187966  0.188310  0.189276
              [781.0]     0.151500  0.151138  0.153155  0.155931  0.159466
['Reference'] [0.0]       0.202345  0.213487  0.219716  0.224497  0.228563

                          ...    1691.0    1692.0    1693.0    1694.0  \
Label         Conc        ...
['Ad5']       [100.0]     ...  0.724246  0.706123  0.688772  0.672316
              [100000.0]  ...  1.058237  1.045763  1.033407  1.020407
              [12500.0]   ...  1.031186  1.019051  1.007000  0.994695
              [1562.0]    ...  1.011746  1.001780  0.990966  0.979593
              [195.0]     ...  0.880224  0.866776  0.852776  0.838741
...                       ...       ...       ...       ...       ...
['RSVB1']     [50.0]      ...  0.744603  0.726397  0.707000  0.688672
              [50000.0]   ...  0.860475  0.851661  0.843661  0.836492
              [6250.0]    ...  0.815948  0.802086  0.791810  0.783845
              [781.0]     ...  0.735293  0.720603  0.709017  0.699397
['Reference'] [0.0]       ...  0.884071  0.872670  0.861655  0.850949

                            1695.0    1696.0    1697.0    1698.0    1699.0  \
Label         Conc
['Ad5']       [100.0]     0.656649  0.642035  0.628474  0.616544  0.603561
              [100000.0]  1.007390  0.992627  0.976119  0.957441  0.937000
              [12500.0]   0.982814  0.969153  0.953915  0.936441  0.918119
              [1562.0]    0.967610  0.954356  0.939966  0.923898  0.907797
              [195.0]     0.824276  0.809707  0.795000  0.779914  0.764931
...                            ...       ...       ...       ...       ...
['RSVB1']     [50.0]      0.671207  0.653741  0.637914  0.623000  0.611241
              [50000.0]   0.831085  0.823475  0.813983  0.801017  0.789203
              [6250.0]    0.781293  0.775534  0.767638  0.754776  0.744207
              [781.0]     0.694690  0.686190  0.675052  0.658069  0.643534
['Reference'] [0.0]       0.841188  0.829807  0.817056  0.801919  0.786701

                            1700.0
Label         Conc
['Ad5']       [100.0]     0.589719
              [100000.0]  0.914610
              [12500.0]   0.898695
              [1562.0]    0.891576
              [195.0]     0.750431
...                            ...
['RSVB1']     [50.0]      0.598483
              [50000.0]   0.778390
              [6250.0]    0.735483
              [781.0]     0.630948
['Reference'] [0.0]       0.771223

[2580 rows x 1251 columns]

In [27]:
# # Step 2: Fix mixed virus data format issues
# print("\nFixing mixed virus data...")
# fixed_df = fix_mixed_virus_data(avg_df)
# fixed_df

# FOR CLEAN CSV FORMAT, WE SKIP THE FIX STEP
# The data is already in the correct format, so we use avg_df directly
fixed_df = avg_df
fixed_df

                             450.0     451.0     452.0     453.0     454.0  \
Label         Conc
['Ad5']       [100.0]     0.188456  0.193579  0.199298  0.205842  0.214035
              [100000.0]  0.108017  0.115627  0.123576  0.132051  0.140915
              [12500.0]   0.125390  0.136017  0.145695  0.155153  0.164305
              [1562.0]    0.144458  0.155678  0.165746  0.175237  0.184034
              [195.0]     0.142603  0.152603  0.161483  0.169983  0.177655
...                            ...       ...       ...       ...       ...
['RSVB1']     [50.0]      0.136810  0.138224  0.141741  0.146172  0.151672
              [50000.0]   0.154390  0.162458  0.167458  0.171000  0.172881
              [6250.0]    0.177224  0.182293  0.185483  0.187879  0.189190
              [781.0]     0.126759  0.135397  0.141224  0.145879  0.149379
['Reference'] [0.0]       0.159350  0.167391  0.175635  0.184376  0.193345

                             455.0     456.0     457.0     458.0     459.0  \
Label         Conc
['Ad5']       [100.0]     0.222088  0.230509  0.238614  0.246246  0.255404
              [100000.0]  0.149695  0.160068  0.166644  0.171949  0.176271
              [12500.0]   0.172593  0.181102  0.186508  0.190441  0.193508
              [1562.0]    0.191864  0.199475  0.204407  0.207966  0.210695
              [195.0]     0.184931  0.192069  0.197793  0.202759  0.208310
...                            ...       ...       ...       ...       ...
['RSVB1']     [50.0]      0.158603  0.166310  0.174000  0.182017  0.189966
              [50000.0]   0.173220  0.170322  0.170288  0.170932  0.172356
              [6250.0]    0.189483  0.187948  0.187966  0.188310  0.189276
              [781.0]     0.151500  0.151138  0.153155  0.155931  0.159466
['Reference'] [0.0]       0.202345  0.213487  0.219716  0.224497  0.228563

                          ...    1691.0    1692.0    1693.0    1694.0  \
Label         Conc        ...
['Ad5']       [100.0]     ...  0.724246  0.706123  0.688772  0.672316
              [100000.0]  ...  1.058237  1.045763  1.033407  1.020407
              [12500.0]   ...  1.031186  1.019051  1.007000  0.994695
              [1562.0]    ...  1.011746  1.001780  0.990966  0.979593
              [195.0]     ...  0.880224  0.866776  0.852776  0.838741
...                       ...       ...       ...       ...       ...
['RSVB1']     [50.0]      ...  0.744603  0.726397  0.707000  0.688672
              [50000.0]   ...  0.860475  0.851661  0.843661  0.836492
              [6250.0]    ...  0.815948  0.802086  0.791810  0.783845
              [781.0]     ...  0.735293  0.720603  0.709017  0.699397
['Reference'] [0.0]       ...  0.884071  0.872670  0.861655  0.850949

                            1695.0    1696.0    1697.0    1698.0    1699.0  \
Label         Conc
['Ad5']       [100.0]     0.656649  0.642035  0.628474  0.616544  0.603561
              [100000.0]  1.007390  0.992627  0.976119  0.957441  0.937000
              [12500.0]   0.982814  0.969153  0.953915  0.936441  0.918119
              [1562.0]    0.967610  0.954356  0.939966  0.923898  0.907797
              [195.0]     0.824276  0.809707  0.795000  0.779914  0.764931
...                            ...       ...       ...       ...       ...
['RSVB1']     [50.0]      0.671207  0.653741  0.637914  0.623000  0.611241
              [50000.0]   0.831085  0.823475  0.813983  0.801017  0.789203
              [6250.0]    0.781293  0.775534  0.767638  0.754776  0.744207
              [781.0]     0.694690  0.686190  0.675052  0.658069  0.643534
['Reference'] [0.0]       0.841188  0.829807  0.817056  0.801919  0.786701

                            1700.0
Label         Conc
['Ad5']       [100.0]     0.589719
              [100000.0]  0.914610
              [12500.0]   0.898695
              [1562.0]    0.891576
              [195.0]     0.750431
...                            ...
['RSVB1']     [50.0]      0.598483
              [50000.0]   0.778390
              [6250.0]    0.735483
              [781.0]     0.630948
['Reference'] [0.0]       0.771223

[2580 rows x 1251 columns]

In [31]:
# Step 3: Parse virus names and concentrations with updated function
print("\nParsing virus names and concentrations...")
parsed_data = parse_mixed_virus_data(fixed_df)
# Print summary of parsed data types
mixture_types = {}
for idx, data in parsed_data.items():
    mixture_type = data["type"]
    if mixture_type not in mixture_types:
        mixture_types[mixture_type] = 0
    mixture_types[mixture_type] += 1
print("\nSummary of parsed data:")
for mixture_type, count in mixture_types.items():
    print(f"  {mixture_type}: {count} samples")

Parsing virus names and concentrations...

Summary of parsed data:
  single: 150 samples
  double: 960 samples
  triple: 1470 samples

In [32]:
parsed_data

{("['Ad5']", '[100.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [100.0]},
 ("['Ad5']", '[100000.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [100000.0]},
 ("['Ad5']", '[12500.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [12500.0]},
 ("['Ad5']", '[1562.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [1562.0]},
 ("['Ad5']", '[195.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [195.0]},
 ("['Ad5']", '[25000.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [25000.0]},
 ("['Ad5']", '[3125.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [3125.0]},
 ("['Ad5']", '[391.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [391.0]},
 ("['Ad5']", '[50000.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [50000.0]},
 ("['Ad5']", '[6250.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [6250.0]},
 ("['Ad5']", '[781.0]'): {'type': 'single',
  'virus_names': ['Ad5'],
  'concentrations': [781.0]},
 ("['CoV2']", '[100.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [100.0]},
 ("['CoV2']", '[100000.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [100000.0]},
 ("['CoV2']", '[12500.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [12500.0]},
 ("['CoV2']", '[1562.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [1562.0]},
 ("['CoV2']", '[195.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [195.0]},
 ("['CoV2']", '[25000.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [25000.0]},
 ("['CoV2']", '[3125.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [3125.0]},
 ("['CoV2']", '[391.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [391.0]},
 ("['CoV2']", '[50000.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [50000.0]},
 ("['CoV2']", '[6250.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [6250.0]},
 ("['CoV2']", '[781.0]'): {'type': 'single',
  'virus_names': ['CoV2'],
  'concentrations': [781.0]},
 ("['CoV229E']", '[100.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [100.0]},
 ("['CoV229E']", '[100000.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [100000.0]},
 ("['CoV229E']", '[12500.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [12500.0]},
 ("['CoV229E']", '[1562.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [1562.0]},
 ("['CoV229E']", '[195.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [195.0]},
 ("['CoV229E']", '[25000.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [25000.0]},
 ("['CoV229E']", '[3125.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [3125.0]},
 ("['CoV229E']", '[391.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [391.0]},
 ("['CoV229E']", '[50.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [50.0]},
 ("['CoV229E']", '[50000.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [50000.0]},
 ("['CoV229E']", '[6250.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [6250.0]},
 ("['CoV229E']", '[781.0]'): {'type': 'single',
  'virus_names': ['CoV229E'],
  'concentrations': [781.0]},
 ("['CoV2B1']", '[100.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [100.0]},
 ("['CoV2B1']", '[100000.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [100000.0]},
 ("['CoV2B1']", '[12500.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [12500.0]},
 ("['CoV2B1']", '[1562.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [1562.0]},
 ("['CoV2B1']", '[195.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [195.0]},
 ("['CoV2B1']", '[25000.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [25000.0]},
 ("['CoV2B1']", '[3125.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [3125.0]},
 ("['CoV2B1']", '[391.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [391.0]},
 ("['CoV2B1']", '[50000.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [50000.0]},
 ("['CoV2B1']", '[6250.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [6250.0]},
 ("['CoV2B1']", '[781.0]'): {'type': 'single',
  'virus_names': ['CoV2B1'],
  'concentrations': [781.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[100000.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [100000.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[12500.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [12500.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[1562.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [1562.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[195.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [195.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[25000.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [25000.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[3125.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [3125.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[391.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [391.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[50000.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [50000.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[6250.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [6250.0, 781.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 100000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 100000.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 12500.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 12500.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 1562.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 1562.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 195.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 195.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 25000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 25000.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 3125.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 3125.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 391.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 391.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 50000.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 50000.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 6250.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 6250.0]},
 ("['CoVNL63', 'FluB']", '[781.0, 781.0]'): {'type': 'double',
  'virus_names': ['CoVNL63', 'FluB'],
  'concentrations': [781.0, 781.0]},
 ("['CoVNL63', 'H1N1', 'RSVA2']",
  '[100000.0, 100000.0, 100000.0]'): {'type': 'triple', 'virus_names': ['CoVNL63',
   'H1N1',
   'RSVA2'], 'concentrations': [100000.0, 100000.0, 100000.0]},
 ("['CoVNL63', 'H1N1', 'RSVA2']",
  '[100000.0, 100000.0, 1562.0]'): {'type': 'triple', 'virus_names': ['CoVNL63',
   'H1N1',
   'RSVA2'], 'concentrations': [100000.0, 100000.0, 1562.0]},
 ("['CoVNL63', 'H1N1', 'RSVA2']",
  '[100000.0, 100000.0, 25000.0]'): {'type': 'triple', 'virus_names': ['CoVNL63',
   'H1N1',
   'RSVA2'], 'concentrations': [100000.0, 100000.0, 25000.0]},
 ("['CoVNL63', 'H1N1', 'RSVA2']",
  '[100000.0, 100000.0, 391.0]'): {'type': 'triple', 'virus_names': ['CoVNL63',
   'H1N1',
   'RSVA2'], 'concentrations': [100000.0, 100000.0, 391.0]},
 ("['CoVNL63', 'H1N1', 'RSVA2']",
  '[100000.0, 100000.0, 50000.0]'): {'type': 'triple', 'virus_names': ['CoVNL63',
   'H1N1',

In [33]:
# Step 4: Get the highest concentration rows for single-virus labels
highest_single_virus_conc_df = get_single_virus_highest_concentration_rows(avg_df)
print("\nHighest concentration single virus DataFrame shape:", highest_single_virus_conc_df.shape)
highest_single_virus_conc_df

Extracting single virus data...
Found 150 single virus samples
Example concentration values:
['[100.0]', '[100000.0]', '[12500.0]', '[1562.0]', '[195.0]']
After parsing concentrations:
     Label        Conc  Conc_parsed
0  ['Ad5']     [100.0]        100.0
1  ['Ad5']  [100000.0]     100000.0
2  ['Ad5']   [12500.0]      12500.0
3  ['Ad5']    [1562.0]       1562.0
4  ['Ad5']     [195.0]        195.0
Found 14 unique single virus types
Highest concentration for ['Ad5']: [100000.0]
Highest concentration for ['CoV2']: [100000.0]
Highest concentration for ['CoV229E']: [100000.0]
Highest concentration for ['CoV2B1']: [100000.0]
Highest concentration for ['CoVNL63']: [100000.0]
Highest concentration for ['CoVOC43']: [100000.0]
Highest concentration for ['FluB']: [100000.0]
Highest concentration for ['H1N1']: [100000.0]
Highest concentration for ['H3N2']: [100000.0]
Highest concentration for ['HMPVA']: [100000.0]
Highest concentration for ['HMPVB']: [100000.0]
Highest concentration for ['RSVA2']: [100000.0]
Highest concentration for ['RSVB1']: [100000.0]
Highest concentration for ['Reference']: [0.0]
Final result has 14 rows

Highest concentration single virus DataFrame shape: (14, 1253)

,Label,Conc,450.0,451.0,452.0,453.0,454.0,455.0,456.0,457.0,...,1691.0,1692.0,1693.0,1694.0,1695.0,1696.0,1697.0,1698.0,1699.0,1700.0
1,['Ad5'],[100000.0],0.108017,0.115627,0.123576,0.132051,0.140915,0.149695,0.160068,0.166644,...,1.058237,1.045763,1.033407,1.020407,1.007390,0.992627,0.976119,0.957441,0.937000,0.914610
12,['CoV2'],[100000.0],0.143678,0.158237,0.170542,0.182068,0.192441,0.201322,0.209508,0.215186,...,0.970017,0.953678,0.940966,0.930339,0.924712,0.915695,0.904000,0.887271,0.871712,0.857068
23,['CoV229E'],[100000.0],0.026228,0.023702,0.023737,0.024930,0.027228,0.030421,0.036719,0.038281,...,1.206211,1.187544,1.167246,1.145368,1.122035,1.097088,1.070860,1.042912,1.014982,0.987281
35,['CoV2B1'],[100000.0],0.309544,0.322877,0.337579,0.353386,0.369930,0.386789,0.407053,0.419105,...,1.195842,1.181596,1.163491,1.141491,1.114737,1.087912,1.061368,1.034211,1.010965,0.990649
2036,['CoVNL63'],[100000.0],0.059492,0.065085,0.071356,0.077983,0.084492,0.090576,0.098661,0.100508,...,1.009051,1.005831,0.999797,0.991441,0.979644,0.967000,0.953153,0.938627,0.922085,0.903356
2048,['CoVOC43'],[100000.0],0.131847,0.137356,0.146068,0.156712,0.168932,0.182966,0.200000,0.214000,...,1.144441,1.152814,1.158136,1.161000,1.160203,1.157237,1.151763,1.143576,1.132695,1.118966
2060,['FluB'],[100000.0],0.109414,0.115172,0.122069,0.129431,0.137362,0.145586,0.154707,0.162293,...,1.108776,1.088431,1.070414,1.053431,1.040483,1.022914,1.001603,0.973517,0.946621,0.920534
2291,['H1N1'],[100000.0],0.055175,0.060404,0.066579,0.073368,0.080491,0.087807,0.096965,0.102035,...,1.770947,1.741158,1.709351,1.675930,1.640737,1.603491,1.564316,1.522561,1.480333,1.437632
2522,['H3N2'],[100000.0],0.071136,0.082153,0.091068,0.099373,0.106763,0.112949,0.118864,0.121186,...,1.734593,1.702339,1.668220,1.632780,1.595763,1.557542,1.518068,1.477373,1.435153,1.391475
2533,['HMPVA'],[100000.0],0.040729,0.044136,0.048949,0.054610,0.060898,0.067644,0.076390,0.081068,...,0.961932,0.952593,0.941746,0.929186,0.915051,0.899339,0.882271,0.863085,0.844153,0.825271
2545,['HMPVB'],[100000.0],0.279271,0.295559,0.310780,0.325644,0.339881,0.353508,0.366085,0.378864,...,1.076373,1.072373,1.068119,1.063458,1.058949,1.051441,1.041220,1.026610,1.011712,0.996288
2557,['RSVA2'],[100000.0],0.319789,0.334526,0.346123,0.356263,0.364596,0.370772,0.374404,0.377140,...,0.753018,0.747860,0.740825,0.732754,0.721368,0.713825,0.709316,0.710228,0.709439,0.707053
2568,['RSVB1'],[100000.0],0.163441,0.167763,0.171153,0.174136,0.176763,0.178864,0.180119,0.181390,...,0.933102,0.923441,0.914661,0.906864,0.900559,0.892932,0.883915,0.873220,0.861610,0.849254
2579,['Reference'],[0.0],0.159350,0.167391,0.175635,0.184376,0.193345,0.202345,0.213487,0.219716,...,0.884071,0.872670,0.861655,0.850949,0.841188,0.829807,0.817056,0.801919,0.786701,0.771223

In [34]:
# Prepare reference data
reference_series = pd.read_csv(DATA_FOLDER + "/SiO2 - only GLF.txt", sep='\t', header=None, index_col=0).squeeze('columns')
reference_series.index = reference_series.index.astype(str) + '.0'  # Convert index to string and append '.0'

# Ensure reference series has the same wavenumbers
wavenumbers = highest_single_virus_conc_df.columns[2:]  # Exclude 'Label' and 'Conc'
reference_series = reference_series.reindex(wavenumbers)

In [35]:
# Step 5: Process the fixed dataframe
print("\nProcessing all samples...")
predicted_df, result_df = process_dataframe(fixed_df, parsed_data, highest_single_virus_conc_df, reference_series)

Processing all samples...

Processing sample: Label=['Ad5'], Conc=[100.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [100.0]
Fitted coefficients: [0.20600991 0.79399009]

Processing sample: Label=['Ad5'], Conc=[100000.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999925e-01 7.52312299e-08]

Processing sample: Label=['Ad5'], Conc=[12500.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.81237653 0.18762347]

Processing sample: Label=['Ad5'], Conc=[1562.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.59467719 0.40532281]

Processing sample: Label=['Ad5'], Conc=[195.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [195.0]
Fitted coefficients: [0.27403126 0.72596874]

Processing sample: Label=['Ad5'], Conc=[25000.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.87731693 0.12268307]

Processing sample: Label=['Ad5'], Conc=[3125.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.66241752 0.33758248]

Processing sample: Label=['Ad5'], Conc=[391.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [391.0]
Fitted coefficients: [0.42955507 0.57044493]

Processing sample: Label=['Ad5'], Conc=[50000.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.96002218 0.03997782]

Processing sample: Label=['Ad5'], Conc=[6250.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.7434221 0.2565779]

Processing sample: Label=['Ad5'], Conc=[781.0]
Parsed viruses: ['Ad5']
Parsed concentrations: [781.0]
Fitted coefficients: [0.51904205 0.48095795]

Processing sample: Label=['CoV2'], Conc=[100.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [100.0]
Fitted coefficients: [0.76319871 0.23680129]

Processing sample: Label=['CoV2'], Conc=[100000.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999999e-01 1.13548693e-09]

Processing sample: Label=['CoV2'], Conc=[12500.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.93416382 0.06583618]

Processing sample: Label=['CoV2'], Conc=[1562.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.83338634 0.16661366]

Processing sample: Label=['CoV2'], Conc=[195.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [195.0]
Fitted coefficients: [0.77288874 0.22711126]

Processing sample: Label=['CoV2'], Conc=[25000.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.95133645 0.04866355]

Processing sample: Label=['CoV2'], Conc=[3125.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.85506664 0.14493336]

Processing sample: Label=['CoV2'], Conc=[391.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [391.0]
Fitted coefficients: [0.79740358 0.20259642]

Processing sample: Label=['CoV2'], Conc=[50000.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.97900258 0.02099742]

Processing sample: Label=['CoV2'], Conc=[6250.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.87829914 0.12170086]

Processing sample: Label=['CoV2'], Conc=[781.0]
Parsed viruses: ['CoV2']
Parsed concentrations: [781.0]
Fitted coefficients: [0.81690566 0.18309434]

Processing sample: Label=['CoV229E'], Conc=[100.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [100.0]
Fitted coefficients: [0.15106902 0.84893098]

Processing sample: Label=['CoV229E'], Conc=[100000.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [100000.0]
Fitted coefficients: [1.00000000e+00 1.00000008e-10]

/tmp/ipykernel_2529799/2434598198.py:386: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat([result_df, pd.DataFrame([result_row])], ignore_index=True)

Processing sample: Label=['CoV229E'], Conc=[12500.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.89482784 0.10517216]

Processing sample: Label=['CoV229E'], Conc=[1562.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.8582144 0.1417856]

Processing sample: Label=['CoV229E'], Conc=[195.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [195.0]
Fitted coefficients: [0.40702021 0.59297979]

Processing sample: Label=['CoV229E'], Conc=[25000.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.95944541 0.04055459]

Processing sample: Label=['CoV229E'], Conc=[3125.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.86966512 0.13033488]

Processing sample: Label=['CoV229E'], Conc=[391.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [391.0]
Fitted coefficients: [0.60583677 0.39416323]

Processing sample: Label=['CoV229E'], Conc=[50.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [50.0]
Fitted coefficients: [0.09789508 0.90210492]

Processing sample: Label=['CoV229E'], Conc=[50000.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.97524911 0.02475089]

Processing sample: Label=['CoV229E'], Conc=[6250.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.86469933 0.13530067]

Processing sample: Label=['CoV229E'], Conc=[781.0]
Parsed viruses: ['CoV229E']
Parsed concentrations: [781.0]
Fitted coefficients: [0.69927886 0.30072114]

Processing sample: Label=['CoV2B1'], Conc=[100.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [100.0]
Fitted coefficients: [0.23152708 0.76847292]

Processing sample: Label=['CoV2B1'], Conc=[100000.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999998e-01 1.65881753e-09]

Processing sample: Label=['CoV2B1'], Conc=[12500.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.79484013 0.20515987]

Processing sample: Label=['CoV2B1'], Conc=[1562.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.62917029 0.37082971]

Processing sample: Label=['CoV2B1'], Conc=[195.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [195.0]
Fitted coefficients: [0.49387491 0.50612509]

Processing sample: Label=['CoV2B1'], Conc=[25000.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.87003423 0.12996577]

Processing sample: Label=['CoV2B1'], Conc=[3125.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.68962473 0.31037527]

Processing sample: Label=['CoV2B1'], Conc=[391.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [391.0]
Fitted coefficients: [0.5397751  0.46022491]

Processing sample: Label=['CoV2B1'], Conc=[50000.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.93704654 0.06295346]

Processing sample: Label=['CoV2B1'], Conc=[6250.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.74634132 0.25365868]

Processing sample: Label=['CoV2B1'], Conc=[781.0]
Parsed viruses: ['CoV2B1']
Parsed concentrations: [781.0]
Fitted coefficients: [0.58289668 0.41710332]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [0.52324687 0.44445799 0.03229514]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.56309171 0.33036475 0.10654355]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.57557323 0.17368472 0.25074204]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [0.57698449 0.02584177 0.39717375]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.53896246 0.38492333 0.07611421]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.55747317 0.23557572 0.2069511 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.59161197 0.05975729 0.34863074]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.55480402 0.40366581 0.04153017]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.55416225 0.28398566 0.1618521 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.58826204 0.1195069  0.29223106]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [2.70013244e-01 7.29986756e-01 1.00000472e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.2574067  0.68716634 0.05542696]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.2966731  0.50019103 0.20313587]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.30328926 0.35871743 0.33799332]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.23330615 0.75517167 0.01152218]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.27103732 0.56338977 0.16557291]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.31179771 0.4037897  0.2844126 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [2.50643047e-01 7.49356953e-01 1.00000000e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.27548247 0.61977183 0.1047457 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[12500.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.29697117 0.44639033 0.25663851]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [1.45502335e-01 8.54497664e-01 1.00000173e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.10341006 0.83206044 0.0645295 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.12161207 0.63535995 0.24302799]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.14939367 0.44762576 0.40298057]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.09312464 0.90491942 0.00195594]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.12208997 0.69042715 0.18748288]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.15864491 0.47969764 0.36165745]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [1.17719146e-01 8.82280854e-01 1.00000000e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.10709578 0.77503339 0.11787084]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.13171209 0.56569955 0.30258836]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [0.05988095 0.59730556 0.34281349]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [0.08616844 0.49171819 0.42211337]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [0.06200756 0.28526334 0.6527291 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.03712788 0.11819663 0.84467549]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [0.07644615 0.55306449 0.37048936]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [0.06657146 0.38330483 0.55012371]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [0.04942045 0.15529343 0.79528611]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [0.06492445 0.5901627  0.34491285]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [0.07681421 0.43560491 0.48758088]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[195.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [0.05100067 0.22363595 0.72536338]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [4.61329408e-01 5.38670592e-01 1.00000000e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.44770746 0.4766019  0.07569064]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 1562.0]
Fitted coefficients: [0.47087368 0.32566088 0.20346544]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.49520891 0.18172411 0.32306698]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.43738649 0.53999663 0.02261688]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.46330605 0.36364935 0.17304461]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.4881493  0.20757151 0.30427919]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [4.257915e-01 5.742085e-01 1.000000e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.45205969 0.43232749 0.11561283]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.49413785 0.26519722 0.24066493]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [1.91539426e-01 8.08460574e-01 1.00186408e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.14235856 0.83377727 0.02386417]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.16142907 0.65034514 0.18822579]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.19396573 0.48092365 0.32511062]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [1.43057158e-01 8.56942842e-01 1.00000036e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.1433615  0.71010864 0.14652986]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.18764315 0.50418355 0.3081733 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [1.59040330e-01 8.40959670e-01 1.00000237e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.12093653 0.78465498 0.09440849]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[3125.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.17561929 0.56847425 0.25590646]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.08215158 0.70369276 0.21415566]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.07882075 0.59798083 0.32319842]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.10751868 0.39005129 0.50243003]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.07855709 0.19916866 0.72227424]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.06953072 0.65596875 0.27450053]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.09315652 0.45726119 0.44958229]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.07903642 0.2432412  0.67772238]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.06874434 0.67835274 0.25290292]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.08879543 0.53881795 0.37238661]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[391.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.08591863 0.3213731  0.59270827]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [6.16436417e-01 3.83563582e-01 1.00000022e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.62450258 0.28870353 0.08679389]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.65221435 0.14372223 0.20406341]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [6.62544576e-01 1.00050942e-10 3.37455422e-01]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.62777367 0.34155065 0.03067568]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.64677613 0.17722299 0.17600088]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.66321152 0.03130165 0.30548683]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.60633175 0.38649304 0.0071752 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.61874552 0.25722791 0.12402657]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.65586501 0.08476152 0.25937347]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [2.14631870e-01 7.85368130e-01 1.00001021e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.19023688 0.76833562 0.0414275 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.24000872 0.58174489 0.17824639]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.26745558 0.41467221 0.31787222]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 25000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Fitted coefficients: [2.02935019e-01 7.97064981e-01 1.00000014e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.2072471 0.6301425 0.1626104]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.25163378 0.45233074 0.29603547]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [1.96305337e-01 8.03694663e-01 1.00000024e-10]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.19772942 0.70876504 0.09350555]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.25520066 0.51807383 0.22672551]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.07714636 0.83310602 0.08974762]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 12500.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.08944767 0.69214087 0.21841146]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.12486914 0.50449504 0.37063582]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 195.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.13723575 0.31847833 0.54428592]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.07968413 0.76777063 0.15254525]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.12814803 0.54575857 0.3260934 ]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 391.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.13467013 0.36997305 0.49535682]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.07874381 0.79611325 0.12514294]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.10617597 0.62683712 0.26698691]

Processing sample: Label=['CoVNL63', 'FluB'], Conc=[781.0, 781.0]
Parsed viruses: ['CoVNL63', 'FluB']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.14258066 0.42456477 0.43285457]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 100000.0]
Fitted coefficients: [0.36569665 0.40715864 0.19685061 0.0302941 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 1562.0]
Fitted coefficients: [0.43249064 0.43297341 0.05514085 0.0793951 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 25000.0]
Fitted coefficients: [0.42793789 0.3929318  0.12160892 0.05752138]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 391.0]
Fitted coefficients: [0.38696428 0.49780571 0.01394427 0.10128574]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 50000.0]
Fitted coefficients: [0.35573348 0.42062716 0.16153227 0.06210708]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 6250.0]
Fitted coefficients: [0.46891492 0.38306577 0.08260952 0.0654098 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 781.0]
Fitted coefficients: [0.47916042 0.40873895 0.04006068 0.07203995]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 100000.0]
Fitted coefficients: [0.50507376 0.06090903 0.27409908 0.15991813]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 1562.0]
Fitted coefficients: [0.63559067 0.07573063 0.06220703 0.22647167]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 25000.0]
Fitted coefficients: [0.54339013 0.06560446 0.16033401 0.23067139]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 391.0]
Fitted coefficients: [0.64636725 0.08084544 0.03855086 0.23423645]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 50000.0]
Fitted coefficients: [0.48435337 0.06509736 0.2158154  0.23473388]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 6250.0]
Fitted coefficients: [0.55337535 0.07331011 0.1258184  0.24749614]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 781.0]
Fitted coefficients: [0.62587926 0.08042562 0.05784759 0.23584753]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 100000.0]
Fitted coefficients: [0.42881867 0.20087813 0.25680311 0.11350009]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 1562.0]
Fitted coefficients: [0.50351908 0.23449808 0.09819908 0.16378377]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 25000.0]
Fitted coefficients: [0.48022582 0.19596209 0.16961674 0.15419536]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 391.0]
Fitted coefficients: [0.52876345 0.23954024 0.06673299 0.16496333]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 50000.0]
Fitted coefficients: [0.45602925 0.21622027 0.17234351 0.15540698]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 6250.0]
Fitted coefficients: [0.47924643 0.21909998 0.14729804 0.15435555]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 781.0]
Fitted coefficients: [0.54880922 0.21977189 0.07510635 0.15631253]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 100000.0]
Fitted coefficients: [5.49087806e-01 1.00036144e-10 3.22872257e-01 1.28039937e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 1562.0]
Fitted coefficients: [7.28742166e-01 1.00150999e-10 9.06296846e-02 1.80628149e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 25000.0]
Fitted coefficients: [5.99277868e-01 1.00000000e-10 1.96683939e-01 2.04038193e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 391.0]
Fitted coefficients: [7.66172525e-01 1.00167062e-10 4.35079902e-02 1.90319484e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 50000.0]
Fitted coefficients: [5.87753620e-01 1.83972429e-10 2.33887636e-01 1.78358747e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 6250.0]
Fitted coefficients: [6.54789048e-01 1.00000000e-10 1.53818533e-01 1.91392419e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 781.0]
Fitted coefficients: [7.05964350e-01 1.00000000e-10 6.51099623e-02 2.28925688e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 100000.0]
Fitted coefficients: [0.40089704 0.3030635  0.21225289 0.08378657]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 1562.0]
Fitted coefficients: [0.53531437 0.27216811 0.08398534 0.10853218]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 25000.0]
Fitted coefficients: [0.41930483 0.28253406 0.16147587 0.13668524]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 391.0]
Fitted coefficients: [0.51363409 0.31528812 0.05180473 0.11927306]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 50000.0]
Fitted coefficients: [0.47277699 0.22424081 0.17403144 0.12895076]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 6250.0]
Fitted coefficients: [0.41502507 0.30048501 0.13487282 0.1496171 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 781.0]
Fitted coefficients: [0.54036395 0.27898597 0.06344422 0.11720585]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 100000.0]
Fitted coefficients: [0.45126587 0.13233376 0.25396951 0.16243086]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 1562.0]
Fitted coefficients: [0.50236525 0.15119411 0.09635606 0.25008458]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 25000.0]
Fitted coefficients: [0.47911422 0.12025954 0.17275494 0.2278713 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 391.0]
Fitted coefficients: [0.61207792 0.13847376 0.04286052 0.2065878 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 50000.0]
Fitted coefficients: [0.49789613 0.11400998 0.17693142 0.21116247]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 6250.0]
Fitted coefficients: [0.53970593 0.10877115 0.13476253 0.21676039]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 781.0]
Fitted coefficients: [0.54948764 0.15242537 0.06670763 0.23137936]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 100000.0]
Fitted coefficients: [0.48494077 0.03986923 0.30439929 0.17079072]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 1562.0]
Fitted coefficients: [0.64158966 0.0356073  0.07316534 0.2496377 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 25000.0]
Fitted coefficients: [0.57116494 0.02115468 0.18640718 0.22127319]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 391.0]
Fitted coefficients: [0.68427698 0.05022442 0.02650192 0.23899669]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 50000.0]
Fitted coefficients: [0.56505919 0.0303773  0.18881676 0.21574675]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 6250.0]
Fitted coefficients: [0.59135352 0.0299367  0.13364118 0.24506861]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[100000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 781.0]
Fitted coefficients: [0.6635866  0.03469805 0.06076607 0.24094927]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 100000.0]
Fitted coefficients: [0.10501264 0.53789847 0.34566989 0.011419  ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 1562.0]
Fitted coefficients: [0.15683308 0.64735793 0.10373788 0.0920711 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 25000.0]
Fitted coefficients: [0.12920129 0.60092801 0.19463982 0.07523089]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 391.0]
Fitted coefficients: [0.17890683 0.66961235 0.05393936 0.09754146]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 50000.0]
Fitted coefficients: [0.11337646 0.60414793 0.21171571 0.0707599 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 6250.0]
Fitted coefficients: [0.15854937 0.57917234 0.16844143 0.09383686]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 781.0]
Fitted coefficients: [0.14867249 0.68487324 0.0732928  0.09316148]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 100000.0]
Fitted coefficients: [0.1770236  0.14448925 0.44781734 0.23066982]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 1562.0]
Fitted coefficients: [0.26901549 0.17374604 0.16417638 0.3930621 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 25000.0]
Fitted coefficients: [0.19263228 0.1216369  0.33252959 0.35320123]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 391.0]
Fitted coefficients: [0.3284449  0.17970309 0.10445839 0.38739362]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 50000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.141442   0.12773038 0.37108588 0.35974174]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 6250.0]
Fitted coefficients: [0.22865051 0.16221183 0.21600268 0.39313498]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 781.0]
Fitted coefficients: [0.27430394 0.17799362 0.13899228 0.40871016]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 100000.0]
Fitted coefficients: [0.02730902 0.35988698 0.46596223 0.14684176]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 1562.0]
Fitted coefficients: [0.13496516 0.42067959 0.18867648 0.25567878]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 25000.0]
Fitted coefficients: [0.0957174  0.35657068 0.30254064 0.24517129]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 391.0]
Fitted coefficients: [0.13776178 0.46101994 0.13293052 0.26828776]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 50000.0]
Fitted coefficients: [0.06471716 0.33502233 0.36666785 0.23359266]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 6250.0]
Fitted coefficients: [0.1122925  0.40321056 0.236234   0.24826294]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 781.0]
Fitted coefficients: [0.15883031 0.4339443  0.15463769 0.25258769]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 100000.0]
Fitted coefficients: [0.22048542 0.02625993 0.59251672 0.16073793]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 1562.0]
Fitted coefficients: [0.42418895 0.01687363 0.21735407 0.34158335]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 25000.0]
Fitted coefficients: [2.66594553e-01 1.00000411e-10 4.06768129e-01 3.26637318e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 391.0]
Fitted coefficients: [0.48586892 0.03003692 0.15064398 0.33345018]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 50000.0]
Fitted coefficients: [2.63308563e-01 1.00003103e-10 4.31297963e-01 3.05393474e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 6250.0]
Fitted coefficients: [3.01776735e-01 1.53018116e-04 3.23752761e-01 3.74317486e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 781.0]
Fitted coefficients: [0.39967426 0.01148671 0.18721696 0.40162208]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 100000.0]
Fitted coefficients: [0.05370959 0.4555711  0.37535918 0.11536013]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 1562.0]
Fitted coefficients: [0.13344898 0.50112992 0.1561341  0.209287  ]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 25000.0]
Fitted coefficients: [0.09770356 0.44186378 0.26841292 0.19201974]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 391.0]
Fitted coefficients: [0.13501018 0.57437755 0.09867009 0.19194217]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 50000.0]
Fitted coefficients: [0.12060969 0.3837477  0.31474239 0.18090022]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 6250.0]
Fitted coefficients: [0.11484712 0.43390791 0.23662329 0.21462168]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 781.0]
Fitted coefficients: [0.10889434 0.52820325 0.14358343 0.21931898]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 100000.0]
Fitted coefficients: [0.04528808 0.26757657 0.41369043 0.27344492]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 1562.0]
Fitted coefficients: [0.21665006 0.24804653 0.17613662 0.35916679]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 25000.0]
Fitted coefficients: [0.12792782 0.21332121 0.31503591 0.34371506]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 391.0]
Fitted coefficients: [0.22550103 0.28699851 0.11366263 0.37383783]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 50000.0]
Fitted coefficients: [0.10119262 0.24353412 0.30618887 0.34908439]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 6250.0]
Fitted coefficients: [0.15210855 0.24901867 0.23463486 0.36423792]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 781.0]
Fitted coefficients: [0.19411969 0.28658363 0.14282155 0.37647513]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 100000.0]
Fitted coefficients: [0.17707182 0.09845908 0.49002511 0.23444398]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 1562.0]
Fitted coefficients: [0.31298645 0.10406773 0.18081407 0.40213175]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 25000.0]
Fitted coefficients: [0.24034003 0.07945296 0.32241436 0.35779265]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 391.0]
Fitted coefficients: [0.31926472 0.14086013 0.10183324 0.43804191]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 50000.0]
Fitted coefficients: [0.20632068 0.07081565 0.3812727  0.34159096]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 6250.0]
Fitted coefficients: [0.21643875 0.09701661 0.26488929 0.42165535]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[1562.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 781.0]
Fitted coefficients: [0.32307593 0.12558344 0.13647663 0.414864  ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 100000.0]
Fitted coefficients: [2.78984280e-01 4.59876002e-01 2.61139718e-01 1.00000064e-10]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 1562.0]
Fitted coefficients: [0.37264925 0.48082399 0.10869221 0.03783455]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 25000.0]
Fitted coefficients: [0.29345651 0.49321194 0.16929299 0.04403855]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 391.0]
Fitted coefficients: [0.42992647 0.47844346 0.07055442 0.02107565]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 50000.0]
Fitted coefficients: [0.33534386 0.44508018 0.18915798 0.03041798]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 6250.0]
Fitted coefficients: [0.39018755 0.44285366 0.1363569  0.03060189]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 781.0]
Fitted coefficients: [0.34360961 0.5416359  0.07091637 0.04383813]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 100000.0]
Fitted coefficients: [0.39553456 0.12345999 0.34770562 0.13329983]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 1562.0]
Fitted coefficients: [0.48593525 0.13915431 0.13784257 0.23706787]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 25000.0]
Fitted coefficients: [0.39242956 0.10487618 0.25810805 0.24458621]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 391.0]
Fitted coefficients: [0.57907598 0.14486501 0.08823847 0.18782053]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 50000.0]
Fitted coefficients: [0.37446824 0.10673583 0.29239288 0.22640305]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 6250.0]
Fitted coefficients: [0.45798641 0.1206273  0.19559219 0.2257941 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 781.0]
Fitted coefficients: [0.53415315 0.14443724 0.10837702 0.21303259]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 100000.0]
Fitted coefficients: [0.32209994 0.27540358 0.32318203 0.07931445]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 1562.0]
Fitted coefficients: [0.41017985 0.31751746 0.13572405 0.13657863]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 25000.0]
Fitted coefficients: [0.29221514 0.31304731 0.2329929  0.16174465]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 391.0]
Fitted coefficients: [0.42015344 0.32754027 0.10550417 0.14680212]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 50000.0]
Fitted coefficients: [0.32168668 0.28605114 0.24403464 0.14822754]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 6250.0]
Fitted coefficients: [0.38418179 0.30397465 0.16956097 0.14228259]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 781.0]
Fitted coefficients: [0.36395287 0.35008889 0.12914922 0.15680903]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 100000.0]
Fitted coefficients: [0.48839968 0.03854958 0.43456508 0.03848567]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 1562.0]
Fitted coefficients: [0.62985803 0.03419271 0.16071469 0.17523457]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 25000.0]
Fitted coefficients: [0.54635132 0.02385893 0.2585248  0.17126494]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 391.0]
Fitted coefficients: [0.66933791 0.04211695 0.10647125 0.18207389]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 50000.0]
Fitted coefficients: [0.45224183 0.01196141 0.33592701 0.19986975]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 6250.0]
Fitted coefficients: [0.58597273 0.02761737 0.21417764 0.17223227]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 781.0]
Fitted coefficients: [0.67751628 0.03887117 0.14245884 0.1411537 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 100000.0]
Fitted coefficients: [0.30587494 0.32857828 0.31361977 0.05192702]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 1562.0]
Fitted coefficients: [0.38579235 0.37107697 0.12855323 0.11457747]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 25000.0]
Fitted coefficients: [0.28798693 0.36021569 0.22629008 0.1255073 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 391.0]
Fitted coefficients: [0.42539231 0.38466397 0.09145096 0.09849276]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 50000.0]
Fitted coefficients: [0.31401356 0.33777766 0.23759198 0.1106168 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 6250.0]
Fitted coefficients: [0.36993126 0.34523909 0.1743876  0.11044205]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 781.0]
Fitted coefficients: [0.36140406 0.40152544 0.10454793 0.13252257]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.33757896 0.1717859  0.37301428 0.11762085]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 1562.0]
Fitted coefficients: [0.44190198 0.21164777 0.11190999 0.23454026]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 25000.0]
Fitted coefficients: [0.37581412 0.17764376 0.23160422 0.21493791]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 391.0]
Fitted coefficients: [0.47815498 0.22734182 0.09136446 0.20313874]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 50000.0]
Fitted coefficients: [0.38192744 0.17095361 0.25055882 0.19656013]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 6250.0]
Fitted coefficients: [0.47623815 0.17559773 0.17088394 0.17728017]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 781.0]
Fitted coefficients: [0.46011774 0.22172964 0.10151143 0.21664119]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 100000.0]
Fitted coefficients: [0.44827136 0.0867583  0.35137581 0.11359453]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 1562.0]
Fitted coefficients: [0.55950277 0.07720062 0.15244753 0.21084907]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 25000.0]
Fitted coefficients: [0.49934968 0.07282546 0.23579505 0.1920298 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 391.0]
Fitted coefficients: [0.64918307 0.10275306 0.08550395 0.16255993]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 50000.0]
Fitted coefficients: [0.4762568  0.07122561 0.26235958 0.19015801]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 6250.0]
Fitted coefficients: [0.50727167 0.07572748 0.20771967 0.20928119]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[25000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 781.0]
Fitted coefficients: [0.52920089 0.10814249 0.1060707  0.25658592]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 100000.0]
Fitted coefficients: [1.01326709e-10 5.95470635e-01 3.34625421e-01 6.99039439e-02]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 1562.0]
Fitted coefficients: [1.00000262e-10 6.99230652e-01 9.25262559e-02 2.08243092e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 5.89806500e-01 2.25039533e-01 1.85153967e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 391.0]
Fitted coefficients: [3.00663613e-09 7.75257337e-01 3.58527354e-02 1.88889928e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 50000.0]
Fitted coefficients: [1.00000000e-10 5.84679259e-01 2.51394214e-01 1.63926527e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 6250.0]
Fitted coefficients: [1.00000012e-10 6.48763252e-01 1.72376554e-01 1.78860193e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 781.0]
Fitted coefficients: [1.00000095e-10 7.41566814e-01 6.92662872e-02 1.89166899e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 100000.0]
Fitted coefficients: [1.00000000e-10 1.22697670e-01 5.27994653e-01 3.49307677e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 1562.0]
Fitted coefficients: [0.00655263 0.15794854 0.18910721 0.64639162]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 25000.0]
Fitted coefficients: [0.00200958 0.12849484 0.34601499 0.52348058]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 391.0]
Fitted coefficients: [0.00115768 0.19773568 0.09332599 0.70778065]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 50000.0]
Fitted coefficients: [2.24593856e-09 1.13673791e-01 4.11927502e-01 4.74398708e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 6250.0]
Fitted coefficients: [1.05039016e-10 1.45957874e-01 2.74152188e-01 5.79889937e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 781.0]
Fitted coefficients: [1.27172868e-10 1.80834143e-01 1.30124253e-01 6.89041603e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 100000.0]
Fitted coefficients: [1.93932926e-10 3.28935493e-01 4.38408265e-01 2.32656243e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 1562.0]
Fitted coefficients: [1.00000000e-10 4.15342609e-01 1.62498139e-01 4.22159252e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 25000.0]
Fitted coefficients: [3.47662969e-10 3.13347121e-01 3.47816695e-01 3.38836184e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 391.0]
Fitted coefficients: [2.27995621e-09 4.46892873e-01 9.33550332e-02 4.59752095e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 50000.0]
Fitted coefficients: [4.34421448e-10 3.03687896e-01 3.58026246e-01 3.38285857e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 6250.0]
Fitted coefficients: [1.01273571e-10 3.87479958e-01 2.31358909e-01 3.81161133e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 781.0]
Fitted coefficients: [1.04066562e-10 4.48216669e-01 1.13290226e-01 4.38493105e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 100000.0]
Fitted coefficients: [1.00091179e-10 1.00000000e-10 6.63661415e-01 3.36338585e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 1562.0]
Fitted coefficients: [4.22437029e-02 1.00000000e-10 2.44072509e-01 7.13683788e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 25000.0]
Fitted coefficients: [3.33386744e-02 3.49900678e-09 4.57627427e-01 5.09033902e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 391.0]
Fitted coefficients: [5.51971377e-02 1.00479202e-10 1.28361950e-01 8.16440913e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 50000.0]
Fitted coefficients: [2.39620061e-02 1.00000000e-10 4.96072865e-01 4.79965129e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 6250.0]
Fitted coefficients: [2.84044680e-02 1.00000000e-10 3.36148509e-01 6.35447022e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 781.0]
Fitted coefficients: [4.92856935e-02 1.00011479e-10 1.92624614e-01 7.58089692e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 4.35830825e-01 3.66177699e-01 1.97991476e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 1562.0]
Fitted coefficients: [1.00000000e-10 5.37646950e-01 1.20277761e-01 3.42075289e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 25000.0]
Fitted coefficients: [1.00000056e-10 4.30749717e-01 2.44430216e-01 3.24820067e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 391.0]
Fitted coefficients: [4.58881985e-09 5.79907828e-01 6.33046942e-02 3.56787478e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 50000.0]
Fitted coefficients: [1.51896220e-09 4.48433649e-01 2.69247029e-01 2.82319319e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 6250.0]
Fitted coefficients: [1.15415018e-09 4.57675810e-01 2.16458686e-01 3.25865503e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 781.0]
Fitted coefficients: [1.00000000e-10 5.78801898e-01 9.14474869e-02 3.29750615e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 100000.0]
Fitted coefficients: [1.04126980e-10 2.04168288e-01 4.57372936e-01 3.38458776e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 1562.0]
Fitted coefficients: [2.06733643e-09 2.63407996e-01 1.51374767e-01 5.85217237e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 25000.0]
Fitted coefficients: [1.00027953e-10 2.14379964e-01 3.23801554e-01 4.61818481e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 391.0]
Fitted coefficients: [1.00000000e-10 3.19860170e-01 6.79684403e-02 6.12171390e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 50000.0]
Fitted coefficients: [1.34826498e-10 2.18952501e-01 3.19919971e-01 4.61127528e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 6250.0]
Fitted coefficients: [1.00000000e-10 2.44513901e-01 2.41588830e-01 5.13897270e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 781.0]
Fitted coefficients: [1.85953267e-10 2.90804677e-01 9.96519788e-02 6.09543344e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 100000.0]
Fitted coefficients: [1.00011888e-10 7.35652379e-02 5.70419562e-01 3.56015200e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 1562.0]
Fitted coefficients: [0.02398634 0.10560115 0.19412854 0.67628397]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 25000.0]
Fitted coefficients: [0.01189619 0.07475541 0.37644246 0.53690595]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 391.0]
Fitted coefficients: [0.04597115 0.12204159 0.09473423 0.73725303]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 50000.0]
Fitted coefficients: [0.02262855 0.05567404 0.42472787 0.49696954]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 6250.0]
Fitted coefficients: [0.00866505 0.09308877 0.26519687 0.63304931]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[391.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 781.0]
Fitted coefficients: [0.03069545 0.10668105 0.14580336 0.71682014]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 100000.0]
Fitted coefficients: [3.99684122e-01 3.85868038e-01 2.14447840e-01 1.00000000e-10]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 1562.0]
Fitted coefficients: [0.39002036 0.49845406 0.08010613 0.03141945]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 25000.0]
Fitted coefficients: [0.41491709 0.40210855 0.16513791 0.01783646]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 391.0]
Fitted coefficients: [0.48908313 0.46140634 0.0396639  0.00984663]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 50000.0]
Fitted coefficients: [0.40159324 0.42370653 0.17161384 0.0030864 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 6250.0]
Fitted coefficients: [4.50882410e-01 4.41657964e-01 1.07459626e-01 1.00000000e-10]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 781.0]
Fitted coefficients: [0.44196191 0.48414859 0.05393437 0.01995513]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 100000.0]
Fitted coefficients: [0.50565609 0.11965698 0.27363333 0.1010536 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 1562.0]
Fitted coefficients: [0.60903585 0.12234764 0.10039022 0.16822629]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 25000.0]
Fitted coefficients: [0.51314641 0.10389201 0.20171224 0.18124934]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 391.0]
Fitted coefficients: [0.63998699 0.13281292 0.06173236 0.16546774]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 50000.0]
Fitted coefficients: [0.54463955 0.09407072 0.21655813 0.14473161]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 6250.0]
Fitted coefficients: [0.54462974 0.1181056  0.14838807 0.18887659]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 781.0]
Fitted coefficients: [0.6237461  0.12953176 0.0772103  0.16951184]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 100000.0]
Fitted coefficients: [0.36387149 0.26996709 0.31583981 0.05032161]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 1562.0]
Fitted coefficients: [0.47310704 0.27845271 0.12935837 0.11908188]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 25000.0]
Fitted coefficients: [0.40236347 0.24699035 0.22589841 0.12474777]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 391.0]
Fitted coefficients: [0.49564092 0.31573273 0.08291231 0.10571404]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 50000.0]
Fitted coefficients: [0.41831934 0.23745339 0.23242713 0.11180014]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 6250.0]
Fitted coefficients: [0.40818068 0.28461802 0.17155483 0.13564646]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 781.0]
Fitted coefficients: [0.50440119 0.2926266  0.09990254 0.10306966]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 100000.0]
Fitted coefficients: [0.58068509 0.0334731  0.35752239 0.02831942]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 1562.0]
Fitted coefficients: [0.69464159 0.02764646 0.12784446 0.14986749]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 25000.0]
Fitted coefficients: [0.60993222 0.01902088 0.24152105 0.12952585]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 391.0]
Fitted coefficients: [0.80473968 0.0430807  0.08153705 0.07064257]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 50000.0]
Fitted coefficients: [0.6146342  0.0244593  0.23766908 0.12323742]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 6250.0]
Fitted coefficients: [0.66989625 0.02535829 0.17885978 0.12588568]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 781.0]
Fitted coefficients: [0.74050301 0.03133788 0.10217115 0.12598796]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 100000.0]
Fitted coefficients: [0.33657809 0.32467848 0.29987478 0.03886866]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 1562.0]
Fitted coefficients: [0.45465832 0.35727564 0.10210896 0.08595707]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 25000.0]
Fitted coefficients: [0.40537902 0.29879133 0.20474332 0.09108633]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 391.0]
Fitted coefficients: [0.56292777 0.32294151 0.06219636 0.05193436]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 50000.0]
Fitted coefficients: [0.35979693 0.31290288 0.22969177 0.09760841]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 6250.0]
Fitted coefficients: [0.47583263 0.29795441 0.1500239  0.07618906]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 781.0]
Fitted coefficients: [0.46824518 0.36502963 0.08951592 0.07720927]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 100000.0]
Fitted coefficients: [0.47418018 0.1780955  0.24992865 0.09779566]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 1562.0]
Fitted coefficients: [0.56845656 0.16295459 0.11224212 0.15634673]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 25000.0]
Fitted coefficients: [0.44873518 0.18282863 0.18420939 0.18422679]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 391.0]
Fitted coefficients: [0.49792396 0.23387285 0.06449434 0.20370885]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 50000.0]
Fitted coefficients: [0.38528222 0.15638567 0.26580565 0.19252646]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 6250.0]
Fitted coefficients: [0.49905985 0.15751998 0.1632798  0.18014037]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 781.0]
Fitted coefficients: [0.56864705 0.18524966 0.08629558 0.15980772]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 100000.0]
Fitted coefficients: [0.48671702 0.07950121 0.3410067  0.09277507]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 1562.0]
Fitted coefficients: [0.63094607 0.08280604 0.10680933 0.17943856]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 25000.0]
Fitted coefficients: [0.52287736 0.06097845 0.23193447 0.18420972]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 391.0]
Fitted coefficients: [0.68027343 0.10556175 0.05135473 0.16281008]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 50000.0]
Fitted coefficients: [0.49505434 0.07041832 0.23849033 0.19603701]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 6250.0]
Fitted coefficients: [0.57008103 0.06908267 0.17966882 0.18116747]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[50000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 781.0]
Fitted coefficients: [0.66418097 0.086818   0.08145565 0.16754537]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 100000.0]
Fitted coefficients: [1.54815049e-01 5.29714119e-01 3.15470833e-01 2.71411596e-10]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 1562.0]
Fitted coefficients: [0.24954159 0.58977719 0.10590846 0.05477276]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 25000.0]
Fitted coefficients: [0.21043415 0.52635027 0.19989668 0.06331889]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 391.0]
Fitted coefficients: [0.26564242 0.60765722 0.07195579 0.05474457]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 50000.0]
Fitted coefficients: [0.19986441 0.51248314 0.22905754 0.05859492]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 6250.0]
Fitted coefficients: [0.25446564 0.52756938 0.15705436 0.06091063]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 781.0]
Fitted coefficients: [0.26364553 0.59076082 0.09275828 0.05283537]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 100000.0]
Fitted coefficients: [0.24916693 0.13641828 0.44332424 0.17109055]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 1562.0]
Fitted coefficients: [0.37941305 0.13912166 0.18164781 0.29981748]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 25000.0]
Fitted coefficients: [0.27577878 0.13194533 0.29433471 0.29794118]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 391.0]
Fitted coefficients: [0.39521047 0.17996546 0.11815044 0.30667364]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 50000.0]
Fitted coefficients: [0.27906338 0.13265301 0.30367027 0.28461335]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 6250.0]
Fitted coefficients: [0.31556439 0.13741825 0.23311155 0.31390581]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 781.0]
Fitted coefficients: [0.39423421 0.16742109 0.13980722 0.29853749]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 100000.0]
Fitted coefficients: [0.14470784 0.32338866 0.4191725  0.112731  ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 1562.0]
Fitted coefficients: [0.23794916 0.36882851 0.17913483 0.21408751]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 25000.0]
Fitted coefficients: [0.20013253 0.33375788 0.26782719 0.1982824 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 391.0]
Fitted coefficients: [0.30093408 0.38269655 0.1405726  0.17579676]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 50000.0]
Fitted coefficients: [0.20255425 0.29057544 0.32961267 0.17725764]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 6250.0]
Fitted coefficients: [0.23354614 0.32544486 0.2385839  0.20242509]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 781.0]
Fitted coefficients: [0.25776903 0.38599726 0.16031791 0.1959158 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 100000.0]
Fitted coefficients: [0.28394007 0.04104761 0.55984314 0.11516918]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 1562.0]
Fitted coefficients: [0.53571239 0.04744762 0.19785106 0.21898893]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 25000.0]
Fitted coefficients: [0.34529543 0.01162366 0.37013669 0.27294421]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 391.0]
Fitted coefficients: [0.55834556 0.04949089 0.15379541 0.23836814]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 50000.0]
Fitted coefficients: [0.32794601 0.01058386 0.4198182  0.24165194]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 6250.0]
Fitted coefficients: [0.44292925 0.02702983 0.29634918 0.23369174]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 781.0]
Fitted coefficients: [0.52693105 0.04697296 0.17530556 0.25079043]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 100000.0]
Fitted coefficients: [0.17635183 0.35889586 0.37347045 0.09128186]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 1562.0]
Fitted coefficients: [0.2287513  0.44532301 0.16080799 0.1651177 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 25000.0]
Fitted coefficients: [0.17348338 0.37909439 0.27851794 0.16890429]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 391.0]
Fitted coefficients: [0.27613788 0.45403457 0.11331349 0.15651405]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 50000.0]
Fitted coefficients: [0.19650807 0.37243685 0.28965163 0.14140345]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 6250.0]
Fitted coefficients: [0.21646655 0.42663321 0.19554049 0.16135975]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 781.0]
Fitted coefficients: [0.19253284 0.50424301 0.13013648 0.17308767]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 100000.0]
Fitted coefficients: [0.1943251  0.20688279 0.425264   0.1735281 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 1562.0]
Fitted coefficients: [0.32066653 0.21751318 0.17813562 0.28368467]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 25000.0]
Fitted coefficients: [0.22885605 0.18752086 0.30241977 0.28120333]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 391.0]
Fitted coefficients: [0.36790841 0.24100318 0.12213313 0.26895528]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 50000.0]
Fitted coefficients: [0.22094327 0.1800578  0.3358871  0.26311182]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 6250.0]
Fitted coefficients: [0.27828746 0.21959478 0.2213438  0.28077396]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 781.0]
Fitted coefficients: [0.31553576 0.25381155 0.14175984 0.28889285]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 100000.0]
Fitted coefficients: [0.2714459  0.1018565  0.44141579 0.1852818 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 1562.0]
Fitted coefficients: [0.42102218 0.10655752 0.18336255 0.28905775]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 25000.0]
Fitted coefficients: [0.33522966 0.07770961 0.30701284 0.28004789]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 391.0]
Fitted coefficients: [0.45876728 0.12387167 0.12569726 0.2916638 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 50000.0]
Fitted coefficients: [0.32735363 0.07723356 0.33857244 0.25684037]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 6250.0]
Fitted coefficients: [0.3324748  0.10282488 0.2531754  0.31152493]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[6250.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 781.0]
Fitted coefficients: [0.42828376 0.11464812 0.15220847 0.30485965]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.01885512 0.5719395  0.33825824 0.07094714]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 1562.0]
Fitted coefficients: [0.09675935 0.63216467 0.0991084  0.17196758]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 25000.0]
Fitted coefficients: [0.07339507 0.53988728 0.22168722 0.16503042]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 391.0]
Fitted coefficients: [0.09069872 0.6818965  0.04746489 0.17993988]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 50000.0]
Fitted coefficients: [0.06905217 0.55931329 0.22788326 0.14375128]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 6250.0]
Fitted coefficients: [0.06608553 0.63701451 0.15401865 0.1428813 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 781.0]
Fitted coefficients: [0.072937   0.67615212 0.07897762 0.17193326]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 100000.0]
Fitted coefficients: [0.02527691 0.13629811 0.51237232 0.32605266]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 1562.0]
Fitted coefficients: [0.11279435 0.17061266 0.1546046  0.56198839]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 25000.0]
Fitted coefficients: [0.07970615 0.14268601 0.28291686 0.49469098]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 391.0]
Fitted coefficients: [0.18364544 0.1940142  0.08759294 0.53474743]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 50000.0]
Fitted coefficients: [0.06813063 0.11086903 0.3933914  0.42760894]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 6250.0]
Fitted coefficients: [0.10648976 0.13504249 0.24549396 0.5129738 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 781.0]
Fitted coefficients: [0.17589269 0.16534752 0.11492472 0.54383507]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 100000.0]
Fitted coefficients: [1.00000002e-10 3.60909610e-01 4.31505770e-01 2.07584623e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 1562.0]
Fitted coefficients: [0.02220749 0.41611513 0.19771101 0.36396637]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 25000.0]
Fitted coefficients: [0.00405943 0.37745442 0.28765313 0.33083302]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 391.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.02350969 0.44924251 0.13322457 0.39402324]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 50000.0]
Fitted coefficients: [1.00000000e-10 3.67460654e-01 3.24512299e-01 3.08027047e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 6250.0]
Fitted coefficients: [0.00909749 0.39729998 0.24757372 0.34602881]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 781.0]
Fitted coefficients: [0.03029948 0.43812203 0.15369026 0.37788823]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 100000.0]
Fitted coefficients: [0.10965012 0.0106422  0.56271856 0.31698911]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 1562.0]
Fitted coefficients: [2.40164961e-01 1.00003045e-10 2.13273600e-01 5.46561439e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 25000.0]
Fitted coefficients: [1.48944670e-01 1.00000000e-10 3.96393151e-01 4.54662179e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 391.0]
Fitted coefficients: [0.29993886 0.01328649 0.11420943 0.57256522]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 50000.0]
Fitted coefficients: [1.13177556e-01 1.70154458e-09 4.48601053e-01 4.38221393e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 6250.0]
Fitted coefficients: [1.59917449e-01 1.00452086e-10 3.60482856e-01 4.79599695e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 781.0]
Fitted coefficients: [2.08248528e-01 6.21040741e-10 1.98991962e-01 5.92759511e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 4.28012086e-01 4.10985880e-01 1.61002034e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 1562.0]
Fitted coefficients: [0.0202321  0.50989554 0.15261174 0.31726062]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 25000.0]
Fitted coefficients: [0.01226276 0.40262286 0.30546444 0.27964993]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 391.0]
Fitted coefficients: [0.0232032  0.58292615 0.09673492 0.29713573]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 50000.0]
Fitted coefficients: [0.00726821 0.40580833 0.31278785 0.27413562]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 6250.0]
Fitted coefficients: [0.02226348 0.42759664 0.24925376 0.30088612]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 781.0]
Fitted coefficients: [0.02299722 0.54489452 0.12571688 0.30639138]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 100000.0]
Fitted coefficients: [0.00478822 0.20476005 0.48258286 0.30786886]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 1562.0]
Fitted coefficients: [0.03459922 0.27538935 0.1727304  0.51728103]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 25000.0]
Fitted coefficients: [0.06285948 0.18840754 0.31736805 0.43136493]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 391.0]
Fitted coefficients: [0.11599811 0.28605317 0.09748501 0.50046372]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 50000.0]
Fitted coefficients: [0.02782274 0.2162464  0.3358127  0.42011816]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 6250.0]
Fitted coefficients: [0.06178755 0.23292082 0.2342324  0.47105923]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 781.0]
Fitted coefficients: [0.07722808 0.29078354 0.12208922 0.50989916]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 100000.0]
Fitted coefficients: [0.0613017  0.09532191 0.50358576 0.33979063]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 1562.0]
Fitted coefficients: [0.15910384 0.08557827 0.18788255 0.56743535]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 25000.0]
Fitted coefficients: [0.09752475 0.0820532  0.34129921 0.47912284]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 391.0]
Fitted coefficients: [0.20270479 0.13070996 0.09027511 0.57631014]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 50000.0]
Fitted coefficients: [0.08351037 0.07145999 0.39298419 0.45204546]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 6250.0]
Fitted coefficients: [0.15550098 0.07609626 0.25172825 0.51667451]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVA2'], Conc=[781.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 781.0]
Fitted coefficients: [0.14538378 0.11025468 0.14251645 0.60184509]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 100000.0]
Fitted coefficients: [0.31495164 0.26287518 0.37107799 0.05109519]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 25000.0]
Fitted coefficients: [0.33803885 0.31301868 0.25429862 0.09464385]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 3125.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.37489617 0.34531164 0.12925264 0.15053955]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 391.0]
Fitted coefficients: [0.35900503 0.41439391 0.05499383 0.17160724]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 50000.0]
Fitted coefficients: [0.34636726 0.30851188 0.26138473 0.08373614]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 6250.0]
Fitted coefficients: [0.39222244 0.32937527 0.17131482 0.10708747]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 781.0]
Fitted coefficients: [0.37192366 0.41046859 0.08178379 0.13582396]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 100000.0]
Fitted coefficients: [0.36544024 0.05110673 0.43698101 0.14647202]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 25000.0]
Fitted coefficients: [0.42592477 0.02877009 0.33078548 0.21451967]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 3125.0]
Fitted coefficients: [0.49238379 0.04624711 0.1825505  0.2788186 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 391.0]
Fitted coefficients: [0.5708387  0.07226165 0.07440284 0.28249681]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 50000.0]
Fitted coefficients: [0.42482244 0.02512146 0.36338413 0.18667197]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 6250.0]
Fitted coefficients: [0.47694075 0.02291133 0.26855721 0.2315907 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 781.0]
Fitted coefficients: [0.51083945 0.05934079 0.13249586 0.2973239 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 100000.0]
Fitted coefficients: [0.30750315 0.1729947  0.42696024 0.09254191]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 25000.0]
Fitted coefficients: [0.39079877 0.14808651 0.3030141  0.15810062]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 3125.0]
Fitted coefficients: [0.36435225 0.16795757 0.2218491  0.24584107]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 391.0]
Fitted coefficients: [0.43733902 0.23277899 0.09124361 0.23863838]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 50000.0]
Fitted coefficients: [0.32140221 0.16301487 0.36850604 0.14707688]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 6250.0]
Fitted coefficients: [0.38971685 0.17304904 0.24904782 0.1881863 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 781.0]
Fitted coefficients: [0.40452561 0.2287442  0.14091605 0.22581414]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 100000.0]
Fitted coefficients: [3.52898517e-01 1.00103577e-10 5.41455415e-01 1.05646068e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 25000.0]
Fitted coefficients: [4.48492298e-01 1.11616017e-09 3.77158912e-01 1.74348791e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 3125.0]
Fitted coefficients: [5.22445054e-01 1.00000000e-10 2.18727543e-01 2.58827403e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 391.0]
Fitted coefficients: [6.34174178e-01 1.00001440e-10 7.50484590e-02 2.90777363e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 50000.0]
Fitted coefficients: [4.83669110e-01 1.00000000e-10 3.57692657e-01 1.58638234e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 6250.0]
Fitted coefficients: [4.97232089e-01 1.00000000e-10 2.71138713e-01 2.31629198e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 781.0]
Fitted coefficients: [5.53010625e-01 1.00937826e-10 1.58803408e-01 2.88185966e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 100000.0]
Fitted coefficients: [0.26486951 0.22840584 0.40881753 0.09790713]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 25000.0]
Fitted coefficients: [0.36822518 0.18838258 0.30836975 0.13502249]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 3125.0]
Fitted coefficients: [0.43437967 0.20148178 0.17195915 0.19217939]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 391.0]
Fitted coefficients: [0.41776595 0.29370822 0.0817465  0.20677934]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 50000.0]
Fitted coefficients: [0.32731026 0.20779942 0.33625993 0.1286304 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 6250.0]
Fitted coefficients: [0.34847267 0.2641188  0.21557563 0.1718329 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 781.0]
Fitted coefficients: [0.45446862 0.24852968 0.11190852 0.18509318]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 100000.0]
Fitted coefficients: [0.32183195 0.08421235 0.45463267 0.13932303]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 25000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.39590348 0.07229243 0.3219847  0.20981939]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 3125.0]
Fitted coefficients: [0.42595188 0.10496278 0.18798684 0.2810985 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 391.0]
Fitted coefficients: [0.47377145 0.13579277 0.09097534 0.29946044]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 50000.0]
Fitted coefficients: [0.34487649 0.07812646 0.38269938 0.19429767]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 6250.0]
Fitted coefficients: [0.48974707 0.08221159 0.22256696 0.20547438]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 781.0]
Fitted coefficients: [0.48596211 0.12662002 0.12006109 0.26735678]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 100000.0]
Fitted coefficients: [0.33161811 0.0121414  0.52694921 0.12929128]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 25000.0]
Fitted coefficients: [0.45124765 0.00770922 0.31821243 0.22283069]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 3125.0]
Fitted coefficients: [0.50522815 0.00915441 0.18355334 0.30206409]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 391.0]
Fitted coefficients: [0.60485751 0.03960056 0.0688864  0.28665554]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 50000.0]
Fitted coefficients: [0.42437974 0.00588711 0.37254964 0.19718351]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 6250.0]
Fitted coefficients: [0.5085915  0.00761305 0.22942329 0.25437216]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[100000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 781.0]
Fitted coefficients: [0.53507041 0.02618719 0.13545875 0.30328365]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 100000.0]
Fitted coefficients: [0.0233341  0.43128576 0.4908903  0.05448985]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 25000.0]
Fitted coefficients: [0.11968016 0.46696878 0.3086169  0.10473417]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 3125.0]
Fitted coefficients: [0.11069817 0.45106592 0.21705177 0.22118415]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 391.0]
Fitted coefficients: [0.09246325 0.60897538 0.08099028 0.21757109]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 50000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.05445334 0.42599297 0.40316076 0.11639293]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 6250.0]
Fitted coefficients: [0.11747369 0.48553194 0.25274238 0.14425199]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 781.0]
Fitted coefficients: [0.12963267 0.56014269 0.14146853 0.16875611]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 100000.0]
Fitted coefficients: [0.02588402 0.07919834 0.70179853 0.19311911]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 25000.0]
Fitted coefficients: [0.10631185 0.07587721 0.49303531 0.32477563]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 3125.0]
Fitted coefficients: [0.13906516 0.07536766 0.32718988 0.4583773 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 391.0]
Fitted coefficients: [0.24916615 0.15494112 0.1360538  0.45983893]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 50000.0]
Fitted coefficients: [0.07691597 0.05173235 0.60392504 0.26742664]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 6250.0]
Fitted coefficients: [0.16699031 0.06319138 0.41056438 0.35925393]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 781.0]
Fitted coefficients: [0.17769113 0.09586458 0.24357809 0.4828662 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 100000.0]
Fitted coefficients: [1.00016306e-10 2.30863219e-01 6.23102664e-01 1.46034117e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 25000.0]
Fitted coefficients: [0.05947286 0.20837377 0.50697997 0.22517341]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 3125.0]
Fitted coefficients: [0.10686087 0.25631491 0.29655447 0.34026974]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 391.0]
Fitted coefficients: [0.06642171 0.38379387 0.15908928 0.39069515]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 50000.0]
Fitted coefficients: [0.02310665 0.23302849 0.53634495 0.20751991]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 6250.0]
Fitted coefficients: [0.06335049 0.27858914 0.36666782 0.29139255]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 781.0]
Fitted coefficients: [0.07331715 0.33990839 0.2228468  0.36392766]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [1.36332902e-01 1.00000000e-10 6.99297522e-01 1.64369576e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 25000.0]
Fitted coefficients: [1.46091340e-01 1.00000000e-10 6.06944071e-01 2.46964589e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 3125.0]
Fitted coefficients: [2.09979998e-01 1.00000020e-10 3.53292482e-01 4.36727520e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 391.0]
Fitted coefficients: [0.3500605  0.02604334 0.16334211 0.46055404]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 50000.0]
Fitted coefficients: [1.26881261e-01 1.00000000e-10 6.26257862e-01 2.46860877e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 6250.0]
Fitted coefficients: [2.20574564e-01 1.00000037e-10 4.52176266e-01 3.27249170e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 781.0]
Fitted coefficients: [2.45930306e-01 1.00000074e-10 2.43831912e-01 5.10237782e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 2.89339497e-01 5.93553556e-01 1.17106947e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 25000.0]
Fitted coefficients: [0.05186319 0.30402176 0.43145726 0.21265779]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 3125.0]
Fitted coefficients: [0.08844564 0.34881591 0.2654615  0.29727695]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 391.0]
Fitted coefficients: [0.09100371 0.43076728 0.13849236 0.33973665]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 50000.0]
Fitted coefficients: [0.03218614 0.30818396 0.47144469 0.18818522]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 6250.0]
Fitted coefficients: [0.08790904 0.32227681 0.33650151 0.25331264]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 781.0]
Fitted coefficients: [0.09890001 0.42867143 0.17963289 0.29279567]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 100000.0]
Fitted coefficients: [0.01690645 0.14021418 0.64989697 0.1929824 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 25000.0]
Fitted coefficients: [0.06396552 0.15060558 0.47455441 0.3108745 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 3125.0]
Fitted coefficients: [0.10964402 0.14078304 0.31726098 0.43231196]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 391.0]
Fitted coefficients: [0.18172492 0.2385957  0.14212771 0.43755167]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 50000.0]
Fitted coefficients: [0.0366829  0.1361154  0.54887818 0.27832352]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 6250.0]
Fitted coefficients: [0.15497481 0.10853962 0.39915274 0.33733283]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 781.0]
Fitted coefficients: [0.11832854 0.20773982 0.220502   0.45342964]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 100000.0]
Fitted coefficients: [0.06478065 0.04623576 0.67706058 0.211923  ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 25000.0]
Fitted coefficients: [0.11638905 0.04318046 0.50198562 0.33844486]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 3125.0]
Fitted coefficients: [0.15292832 0.03070097 0.33850544 0.47786527]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 391.0]
Fitted coefficients: [0.2111588  0.09115638 0.16104837 0.53663644]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 50000.0]
Fitted coefficients: [0.09766485 0.01039077 0.63691491 0.25502947]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 6250.0]
Fitted coefficients: [0.18653885 0.02344765 0.41514736 0.37486614]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[1562.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 781.0]
Fitted coefficients: [0.22696073 0.08510041 0.20745231 0.48048656]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 100000.0]
Fitted coefficients: [0.21302768 0.33184978 0.43075303 0.02436951]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 25000.0]
Fitted coefficients: [0.27293356 0.36857863 0.27858755 0.07990027]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 3125.0]
Fitted coefficients: [0.31567404 0.38218644 0.16767597 0.13446354]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 391.0]
Fitted coefficients: [0.32149381 0.47985749 0.07590051 0.12274819]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 50000.0]
Fitted coefficients: [0.24150334 0.35434997 0.33411983 0.07002687]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 6250.0]
Fitted coefficients: [0.29554977 0.37981687 0.2083904  0.11624296]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 781.0]
Fitted coefficients: [0.32849443 0.44365735 0.124685   0.10316322]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 100000.0]
Fitted coefficients: [0.2858158  0.06806209 0.51534983 0.13077228]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 25000.0]
Fitted coefficients: [0.32636963 0.06643082 0.39605405 0.2111455 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 3125.0]
Fitted coefficients: [0.34676962 0.06562277 0.24615352 0.34145408]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 391.0]
Fitted coefficients: [0.46409943 0.11368679 0.12004248 0.3021713 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 50000.0]
Fitted coefficients: [0.26302793 0.04455734 0.48396673 0.208448  ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 6250.0]
Fitted coefficients: [0.34601405 0.05991244 0.32073082 0.27334269]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 781.0]
Fitted coefficients: [0.39877938 0.09859985 0.17528675 0.32733403]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 100000.0]
Fitted coefficients: [0.17777462 0.16383484 0.56884056 0.08954998]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 25000.0]
Fitted coefficients: [0.21424454 0.18030998 0.41935207 0.18609342]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 3125.0]
Fitted coefficients: [0.34186389 0.2375936  0.20393831 0.2166042 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 391.0]
Fitted coefficients: [0.40389292 0.2541789  0.11948765 0.22244054]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 50000.0]
Fitted coefficients: [0.20147133 0.20736997 0.42625046 0.16490824]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 6250.0]
Fitted coefficients: [0.29880921 0.1684864  0.3280574  0.20464699]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 781.0]
Fitted coefficients: [0.3497961  0.26369189 0.16292514 0.22358688]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 100000.0]
Fitted coefficients: [0.32163953 0.01271991 0.55683454 0.10880603]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 25000.0]
Fitted coefficients: [3.39065653e-01 1.00000000e-10 4.67071081e-01 1.93863266e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 3125.0]
Fitted coefficients: [4.87035663e-01 1.00000000e-10 2.41700757e-01 2.71263579e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 391.0]
Fitted coefficients: [0.58812989 0.03827948 0.11575869 0.25783193]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 50000.0]
Fitted coefficients: [3.35440372e-01 1.00152872e-10 5.10171519e-01 1.54388109e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 6250.0]
Fitted coefficients: [4.28429309e-01 1.00054546e-10 3.44889726e-01 2.26680971e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 781.0]
Fitted coefficients: [0.51873465 0.0170982  0.18192895 0.28223819]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 100000.0]
Fitted coefficients: [0.17469885 0.2556241  0.4842004  0.08547665]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 25000.0]
Fitted coefficients: [0.22205632 0.26103211 0.36811646 0.14879511]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 3125.0]
Fitted coefficients: [0.26548289 0.30449997 0.21001519 0.22000195]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 391.0]
Fitted coefficients: [0.32224152 0.36698979 0.10184061 0.20892807]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 50000.0]
Fitted coefficients: [0.23975081 0.24882093 0.38312413 0.12830414]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 6250.0]
Fitted coefficients: [0.31529972 0.25050106 0.27754652 0.15665271]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 781.0]
Fitted coefficients: [0.36939825 0.30164487 0.14597433 0.18298256]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 100000.0]
Fitted coefficients: [0.22106383 0.13845606 0.49411153 0.14636857]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 25000.0]
Fitted coefficients: [0.30168184 0.11246729 0.37858793 0.20726294]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 3125.0]
Fitted coefficients: [0.32358045 0.13844584 0.23285517 0.30511854]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 391.0]
Fitted coefficients: [0.446002   0.17295011 0.11836945 0.26267843]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 50000.0]
Fitted coefficients: [0.26464645 0.12684933 0.40628296 0.20222126]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 6250.0]
Fitted coefficients: [0.31151002 0.15057148 0.28082534 0.25709316]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 781.0]
Fitted coefficients: [0.37339863 0.16910404 0.16360661 0.29389072]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 100000.0]
Fitted coefficients: [0.24970392 0.04804501 0.55897369 0.14327738]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 25000.0]
Fitted coefficients: [0.3313107  0.03935253 0.39489185 0.23444492]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 3125.0]
Fitted coefficients: [0.37357626 0.04681077 0.24804649 0.33156647]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 391.0]
Fitted coefficients: [0.50047841 0.07721576 0.12086848 0.30143734]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 50000.0]
Fitted coefficients: [0.28752219 0.0303138  0.46513984 0.21702417]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 6250.0]
Fitted coefficients: [0.38700288 0.03096427 0.32219847 0.25983438]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[25000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 781.0]
Fitted coefficients: [0.44165161 0.0778846  0.15826682 0.32219696]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 100000.0]
Fitted coefficients: [1.00002184e-10 4.42705906e-01 4.54991794e-01 1.02302301e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 4.62086208e-01 3.60086172e-01 1.77827620e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 3125.0]
Fitted coefficients: [0.01909047 0.54434594 0.19611476 0.24044883]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 391.0]
Fitted coefficients: [1.00000000e-10 6.28370348e-01 6.94176700e-02 3.02211982e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 50000.0]
Fitted coefficients: [1.02908463e-10 4.14007541e-01 4.09232180e-01 1.76760280e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 6250.0]
Fitted coefficients: [0.0352183  0.45334718 0.27878964 0.23264489]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 781.0]
Fitted coefficients: [1.00000000e-10 5.96034610e-01 1.27017553e-01 2.76947836e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 100000.0]
Fitted coefficients: [1.00000000e-10 4.70504359e-02 6.79815133e-01 2.73134431e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 25000.0]
Fitted coefficients: [0.00118232 0.06568796 0.53256148 0.40056825]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 3125.0]
Fitted coefficients: [1.00009918e-10 5.19775771e-02 3.44971963e-01 6.03050460e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 391.0]
Fitted coefficients: [0.00936154 0.16563565 0.14389836 0.68110444]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 50000.0]
Fitted coefficients: [1.00139384e-10 5.88236320e-02 5.70160202e-01 3.71016166e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 6250.0]
Fitted coefficients: [0.01659108 0.060889   0.42682648 0.49569344]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 781.0]
Fitted coefficients: [1.00000000e-10 1.02357713e-01 2.22096614e-01 6.75545673e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 100000.0]
Fitted coefficients: [1.04547158e-10 1.73799552e-01 6.32034338e-01 1.94166111e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 25000.0]
Fitted coefficients: [1.00305810e-10 2.12423119e-01 4.74658524e-01 3.12918357e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 3125.0]
Fitted coefficients: [1.00567515e-10 2.90228115e-01 2.51655484e-01 4.58116401e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 391.0]
Fitted coefficients: [1.00215383e-10 3.16152067e-01 1.07605666e-01 5.76242267e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 50000.0]
Fitted coefficients: [1.00000000e-10 1.95408120e-01 4.99995495e-01 3.04596385e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 6250.0]
Fitted coefficients: [1.00299626e-10 2.24961298e-01 3.87765019e-01 3.87273684e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 781.0]
Fitted coefficients: [1.00000000e-10 3.03260175e-01 2.00766820e-01 4.95973004e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 100000.0]
Fitted coefficients: [1.01362581e-10 1.02125082e-10 7.59619719e-01 2.40380280e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 25000.0]
Fitted coefficients: [4.97436582e-03 1.02652120e-10 6.33501708e-01 3.61523926e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 3125.0]
Fitted coefficients: [1.02963019e-10 1.00000000e-10 3.83689031e-01 6.16310966e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 391.0]
Fitted coefficients: [6.44179032e-02 1.00000000e-10 1.60258577e-01 7.75323520e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 50000.0]
Fitted coefficients: [1.00000000e-10 1.01980220e-10 6.79158675e-01 3.20841325e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 6250.0]
Fitted coefficients: [3.87263186e-02 1.15250998e-10 5.01476818e-01 4.59796863e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 781.0]
Fitted coefficients: [1.00542760e-10 1.00000000e-10 2.63901348e-01 7.36098652e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 2.39519001e-01 5.83055291e-01 1.77425708e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 2.65621803e-01 4.20023230e-01 3.14354967e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 3125.0]
Fitted coefficients: [1.00462106e-10 3.38419343e-01 2.45688083e-01 4.15892574e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 391.0]
Fitted coefficients: [1.00000000e-10 4.45854065e-01 1.05093512e-01 4.49052424e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 50000.0]
Fitted coefficients: [1.04342888e-10 2.82534317e-01 4.48651937e-01 2.68813746e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 6250.0]
Fitted coefficients: [5.07250811e-10 2.75555739e-01 3.72817484e-01 3.51626776e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 781.0]
Fitted coefficients: [1.75393647e-09 3.92538349e-01 1.72319440e-01 4.35142210e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 100000.0]
Fitted coefficients: [1.00000000e-10 1.14611277e-01 6.33279555e-01 2.52109167e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 25000.0]
Fitted coefficients: [3.53554620e-09 1.00128699e-01 5.28087716e-01 3.71783585e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 3125.0]
Fitted coefficients: [1.00000000e-10 1.53498034e-01 2.79740141e-01 5.66761826e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 391.0]
Fitted coefficients: [1.22907405e-09 2.04520310e-01 1.23013939e-01 6.72465751e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 50000.0]
Fitted coefficients: [1.00717664e-10 9.66815813e-02 5.59839090e-01 3.43479329e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 6250.0]
Fitted coefficients: [1.00000000e-10 1.39380412e-01 3.84878770e-01 4.75740818e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 781.0]
Fitted coefficients: [1.00000000e-10 1.75033715e-01 2.01720083e-01 6.23246201e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 100000.0]
Fitted coefficients: [1.03016811e-10 2.06358100e-02 6.85710421e-01 2.93653769e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 25000.0]
Fitted coefficients: [0.01218283 0.01977884 0.57904395 0.38899438]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 3125.0]
Fitted coefficients: [1.00000025e-10 2.96181356e-02 3.43326247e-01 6.27055617e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 391.0]
Fitted coefficients: [0.06737554 0.09282953 0.14079492 0.69900002]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 50000.0]
Fitted coefficients: [1.00000000e-10 2.84659265e-02 5.92398099e-01 3.79135974e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 6250.0]
Fitted coefficients: [0.04609471 0.00632169 0.4284168  0.51916681]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[391.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 781.0]
Fitted coefficients: [1.00000000e-10 7.21619009e-02 2.06877925e-01 7.20960174e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 100000.0]
Fitted coefficients: [3.15998681e-01 3.31423390e-01 3.52521598e-01 5.63305726e-05]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 25000.0]
Fitted coefficients: [0.27643175 0.35288669 0.28844438 0.08223719]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 3125.0]
Fitted coefficients: [0.37253387 0.40972517 0.12945959 0.08828137]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 391.0]
Fitted coefficients: [0.42146766 0.41802299 0.05757168 0.10293768]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 50000.0]
Fitted coefficients: [0.29829882 0.3515486  0.29508327 0.05506931]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 6250.0]
Fitted coefficients: [0.32275822 0.37390499 0.20363778 0.09969901]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 781.0]
Fitted coefficients: [0.38928602 0.41853702 0.09354339 0.09863357]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 100000.0]
Fitted coefficients: [0.32730216 0.06017453 0.49666132 0.11586199]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 25000.0]
Fitted coefficients: [0.34729836 0.05053919 0.38033871 0.22182374]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 3125.0]
Fitted coefficients: [0.42225271 0.08747305 0.1895586  0.30071564]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 391.0]
Fitted coefficients: [0.49834253 0.11007879 0.083812   0.30776668]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 50000.0]
Fitted coefficients: [0.3682202  0.0512578  0.40278307 0.17773893]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 6250.0]
Fitted coefficients: [0.44078056 0.05598393 0.2681171  0.23511841]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 781.0]
Fitted coefficients: [0.5147328  0.10141775 0.12376076 0.26008868]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 100000.0]
Fitted coefficients: [0.27675959 0.20131771 0.4454     0.07652271]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 25000.0]
Fitted coefficients: [0.29688804 0.19160539 0.36200603 0.14950054]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 3125.0]
Fitted coefficients: [0.33983345 0.2272917  0.20650125 0.22637361]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 391.0]
Fitted coefficients: [0.45425597 0.25953187 0.07972617 0.206486  ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 50000.0]
Fitted coefficients: [0.29779532 0.20079088 0.36645109 0.13496271]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 6250.0]
Fitted coefficients: [0.35480209 0.1765024  0.2795208  0.1891747 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 781.0]
Fitted coefficients: [0.4393375  0.25080396 0.12335881 0.18649973]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 100000.0]
Fitted coefficients: [0.39311977 0.00576675 0.51016507 0.09094841]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 25000.0]
Fitted coefficients: [5.01900257e-01 1.00000000e-10 3.28365984e-01 1.69733759e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 3125.0]
Fitted coefficients: [5.69683458e-01 1.00000003e-10 2.05756137e-01 2.24560404e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 391.0]
Fitted coefficients: [0.65507169 0.03080797 0.07400462 0.24011572]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 50000.0]
Fitted coefficients: [4.46990462e-01 1.00000000e-10 4.00565306e-01 1.52444232e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 6250.0]
Fitted coefficients: [5.09240777e-01 1.00000000e-10 2.80860389e-01 2.09898834e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 781.0]
Fitted coefficients: [0.65285376 0.01961896 0.12335304 0.20417423]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 100000.0]
Fitted coefficients: [0.25029059 0.22984662 0.44568044 0.07418235]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 25000.0]
Fitted coefficients: [0.30455713 0.20572675 0.35688556 0.13283055]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 3125.0]
Fitted coefficients: [0.36991559 0.25819525 0.18199942 0.18988975]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 391.0]
Fitted coefficients: [0.41936626 0.3234588  0.0783119  0.17886303]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 50000.0]
Fitted coefficients: [0.27677104 0.22686087 0.37720044 0.11916766]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 6250.0]
Fitted coefficients: [0.30492027 0.26127348 0.25638034 0.17742592]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 781.0]
Fitted coefficients: [0.39790908 0.30438768 0.11815833 0.17954491]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 100000.0]
Fitted coefficients: [0.25859149 0.12331863 0.4844624  0.13362748]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 25000.0]
Fitted coefficients: [0.38731973 0.11793052 0.3164482  0.17830156]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 3125.0]
Fitted coefficients: [0.45747402 0.1237541  0.17901068 0.2397612 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 391.0]
Fitted coefficients: [0.51320962 0.17726    0.07512184 0.23440854]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 50000.0]
Fitted coefficients: [0.33514984 0.11582573 0.37210537 0.17691906]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 6250.0]
Fitted coefficients: [0.42596236 0.11420176 0.23947147 0.2203644 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 781.0]
Fitted coefficients: [0.51146088 0.14809955 0.11748245 0.22295712]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 100000.0]
Fitted coefficients: [0.36189618 0.04393459 0.47859264 0.11557659]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 25000.0]
Fitted coefficients: [0.49849522 0.04041793 0.28920508 0.17188177]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 3125.0]
Fitted coefficients: [0.4730052  0.03745054 0.20775289 0.28179136]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 391.0]
Fitted coefficients: [0.56353334 0.07493391 0.08072666 0.2808061 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 50000.0]
Fitted coefficients: [0.37254738 0.02784989 0.40774857 0.19185416]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 6250.0]
Fitted coefficients: [0.47948777 0.04109953 0.23463517 0.24477753]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[50000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 781.0]
Fitted coefficients: [0.58247662 0.07275345 0.09942797 0.24534196]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 100000.0]
Fitted coefficients: [0.13284952 0.42111298 0.43186724 0.01417026]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 25000.0]
Fitted coefficients: [0.15531768 0.44559046 0.30993899 0.08915287]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 3125.0]
Fitted coefficients: [0.19932414 0.4250925  0.20043104 0.17515233]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 391.0]
Fitted coefficients: [0.22335034 0.49729574 0.10882708 0.17052684]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 50000.0]
Fitted coefficients: [0.13180978 0.38987019 0.39038906 0.08793097]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 6250.0]
Fitted coefficients: [0.19212223 0.42518267 0.25323178 0.12946332]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 781.0]
Fitted coefficients: [0.25667818 0.4557964  0.15106115 0.13646429]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 100000.0]
Fitted coefficients: [0.12022481 0.08049164 0.62660834 0.17267521]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 25000.0]
Fitted coefficients: [0.16745145 0.06830719 0.49647201 0.26776935]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 3125.0]
Fitted coefficients: [0.26231621 0.10374459 0.2682369  0.3657023 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 391.0]
Fitted coefficients: [0.33838831 0.14744979 0.16672543 0.34743647]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 50000.0]
Fitted coefficients: [0.14907835 0.0562813  0.55747477 0.23716558]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 6250.0]
Fitted coefficients: [0.22665816 0.07590996 0.37269018 0.3247417 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 781.0]
Fitted coefficients: [0.28344176 0.1227073  0.21563264 0.37821829]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 100000.0]
Fitted coefficients: [0.05803347 0.24657905 0.56847332 0.12691416]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 25000.0]
Fitted coefficients: [0.09940746 0.20258799 0.48805134 0.2099532 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 3125.0]
Fitted coefficients: [0.17088797 0.23424967 0.304693   0.29016937]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 391.0]
Fitted coefficients: [0.21379167 0.32856182 0.15700686 0.30063965]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 50000.0]
Fitted coefficients: [0.10450258 0.20718471 0.50181212 0.18650059]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 6250.0]
Fitted coefficients: [0.19699566 0.22035486 0.34838706 0.23426242]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 781.0]
Fitted coefficients: [0.18992382 0.31322104 0.21685994 0.27999521]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 100000.0]
Fitted coefficients: [0.1707449  0.00507033 0.68957367 0.1346111 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 25000.0]
Fitted coefficients: [1.85717405e-01 1.00000007e-10 5.67634961e-01 2.46647634e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 3125.0]
Fitted coefficients: [2.88807757e-01 1.00000024e-10 3.44605865e-01 3.66586378e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 391.0]
Fitted coefficients: [0.4151342  0.03747915 0.17538053 0.37200613]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 50000.0]
Fitted coefficients: [1.89259989e-01 1.00000030e-10 5.92805692e-01 2.17934319e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 6250.0]
Fitted coefficients: [3.01571953e-01 1.00196137e-10 4.08500212e-01 2.89927835e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 781.0]
Fitted coefficients: [0.37347933 0.01696009 0.23959298 0.36996761]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 100000.0]
Fitted coefficients: [0.08412949 0.22716611 0.60696519 0.08173921]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 25000.0]
Fitted coefficients: [0.1016549  0.2648547  0.44643269 0.18705772]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 3125.0]
Fitted coefficients: [0.16514216 0.37278753 0.23254298 0.22952733]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 391.0]
Fitted coefficients: [0.20858698 0.39727114 0.1414889  0.25265298]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 50000.0]
Fitted coefficients: [0.11542523 0.26988845 0.45624326 0.15844305]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 6250.0]
Fitted coefficients: [0.16062604 0.33684107 0.29840828 0.20412462]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 781.0]
Fitted coefficients: [0.19765881 0.37661512 0.18796016 0.23776591]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 100000.0]
Fitted coefficients: [0.1077856  0.12712962 0.62868262 0.13640216]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 25000.0]
Fitted coefficients: [0.16909808 0.12310226 0.45244501 0.25535465]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 3125.0]
Fitted coefficients: [0.18527331 0.13989531 0.30338686 0.37144451]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 391.0]
Fitted coefficients: [0.25438553 0.1986513  0.16356507 0.38339809]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 50000.0]
Fitted coefficients: [0.13491364 0.1105477  0.52957008 0.22496858]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 6250.0]
Fitted coefficients: [0.23847808 0.1547413  0.32086034 0.28592028]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 781.0]
Fitted coefficients: [0.23008733 0.1928787  0.21646815 0.36056583]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 100000.0]
Fitted coefficients: [0.10981363 0.04426255 0.6665596  0.17936422]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 25000.0]
Fitted coefficients: [0.18421466 0.03494841 0.48879318 0.29204375]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 3125.0]
Fitted coefficients: [0.25342837 0.0595298  0.28887719 0.39816463]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 391.0]
Fitted coefficients: [0.33969335 0.09616245 0.16770631 0.39643788]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 50000.0]
Fitted coefficients: [0.1780941  0.03719813 0.53613702 0.24857076]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 6250.0]
Fitted coefficients: [0.21677842 0.03763085 0.38700906 0.35858167]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[6250.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 781.0]
Fitted coefficients: [0.36544806 0.08545675 0.2128883  0.33620689]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 100000.0]
Fitted coefficients: [1.00027794e-10 3.83033496e-01 5.27942517e-01 8.90239867e-02]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 25000.0]
Fitted coefficients: [0.03265576 0.39309347 0.38476121 0.18948955]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 3125.0]
Fitted coefficients: [0.07059543 0.49425094 0.20356383 0.2315898 ]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 391.0]
Fitted coefficients: [0.06859762 0.55662998 0.07056598 0.30420642]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 50000.0]
Fitted coefficients: [0.01529801 0.44457719 0.37636185 0.16376295]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 6250.0]
Fitted coefficients: [0.08699133 0.41967924 0.27878872 0.21454071]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 781.0]
Fitted coefficients: [0.08392315 0.54066485 0.136782   0.23863001]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 100000.0]
Fitted coefficients: [1.00000000e-10 6.92260859e-02 6.58920844e-01 2.71853070e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 25000.0]
Fitted coefficients: [0.05575469 0.05219523 0.52772326 0.36432682]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 3125.0]
Fitted coefficients: [0.07231074 0.08810358 0.28026336 0.55932232]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 391.0]
Fitted coefficients: [0.15603115 0.1531629  0.1317845  0.55902144]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 50000.0]
Fitted coefficients: [0.02517327 0.06708448 0.55439688 0.35334537]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 6250.0]
Fitted coefficients: [0.08945437 0.06065904 0.39806763 0.45181896]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 781.0]
Fitted coefficients: [0.09840378 0.12420861 0.20300596 0.57438165]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 1.88163599e-01 6.36296255e-01 1.75540146e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 2.32803936e-01 4.82921912e-01 2.84274152e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 3125.0]
Fitted coefficients: [1.00000436e-10 2.74733797e-01 3.07093789e-01 4.18172415e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 391.0]
Fitted coefficients: [0.01882512 0.34662708 0.14318068 0.49136712]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 50000.0]
Fitted coefficients: [1.00000000e-10 2.03758913e-01 5.25611324e-01 2.70629763e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 6250.0]
Fitted coefficients: [0.03126603 0.27512802 0.33379647 0.35980947]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 781.0]
Fitted coefficients: [1.00016082e-10 3.31669774e-01 2.18589599e-01 4.49740626e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 100000.0]
Fitted coefficients: [2.17814210e-02 1.00000000e-10 7.61250177e-01 2.16968402e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 25000.0]
Fitted coefficients: [9.29482086e-02 1.00000000e-10 5.51666535e-01 3.55385257e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 3125.0]
Fitted coefficients: [1.02506975e-01 1.00000000e-10 3.53843251e-01 5.43649774e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 391.0]
Fitted coefficients: [0.21952987 0.00553784 0.15614147 0.61879083]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 50000.0]
Fitted coefficients: [5.51590050e-02 1.00863231e-10 6.22680167e-01 3.22160828e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 6250.0]
Fitted coefficients: [1.25719248e-01 1.09533249e-10 4.49172001e-01 4.25108751e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 781.0]
Fitted coefficients: [1.40298433e-01 1.00003878e-10 2.35577571e-01 6.24123996e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 2.93932927e-01 5.46899173e-01 1.59167901e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 25000.0]
Fitted coefficients: [0.00466835 0.2665169  0.45687982 0.27193493]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 3125.0]
Fitted coefficients: [0.01226984 0.32037832 0.28556384 0.38178799]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 391.0]
Fitted coefficients: [0.01316355 0.4564049  0.11867428 0.41175728]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 50000.0]
Fitted coefficients: [1.00031388e-10 2.35558374e-01 5.05683210e-01 2.58758416e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 6250.0]
Fitted coefficients: [0.01451702 0.32104076 0.34284868 0.32159354]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 781.0]
Fitted coefficients: [0.02790778 0.42090564 0.16895621 0.38223037]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 100000.0]
Fitted coefficients: [1.40705801e-09 1.23616794e-01 6.46623389e-01 2.29759817e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 25000.0]
Fitted coefficients: [0.01079527 0.12950706 0.51230198 0.34739569]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 3125.0]
Fitted coefficients: [0.01733111 0.15910554 0.30064562 0.52291773]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 391.0]
Fitted coefficients: [0.05968301 0.23646174 0.14055677 0.56329848]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 50000.0]
Fitted coefficients: [0.00203701 0.12111854 0.54756245 0.329282  ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 6250.0]
Fitted coefficients: [0.05724713 0.12435415 0.39183724 0.42656148]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 781.0]
Fitted coefficients: [0.02896467 0.21562807 0.21285549 0.54255177]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 100000.0]
Fitted coefficients: [5.51709980e-04 4.69574833e-02 6.79090492e-01 2.73400315e-01]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 25000.0]
Fitted coefficients: [0.0682194  0.02630361 0.52812596 0.37735103]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 3125.0]
Fitted coefficients: [0.09562727 0.03334784 0.30739764 0.56362725]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 391.0]
Fitted coefficients: [0.17627554 0.08084552 0.16744944 0.5754295 ]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 50000.0]
Fitted coefficients: [0.03628866 0.02229117 0.58694696 0.35447321]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 6250.0]
Fitted coefficients: [0.11491168 0.03075045 0.37764706 0.47669081]

Processing sample: Label=['CoVNL63', 'H1N1', 'RSVB1'], Conc=[781.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 781.0]
Fitted coefficients: [0.09227533 0.05765434 0.22568515 0.62438519]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 100.0]
Fitted coefficients: [0.69602501 0.01287107 0.29110393]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [0.48423526 0.4409753  0.07478944]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.63984129 0.20549383 0.15466488]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.67770558 0.11167295 0.21062146]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [0.72172859 0.01788604 0.26038537]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.61945938 0.25023691 0.13030371]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.61373347 0.17535848 0.21090805]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 391.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.68215343 0.05041148 0.26743508]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.55999379 0.33013866 0.10986755]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.63284007 0.17460102 0.19255891]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.64411557 0.09828467 0.25759977]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 100.0]
Fitted coefficients: [0.61800449 0.06292778 0.31906774]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.502229   0.43611523 0.06165577]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.51071443 0.27873004 0.21055552]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.53225654 0.19385229 0.27389117]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.6161397  0.07373789 0.31012241]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.50906676 0.33164174 0.1592915 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.56003865 0.22397973 0.21598162]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.56691109 0.10907797 0.32401094]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.39878691 0.45671599 0.14449709]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.49251309 0.26361049 0.24387642]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[12500.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.58809847 0.14706803 0.26483351]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 100.0]
Fitted coefficients: [0.49781442 0.06066798 0.4415176 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.34450435 0.57804551 0.07745014]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.43697649 0.32255402 0.24046949]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.41119223 0.24023866 0.3485691 ]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.51117264 0.08062739 0.40819996]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.34015323 0.44392831 0.21591846]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.44345252 0.26109299 0.29545449]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.51448851 0.11504346 0.37046803]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.31271642 0.50994935 0.17733423]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.46121114 0.27470581 0.26408305]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.41387948 0.19204909 0.39407144]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 100.0]
Fitted coefficients: [0.0971229  0.01512694 0.88775016]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [1.00000004e-10 4.55724272e-01 5.44275732e-01]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [0.02897361 0.27499238 0.69603401]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [0.07233856 0.17105387 0.75660757]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.1251849  0.02910907 0.84570603]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [0.00316229 0.33316123 0.66367648]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [0.05937976 0.21096709 0.72965315]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [0.13217966 0.06186891 0.80595143]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [1.38220890e-10 4.54958081e-01 5.45041919e-01]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [0.05094475 0.25318261 0.69587264]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [0.09416701 0.1151581  0.7906749 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 100.0]
Fitted coefficients: [0.6771208  0.05703081 0.26584839]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [0.51579207 0.44558626 0.03862168]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.56372914 0.28027249 0.15599837]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 1562.0]
Fitted coefficients: [0.64712576 0.16714882 0.18572542]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.70221445 0.06970495 0.22808059]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.57178461 0.31806174 0.11015364]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.59263535 0.22746251 0.17990215]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.6492367  0.09221143 0.25855187]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.47654029 0.41691309 0.10654663]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.58583922 0.23676456 0.17739622]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.60448249 0.15000355 0.24551396]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 100.0]
Fitted coefficients: [0.57800916 0.08136357 0.34062727]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.3439874  0.58895966 0.06705294]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.45545507 0.32677021 0.21777472]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.48888179 0.23292211 0.2781961 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.58013594 0.09388968 0.32597438]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.42298531 0.40534737 0.17166732]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.42395876 0.29480479 0.28123645]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.56456449 0.12631127 0.30912424]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.3758287  0.48825142 0.13591987]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.5044961 0.2783862 0.2171177]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[3125.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [3125.0, 781.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.48379711 0.18881918 0.32738372]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 100.0]
Fitted coefficients: [0.24451868 0.03320599 0.72227533]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.09344106 0.49099894 0.41556   ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.13141017 0.30565521 0.56293462]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.19350041 0.19265185 0.61384774]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.23983423 0.04587888 0.7142869 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.07057963 0.38726215 0.54215823]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.14909859 0.25699612 0.59390529]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.25051626 0.07808316 0.67140058]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.06324041 0.44934479 0.4874148 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.1507389  0.25145236 0.59780875]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.22504677 0.14091258 0.63404065]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 100.0]
Fitted coefficients: [0.75760809 0.05243321 0.1899587 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [5.40369579e-01 4.59630420e-01 1.27886172e-09]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.68666283 0.22865581 0.08468136]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.67437208 0.17254483 0.15308308]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [0.6970815  0.06307361 0.23984489]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.60157804 0.32176287 0.07665909]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.65687234 0.20971677 0.13341088]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.70782855 0.08962667 0.20254478]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.58964644 0.36241242 0.04794114]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.67188599 0.21923791 0.1088761 ]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.60745302 0.15466888 0.23787809]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 100.0]
Fitted coefficients: [0.63141518 0.07511516 0.29346966]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.36710316 0.55644807 0.07644877]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.46988894 0.31696193 0.21314913]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.52205658 0.2060406  0.27190282]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.58294359 0.08709548 0.32996093]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.47076727 0.36193379 0.16729895]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.49767424 0.25835223 0.24397353]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.56433057 0.11656477 0.31910466]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.40051027 0.45960989 0.13987984]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.49607206 0.26284182 0.24108612]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.55460207 0.1640946  0.28130333]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 100.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 100.0]
Fitted coefficients: [0.36408967 0.04901338 0.58689695]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.18630575 0.56248066 0.25121359]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.25308489 0.3199568  0.42695831]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.31633959 0.192713   0.49094741]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 195.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.38133163 0.06430825 0.55436013]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.20568598 0.40965835 0.38465567]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.29964104 0.23781899 0.46253997]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.34769162 0.09399276 0.55831562]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.25493932 0.38921072 0.35584996]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.2526609  0.28456699 0.46277211]

Processing sample: Label=['CoVNL63', 'H1N1'], Conc=[781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H1N1']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.32468749 0.16013874 0.51517377]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 100000.0]
Fitted coefficients: [0.37446073 0.29181712 0.33055515 0.00316701]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 1562.0]
Fitted coefficients: [0.45550589 0.35419874 0.08237524 0.10792013]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 25000.0]
Fitted coefficients: [0.40875588 0.25252181 0.23365889 0.10506342]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 391.0]
Fitted coefficients: [0.46976205 0.40853817 0.03163839 0.09006139]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 50000.0]
Fitted coefficients: [0.37023399 0.31053276 0.23161383 0.08761942]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 6250.0]
Fitted coefficients: [0.46286277 0.25776486 0.18649767 0.0928747 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0, 781.0]
Fitted coefficients: [0.52835575 0.33707888 0.05960455 0.07496082]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 100000.0]
Fitted coefficients: [0.43652073 0.03163225 0.42199202 0.109855  ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 1562.0]
Fitted coefficients: [0.59524649 0.01484287 0.15890994 0.2310007 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 25000.0]
Fitted coefficients: [0.47176513 0.02072591 0.26947677 0.23803219]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 391.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Fitted coefficients: [0.69092154 0.03305068 0.08068141 0.19534637]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 50000.0]
Fitted coefficients: [0.46220976 0.00382204 0.34056768 0.19340052]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 6250.0]
Fitted coefficients: [0.49834969 0.01164761 0.2436727  0.24633   ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0, 781.0]
Fitted coefficients: [0.6168102  0.03062025 0.1279748  0.22459474]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0, 100000.0]
Fitted coefficients: [4.67863605e-01 1.00040883e-10 4.44904169e-01 8.72322255e-02]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0, 1562.0]
Fitted coefficients: [6.29641610e-01 1.00000000e-10 1.58834714e-01 2.11523676e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0, 25000.0]
Fitted coefficients: [4.87233439e-01 1.00097892e-10 3.37860527e-01 1.74906033e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0, 391.0]
Fitted coefficients: [7.11776050e-01 2.58244584e-09 8.62088789e-02 2.02015072e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0, 50000.0]
Fitted coefficients: [5.52686139e-01 1.04584664e-10 3.06651324e-01 1.40662536e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0, 6250.0]
Fitted coefficients: [5.89935478e-01 1.02003165e-10 2.29429447e-01 1.80635075e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0, 781.0]
Fitted coefficients: [6.93232708e-01 1.02666886e-10 1.27013370e-01 1.79753921e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 100000.0]
Fitted coefficients: [0.25686964 0.254893   0.33949275 0.14874461]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 1562.0]
Fitted coefficients: [0.45947903 0.29435482 0.04691683 0.19924931]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 25000.0]
Fitted coefficients: [0.33908719 0.21717491 0.23017055 0.21356735]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 391.0]
Fitted coefficients: [0.46022272 0.31281218 0.01171856 0.21524654]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 50000.0]
Fitted coefficients: [0.36580212 0.22338923 0.22707488 0.18373377]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 6250.0]
Fitted coefficients: [0.37617022 0.22846093 0.16160965 0.2337592 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0, 781.0]
Fitted coefficients: [0.46973076 0.2656241  0.05528546 0.20935968]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.42952553 0.00384671 0.46619569 0.10043207]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 1562.0]
Fitted coefficients: [6.07685632e-01 1.00177010e-10 1.59373569e-01 2.32940799e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 25000.0]
Fitted coefficients: [5.16853072e-01 1.00000000e-10 3.07351029e-01 1.75795899e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 391.0]
Fitted coefficients: [0.73785474 0.00379602 0.07224543 0.1861038 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 50000.0]
Fitted coefficients: [4.48955270e-01 1.05046098e-10 3.74194758e-01 1.76849971e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 6250.0]
Fitted coefficients: [5.99335795e-01 1.00457244e-10 2.02149596e-01 1.98514609e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0, 781.0]
Fitted coefficients: [6.54163131e-01 1.00000692e-10 1.26364109e-01 2.19472760e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 100000.0]
Fitted coefficients: [0.27588832 0.26635006 0.33171246 0.12604916]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 1562.0]
Fitted coefficients: [0.4305286  0.27131535 0.09824176 0.1999143 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 25000.0]
Fitted coefficients: [0.38551009 0.24402393 0.18987586 0.18059012]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 391.0]
Fitted coefficients: [0.50790741 0.30815548 0.01372881 0.1702083 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 50000.0]
Fitted coefficients: [0.2901139  0.29288111 0.2399555  0.17704949]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 6250.0]
Fitted coefficients: [0.39533317 0.32109675 0.10164074 0.18192933]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0, 781.0]
Fitted coefficients: [0.4497575  0.32113022 0.0422735  0.18683878]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 100000.0]
Fitted coefficients: [0.39834121 0.11736946 0.40071872 0.08357061]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 1562.0]
Fitted coefficients: [0.53179533 0.11299313 0.16556449 0.18964706]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 25000.0]
Fitted coefficients: [0.44351179 0.10662639 0.2813646  0.16849722]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 391.0]
Fitted coefficients: [0.59593512 0.13300071 0.08433312 0.18673105]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 50000.0]
Fitted coefficients: [0.43764618 0.08621818 0.3126064  0.16352923]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 6250.0]
Fitted coefficients: [0.4915172  0.08156994 0.24994422 0.17696865]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0, 781.0]
Fitted coefficients: [0.62173374 0.11353155 0.11253138 0.15220334]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 100000.0]
Fitted coefficients: [0.48235403 0.01395651 0.39723739 0.10645206]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 1562.0]
Fitted coefficients: [0.6578022  0.01334834 0.13210195 0.19674751]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 25000.0]
Fitted coefficients: [5.04482498e-01 3.33632364e-09 2.91615508e-01 2.03901996e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 391.0]
Fitted coefficients: [0.71204356 0.02872669 0.06989824 0.18933151]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 50000.0]
Fitted coefficients: [4.71925133e-01 1.00000000e-10 3.38609087e-01 1.89465779e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 6250.0]
Fitted coefficients: [5.85511980e-01 4.85849529e-05 2.25635451e-01 1.88803984e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[100000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0, 781.0]
Fitted coefficients: [0.61078178 0.00115502 0.14256261 0.24550058]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 100000.0]
Fitted coefficients: [0.04843062 0.43245693 0.50831222 0.01080024]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 1562.0]
Fitted coefficients: [0.17045887 0.53379698 0.16110132 0.13464283]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 25000.0]
Fitted coefficients: [0.07600049 0.45319558 0.34232295 0.12848098]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 391.0]
Fitted coefficients: [0.14219841 0.66099535 0.07100913 0.12579711]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 50000.0]
Fitted coefficients: [0.07419188 0.40829504 0.39748492 0.12002817]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 6250.0]
Fitted coefficients: [0.12297918 0.52191607 0.23750354 0.11760121]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0, 781.0]
Fitted coefficients: [0.17319944 0.55736461 0.12748238 0.14195356]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 100000.0]
Fitted coefficients: [0.09437899 0.06296544 0.71014258 0.132513  ]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 1562.0]
Fitted coefficients: [0.26509389 0.05779934 0.30353681 0.37356996]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 25000.0]
Fitted coefficients: [0.17951808 0.04392097 0.45230285 0.3242581 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 391.0]
Fitted coefficients: [0.26033105 0.10706297 0.19495021 0.43765576]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 50000.0]
Fitted coefficients: [0.16643775 0.03129623 0.53438612 0.2678799 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 6250.0]
Fitted coefficients: [0.19598823 0.0495085  0.40758504 0.34691823]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0, 781.0]
Fitted coefficients: [0.27347859 0.07166714 0.26001895 0.39483532]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0, 100000.0]
Fitted coefficients: [0.1221219  0.00610054 0.78982578 0.08195178]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0, 1562.0]
Fitted coefficients: [2.97499823e-01 1.01214289e-10 3.56878644e-01 3.45621533e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0, 25000.0]
Fitted coefficients: [1.93816105e-01 1.05900902e-10 5.56317641e-01 2.49866254e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0, 391.0]
Fitted coefficients: [4.38149081e-01 1.00000000e-10 2.07798919e-01 3.54052000e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0, 50000.0]
Fitted coefficients: [1.81511145e-01 1.00000000e-10 5.75221492e-01 2.43267363e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0, 6250.0]
Fitted coefficients: [2.50631116e-01 1.02204709e-10 4.60984006e-01 2.88384877e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0, 781.0]
Fitted coefficients: [3.39404486e-01 1.00142671e-10 3.08464369e-01 3.52131145e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 100000.0]
Fitted coefficients: [1.00000197e-10 3.56483939e-01 5.34399484e-01 1.09116576e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 1562.0]
Fitted coefficients: [0.05456537 0.46709148 0.15886775 0.3194754 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 25000.0]
Fitted coefficients: [0.0671393  0.32401783 0.35098188 0.25786099]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 391.0]
Fitted coefficients: [0.10843295 0.51226089 0.0478862  0.33141996]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 50000.0]
Fitted coefficients: [0.02170279 0.38622761 0.33951166 0.25255794]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 6250.0]
Fitted coefficients: [0.07151928 0.38695894 0.261737   0.27978477]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0, 781.0]
Fitted coefficients: [0.07423189 0.48921304 0.11412275 0.32243232]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 100000.0]
Fitted coefficients: [0.11233565 0.02630247 0.74715022 0.11421167]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 1562.0]
Fitted coefficients: [0.28907947 0.02597691 0.3039727  0.38097091]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 25000.0]
Fitted coefficients: [1.99459252e-01 4.05401338e-10 5.35527279e-01 2.65013468e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 391.0]
Fitted coefficients: [0.36423429 0.03946988 0.21534494 0.38095089]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 50000.0]
Fitted coefficients: [2.05117100e-01 7.20359967e-10 5.51979667e-01 2.42903232e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 6250.0]
Fitted coefficients: [0.25037919 0.01228599 0.42561976 0.31171506]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0, 781.0]
Fitted coefficients: [0.32454215 0.00987825 0.29212253 0.37345707]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 3.65616981e-01 5.29857315e-01 1.04525705e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 1562.0]
Fitted coefficients: [0.09415487 0.43932982 0.17465051 0.2918648 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 25000.0]
Fitted coefficients: [0.03115193 0.41026989 0.32791077 0.2306674 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 391.0]
Fitted coefficients: [0.04602425 0.6120767  0.03180419 0.31009486]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 50000.0]
Fitted coefficients: [0.04908931 0.34630326 0.39721418 0.20739325]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 6250.0]
Fitted coefficients: [0.06096918 0.43642213 0.25016833 0.25244036]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0, 781.0]
Fitted coefficients: [0.0904796  0.50327211 0.11099472 0.29525358]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 100000.0]
Fitted coefficients: [0.09796984 0.16556457 0.63225064 0.10421495]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 1562.0]
Fitted coefficients: [0.2137204  0.19083438 0.31099769 0.28444753]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 25000.0]
Fitted coefficients: [0.16707743 0.13763711 0.4709082  0.22437726]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 391.0]
Fitted coefficients: [0.26242882 0.2485197  0.1935265  0.29552498]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 50000.0]
Fitted coefficients: [0.14651353 0.14422132 0.49852751 0.21073764]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 6250.0]
Fitted coefficients: [0.16078382 0.19714641 0.37659358 0.26547619]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0, 781.0]
Fitted coefficients: [0.22231937 0.22649094 0.25695309 0.2942366 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 100000.0]
Fitted coefficients: [0.09442484 0.05529005 0.69605689 0.15422822]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 1562.0]
Fitted coefficients: [0.30554724 0.03704283 0.30158804 0.35582188]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 25000.0]
Fitted coefficients: [0.19099478 0.01716326 0.49063614 0.30120582]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 391.0]
Fitted coefficients: [0.3246884  0.05702436 0.20992969 0.40835755]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 50000.0]
Fitted coefficients: [0.18028771 0.02231724 0.51710786 0.28028719]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 6250.0]
Fitted coefficients: [0.21242448 0.01435413 0.44691955 0.32630184]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[1562.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0, 781.0]
Fitted coefficients: [0.33309268 0.05314992 0.24780077 0.36595664]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 100000.0]
Fitted coefficients: [2.59157514e-01 3.81223453e-01 3.59619040e-01 3.29220422e-10]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 1562.0]
Fitted coefficients: [0.38904664 0.38015314 0.14650824 0.08429198]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 25000.0]
Fitted coefficients: [0.2990312  0.36033096 0.26803473 0.0726031 ]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 391.0]
Fitted coefficients: [0.471487   0.40144727 0.08624056 0.04082517]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 50000.0]
Fitted coefficients: [0.28705623 0.32073434 0.30788406 0.08432537]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 6250.0]
Fitted coefficients: [0.33229607 0.35858447 0.22010228 0.08901718]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0, 781.0]
Fitted coefficients: [0.35260438 0.45930731 0.09606248 0.09202582]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 100000.0]
Fitted coefficients: [0.33089081 0.06118192 0.533218   0.07470927]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 1562.0]
Fitted coefficients: [0.4528108  0.0479109  0.24334727 0.25593103]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 25000.0]
Fitted coefficients: [0.40294305 0.04637787 0.35006971 0.20060936]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 391.0]
Fitted coefficients: [0.52675795 0.08664584 0.14100978 0.24558642]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 50000.0]
Fitted coefficients: [0.36257865 0.04270771 0.41175251 0.18296114]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 6250.0]
Fitted coefficients: [0.42783205 0.04612051 0.30177011 0.22427734]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0, 781.0]
Fitted coefficients: [0.51092276 0.07343196 0.17564587 0.23999941]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0, 100000.0]
Fitted coefficients: [0.3446327  0.01931474 0.5696265  0.06642606]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0, 1562.0]
Fitted coefficients: [5.45822637e-01 5.93207359e-09 2.46045012e-01 2.08132353e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0, 25000.0]
Fitted coefficients: [3.60317226e-01 1.00000000e-10 4.46391604e-01 1.93291170e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0, 391.0]
Fitted coefficients: [0.69700873 0.02975009 0.13988773 0.13335345]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0, 50000.0]
Fitted coefficients: [3.98494328e-01 1.00005037e-10 4.26822374e-01 1.74683298e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0, 6250.0]
Fitted coefficients: [4.69196999e-01 1.00000000e-10 3.42577477e-01 1.88225524e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0, 781.0]
Fitted coefficients: [0.57920003 0.01041954 0.19284683 0.2175336 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 100000.0]
Fitted coefficients: [0.16866821 0.27248846 0.47349423 0.08534909]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 1562.0]
Fitted coefficients: [0.29815317 0.38986037 0.09463663 0.21734983]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 25000.0]
Fitted coefficients: [0.1843718  0.32172915 0.26873534 0.22516371]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 391.0]
Fitted coefficients: [0.35514565 0.39607631 0.03325384 0.21552419]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 50000.0]
Fitted coefficients: [0.22907239 0.24490688 0.33031643 0.19570429]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 6250.0]
Fitted coefficients: [0.25458492 0.30819371 0.20823187 0.2289895 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0, 781.0]
Fitted coefficients: [0.28429446 0.41936111 0.06536193 0.2309825 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 100000.0]
Fitted coefficients: [0.40066501 0.04073263 0.50817032 0.05043204]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 1562.0]
Fitted coefficients: [0.53384954 0.03164017 0.2229584  0.2115519 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 25000.0]
Fitted coefficients: [0.42817288 0.01712752 0.36838732 0.18631228]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 391.0]
Fitted coefficients: [0.58869101 0.04264117 0.15565858 0.21300924]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 50000.0]
Fitted coefficients: [0.39864518 0.00582658 0.42734434 0.16818389]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 6250.0]
Fitted coefficients: [0.47749446 0.02054497 0.30616939 0.19579117]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0, 781.0]
Fitted coefficients: [0.57798806 0.03633961 0.18637607 0.19929627]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 100000.0]
Fitted coefficients: [0.19921954 0.30086123 0.42316091 0.07675833]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 1562.0]
Fitted coefficients: [0.35726661 0.35087925 0.11216551 0.17968863]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 25000.0]
Fitted coefficients: [0.28978859 0.2613276  0.28061145 0.16827235]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 391.0]
Fitted coefficients: [0.37495723 0.4111391  0.04206252 0.17184115]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 50000.0]
Fitted coefficients: [0.16929804 0.35974926 0.28213514 0.18881756]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 6250.0]
Fitted coefficients: [0.33325751 0.29814014 0.19737615 0.1712262 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0, 781.0]
Fitted coefficients: [0.31167286 0.41896157 0.07062489 0.19874068]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 100000.0]
Fitted coefficients: [0.3069648  0.15287908 0.4767928  0.06336332]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 1562.0]
Fitted coefficients: [0.45068978 0.1555783  0.22138963 0.17234229]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 25000.0]
Fitted coefficients: [0.40555827 0.1280259  0.33214792 0.13426792]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 391.0]
Fitted coefficients: [0.4986533  0.20225578 0.14483949 0.15425143]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 50000.0]
Fitted coefficients: [0.32004604 0.11934518 0.40432633 0.15628245]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 6250.0]
Fitted coefficients: [0.42433814 0.14435705 0.27847044 0.15283437]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0, 781.0]
Fitted coefficients: [0.48310307 0.18812232 0.16978141 0.15899321]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 100000.0]
Fitted coefficients: [0.35503505 0.04751443 0.56102957 0.03642096]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 1562.0]
Fitted coefficients: [0.54185152 0.04603983 0.20660422 0.20550443]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 25000.0]
Fitted coefficients: [0.39432713 0.01771073 0.39141847 0.19654367]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 391.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.62922892 0.06559232 0.12102839 0.18415037]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 50000.0]
Fitted coefficients: [0.40451557 0.0328971  0.37864038 0.18394696]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 6250.0]
Fitted coefficients: [0.38599148 0.01811243 0.35093332 0.24496277]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[25000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0, 781.0]
Fitted coefficients: [0.57658934 0.05592125 0.17005054 0.19743887]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 100000.0]
Fitted coefficients: [1.00003139e-10 4.62862955e-01 4.67663517e-01 6.94735281e-02]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 1562.0]
Fitted coefficients: [0.00830752 0.58274447 0.17124902 0.23769899]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 4.76067140e-01 3.09867532e-01 2.14065328e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 391.0]
Fitted coefficients: [1.00000000e-10 6.73654734e-01 6.75807848e-02 2.58764481e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 50000.0]
Fitted coefficients: [1.00000000e-10 4.40644288e-01 3.66933030e-01 1.92422682e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 6250.0]
Fitted coefficients: [1.00003289e-10 4.91569680e-01 2.59728701e-01 2.48701619e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0, 781.0]
Fitted coefficients: [1.00000212e-10 5.96721679e-01 1.35940016e-01 2.67338304e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 100000.0]
Fitted coefficients: [1.00000000e-10 4.42022820e-02 7.68958899e-01 1.86838819e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 1562.0]
Fitted coefficients: [0.05763187 0.06493946 0.32349457 0.5539341 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 25000.0]
Fitted coefficients: [0.06165732 0.02743323 0.54238742 0.36852203]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 391.0]
Fitted coefficients: [0.04684915 0.09362922 0.2162372  0.64328443]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 50000.0]
Fitted coefficients: [0.01733535 0.06484584 0.49348678 0.42433204]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 6250.0]
Fitted coefficients: [0.0609676  0.05481471 0.41180015 0.47241753]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0, 781.0]
Fitted coefficients: [0.05995647 0.0797136  0.27841108 0.58191885]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0, 100000.0]
Fitted coefficients: [6.02448066e-09 1.00000007e-10 8.22970687e-01 1.77029313e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0, 1562.0]
Fitted coefficients: [8.12096961e-02 1.00000000e-10 3.85747667e-01 5.33042637e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0, 25000.0]
Fitted coefficients: [5.69337717e-02 9.89263589e-10 5.95871771e-01 3.47194457e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0, 391.0]
Fitted coefficients: [6.33543275e-02 1.00000000e-10 2.52923844e-01 6.83721829e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0, 50000.0]
Fitted coefficients: [4.15321039e-02 1.00000000e-10 5.99445545e-01 3.59022351e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0, 6250.0]
Fitted coefficients: [5.37714905e-02 1.03709119e-10 4.96781479e-01 4.49447031e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0, 781.0]
Fitted coefficients: [6.56013363e-02 1.00000000e-10 3.27204987e-01 6.07193676e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 100000.0]
Fitted coefficients: [1.10466698e-10 3.17923935e-01 5.35858720e-01 1.46217345e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 1562.0]
Fitted coefficients: [8.20336091e-10 4.98702768e-01 9.94357304e-02 4.01861502e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 25000.0]
Fitted coefficients: [1.00001259e-10 3.38341576e-01 3.52084785e-01 3.09573639e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 391.0]
Fitted coefficients: [1.02644140e-10 5.31013066e-01 3.84443770e-02 4.30542557e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 50000.0]
Fitted coefficients: [1.00003013e-10 3.36857776e-01 3.70184193e-01 2.92958031e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 6250.0]
Fitted coefficients: [1.00000551e-10 3.72640490e-01 2.49177396e-01 3.78182113e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0, 781.0]
Fitted coefficients: [1.00000002e-10 4.74597160e-01 1.08615855e-01 4.16786988e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 100000.0]
Fitted coefficients: [1.00000000e-10 2.74477018e-02 7.58740748e-01 2.13811550e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 1562.0]
Fitted coefficients: [9.99858763e-02 1.00003510e-10 3.79012395e-01 5.21001729e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 25000.0]
Fitted coefficients: [7.48305559e-02 1.00197226e-10 5.77280291e-01 3.47889153e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 391.0]
Fitted coefficients: [0.08768656 0.00161303 0.24467369 0.66602672]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 50000.0]
Fitted coefficients: [5.08408247e-02 1.00000902e-10 5.99589480e-01 3.49569695e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 6250.0]
Fitted coefficients: [8.98476817e-02 1.00000000e-10 4.83947469e-01 4.26204849e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0, 781.0]
Fitted coefficients: [9.72205085e-02 1.00006411e-10 3.17088045e-01 5.85691447e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 100000.0]
Fitted coefficients: [1.52859445e-09 3.46184172e-01 5.31137369e-01 1.22678458e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 1562.0]
Fitted coefficients: [4.60134684e-10 4.82407215e-01 1.39561423e-01 3.78031361e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 3.46945462e-01 3.64159357e-01 2.88895182e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 391.0]
Fitted coefficients: [1.09539392e-10 5.84872303e-01 6.37288599e-03 4.08754811e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 50000.0]
Fitted coefficients: [1.00000257e-10 3.41440549e-01 3.91701595e-01 2.66857856e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 6250.0]
Fitted coefficients: [1.03202053e-10 4.73208505e-01 2.20691490e-01 3.06100005e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0, 781.0]
Fitted coefficients: [1.82203996e-09 5.36958639e-01 7.99146791e-02 3.83126682e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 100000.0]
Fitted coefficients: [1.00001591e-10 1.54217010e-01 7.10512329e-01 1.35270661e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 1562.0]
Fitted coefficients: [0.0695571  0.19766168 0.31093179 0.42184943]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 25000.0]
Fitted coefficients: [0.05513142 0.1356698  0.48777988 0.32141889]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 391.0]
Fitted coefficients: [0.07426749 0.25713441 0.22372401 0.44487409]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 50000.0]
Fitted coefficients: [0.04072477 0.16207649 0.50107251 0.29612623]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 6250.0]
Fitted coefficients: [0.06762366 0.16554062 0.41614396 0.35069175]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0, 781.0]
Fitted coefficients: [0.07312998 0.22899168 0.28291558 0.41496276]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 100000.0]
Fitted coefficients: [1.00556170e-10 3.80474329e-02 7.50758779e-01 2.11193788e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 1562.0]
Fitted coefficients: [0.07525243 0.02298129 0.35474823 0.54701805]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 25000.0]
Fitted coefficients: [0.06356592 0.01360209 0.52249733 0.40033466]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 391.0]
Fitted coefficients: [0.05164841 0.06469929 0.21925797 0.66439432]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 50000.0]
Fitted coefficients: [0.05082575 0.01477555 0.57688969 0.35750901]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 6250.0]
Fitted coefficients: [0.05533683 0.02764443 0.45304383 0.46397491]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[391.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0, 781.0]
Fitted coefficients: [0.08536657 0.02778976 0.31183585 0.57500783]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 100000.0]
Fitted coefficients: [2.63849389e-01 3.21022508e-01 4.15128104e-01 2.89566939e-10]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 1562.0]
Fitted coefficients: [0.44080622 0.40865754 0.09769823 0.05283802]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 25000.0]
Fitted coefficients: [0.37689398 0.3303648  0.23955743 0.05318378]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 391.0]
Fitted coefficients: [0.46525221 0.43785703 0.06033356 0.0365572 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 50000.0]
Fitted coefficients: [0.36584561 0.30188708 0.27649047 0.05577684]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 6250.0]
Fitted coefficients: [0.39372623 0.37776528 0.16624066 0.06226782]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0, 781.0]
Fitted coefficients: [0.48785031 0.39387668 0.08854122 0.0297318 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 100000.0]
Fitted coefficients: [0.3579825  0.05217036 0.53517598 0.05467116]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 1562.0]
Fitted coefficients: [0.54241967 0.05240952 0.19825993 0.20691088]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 25000.0]
Fitted coefficients: [0.48617647 0.0430401  0.30338584 0.16739759]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 391.0]
Fitted coefficients: [0.65453332 0.08042168 0.10361325 0.16143176]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 50000.0]
Fitted coefficients: [0.47127817 0.04872166 0.32716733 0.15283284]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 6250.0]
Fitted coefficients: [0.49807326 0.05918757 0.25378988 0.18894929]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0, 781.0]
Fitted coefficients: [0.56173669 0.07357204 0.16149025 0.20320103]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0, 100000.0]
Fitted coefficients: [0.43624651 0.01774951 0.52337477 0.02262921]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0, 1562.0]
Fitted coefficients: [0.66682531 0.00878632 0.1883577  0.13603067]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0, 25000.0]
Fitted coefficients: [5.11311916e-01 2.45514457e-10 3.48386252e-01 1.40301846e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0, 391.0]
Fitted coefficients: [0.73659017 0.0185288  0.11213197 0.13274906]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0, 50000.0]
Fitted coefficients: [4.91207935e-01 1.00011358e-10 3.81926794e-01 1.26865271e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0, 6250.0]
Fitted coefficients: [5.41879071e-01 1.38266312e-10 3.07952319e-01 1.50168610e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0, 781.0]
Fitted coefficients: [0.70358064 0.00967777 0.15728416 0.12945742]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 100000.0]
Fitted coefficients: [0.2371037  0.26699763 0.41538838 0.08051029]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 1562.0]
Fitted coefficients: [0.44639322 0.32374747 0.07419885 0.15566047]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 25000.0]
Fitted coefficients: [0.27958517 0.30856277 0.22888491 0.18296715]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 391.0]
Fitted coefficients: [0.42733667 0.38026946 0.01815208 0.17424179]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 50000.0]
Fitted coefficients: [0.34392178 0.28020582 0.23151341 0.14435899]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 6250.0]
Fitted coefficients: [0.2838763  0.31916965 0.18532424 0.2116298 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0, 781.0]
Fitted coefficients: [0.40327131 0.3552603  0.05405914 0.18740925]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 100000.0]
Fitted coefficients: [0.40276648 0.03802397 0.51925726 0.03995228]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 1562.0]
Fitted coefficients: [0.62599552 0.02121854 0.20255366 0.15023228]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 25000.0]
Fitted coefficients: [0.54261308 0.02017878 0.31349094 0.1237172 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 391.0]
Fitted coefficients: [0.69581672 0.04167473 0.11138043 0.15112813]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 50000.0]
Fitted coefficients: [0.46103258 0.00791392 0.39934693 0.13170657]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 6250.0]
Fitted coefficients: [0.57203872 0.01819006 0.27972044 0.13005078]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0, 781.0]
Fitted coefficients: [0.6807989  0.03953505 0.14741758 0.13224847]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 100000.0]
Fitted coefficients: [0.30100563 0.32143479 0.33738045 0.04017913]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 1562.0]
Fitted coefficients: [0.37931247 0.36510479 0.09464079 0.16094196]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 25000.0]
Fitted coefficients: [0.274752   0.31859819 0.24597633 0.16067349]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 391.0]
Fitted coefficients: [0.35098145 0.45905574 0.01993602 0.17002679]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 50000.0]
Fitted coefficients: [0.32390133 0.31416921 0.22957741 0.13235206]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 6250.0]
Fitted coefficients: [0.37332211 0.30792271 0.16612818 0.15262699]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0, 781.0]
Fitted coefficients: [0.38427764 0.40083369 0.05040442 0.16448425]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 100000.0]
Fitted coefficients: [0.36941475 0.13053642 0.48770149 0.01234734]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 1562.0]
Fitted coefficients: [0.53563275 0.14171803 0.18397168 0.13867754]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 25000.0]
Fitted coefficients: [0.41406199 0.10664506 0.34101134 0.13828161]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 391.0]
Fitted coefficients: [0.54136662 0.19826079 0.12764594 0.13272666]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 50000.0]
Fitted coefficients: [0.41815377 0.10785135 0.36613005 0.10786484]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 6250.0]
Fitted coefficients: [0.50462211 0.14964928 0.23339023 0.11233838]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0, 781.0]
Fitted coefficients: [0.56518572 0.18487426 0.13947481 0.11046521]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 100000.0]
Fitted coefficients: [0.35587109 0.04270612 0.55751591 0.04390688]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 1562.0]
Fitted coefficients: [0.62801966 0.0440297  0.17430527 0.15364538]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 25000.0]
Fitted coefficients: [0.46441414 0.02574486 0.34774978 0.16209122]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 391.0]
Fitted coefficients: [0.67412776 0.05910909 0.10983354 0.15692961]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 50000.0]
Fitted coefficients: [0.39540944 0.01569657 0.4282211  0.16067289]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 6250.0]
Fitted coefficients: [0.523382   0.04028843 0.2720809  0.16424867]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[50000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0, 781.0]
Fitted coefficients: [0.62591039 0.0479696  0.15429448 0.17182553]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 100000.0]
Fitted coefficients: [0.11391728 0.3730054  0.49766336 0.01541396]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 1562.0]
Fitted coefficients: [0.23994121 0.45915772 0.17317868 0.12772239]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 25000.0]
Fitted coefficients: [0.16398444 0.41480712 0.3109696  0.11023885]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 391.0]
Fitted coefficients: [0.27247122 0.55123885 0.08579814 0.09049178]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 50000.0]
Fitted coefficients: [0.13758002 0.42079367 0.34530648 0.09631982]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 6250.0]
Fitted coefficients: [0.21763055 0.4538315  0.22739968 0.10113827]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0, 781.0]
Fitted coefficients: [0.24334645 0.52469442 0.12735805 0.10460107]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 100000.0]
Fitted coefficients: [0.19125413 0.06321908 0.65323533 0.09229146]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 1562.0]
Fitted coefficients: [0.37180625 0.07729414 0.25139691 0.2995027 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 25000.0]
Fitted coefficients: [0.26500311 0.03655747 0.44716407 0.25127536]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 391.0]
Fitted coefficients: [0.44084971 0.09698328 0.175378   0.28678901]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 50000.0]
Fitted coefficients: [0.22173138 0.04081099 0.49008002 0.24737761]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 6250.0]
Fitted coefficients: [0.28751836 0.04815973 0.37868251 0.2856394 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0, 781.0]
Fitted coefficients: [0.36789212 0.09325457 0.22005822 0.3187951 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0, 100000.0]
Fitted coefficients: [0.18396986 0.0156821  0.70356699 0.09678106]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0, 1562.0]
Fitted coefficients: [4.07851712e-01 4.47170030e-05 3.06340499e-01 2.85763073e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0, 25000.0]
Fitted coefficients: [2.92264720e-01 1.00004164e-10 4.94894337e-01 2.12840943e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0, 391.0]
Fitted coefficients: [0.51438945 0.02166137 0.20025915 0.26369003]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0, 50000.0]
Fitted coefficients: [2.70868192e-01 1.00224782e-10 5.33656734e-01 1.95475075e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0, 6250.0]
Fitted coefficients: [3.80265813e-01 1.00003976e-10 3.87574427e-01 2.32159760e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0, 781.0]
Fitted coefficients: [4.38870142e-01 1.55630873e-04 2.66268292e-01 2.94705935e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 100000.0]
Fitted coefficients: [0.06457373 0.3256746  0.49034085 0.11941082]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 1562.0]
Fitted coefficients: [0.13100116 0.4339171  0.13772044 0.2973613 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 25000.0]
Fitted coefficients: [0.11417585 0.30353143 0.3420977  0.24019501]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 391.0]
Fitted coefficients: [0.19570142 0.46814405 0.05611483 0.28003971]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 50000.0]
Fitted coefficients: [0.11548993 0.30610086 0.34690063 0.23150857]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 6250.0]
Fitted coefficients: [0.10701369 0.38838808 0.23318569 0.27141253]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0, 781.0]
Fitted coefficients: [0.14724007 0.47643444 0.08617479 0.2901507 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 100000.0]
Fitted coefficients: [0.22354221 0.03737774 0.65314807 0.08593198]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 1562.0]
Fitted coefficients: [0.37568678 0.02653557 0.29675004 0.30102761]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 25000.0]
Fitted coefficients: [0.27949011 0.00817834 0.47862607 0.23370548]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 391.0]
Fitted coefficients: [0.45209567 0.03727352 0.20722941 0.3034014 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 50000.0]
Fitted coefficients: [0.27133203 0.00564108 0.51397254 0.20905435]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 6250.0]
Fitted coefficients: [0.32667084 0.02586424 0.38930999 0.25815492]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0, 781.0]
Fitted coefficients: [0.41254042 0.03556579 0.26364399 0.2882498 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 100000.0]
Fitted coefficients: [0.05475337 0.38559755 0.47659933 0.08304975]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 1562.0]
Fitted coefficients: [0.14485116 0.46085481 0.12803047 0.26626356]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 25000.0]
Fitted coefficients: [0.08591905 0.39391836 0.29798785 0.22217474]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 391.0]
Fitted coefficients: [0.20128795 0.51422946 0.04403344 0.24044915]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 50000.0]
Fitted coefficients: [0.06129269 0.39388171 0.33397527 0.21085033]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 6250.0]
Fitted coefficients: [0.13130188 0.42012756 0.20924029 0.23933027]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0, 781.0]
Fitted coefficients: [0.18128328 0.49370304 0.08416529 0.24084839]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 100000.0]
Fitted coefficients: [0.13531039 0.15420724 0.64017498 0.07030739]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 1562.0]
Fitted coefficients: [0.33127905 0.1878224  0.25966931 0.22122925]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 25000.0]
Fitted coefficients: [0.25102227 0.13898807 0.41272308 0.19726657]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 391.0]
Fitted coefficients: [0.3869634  0.2095477  0.19370163 0.20978726]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 50000.0]
Fitted coefficients: [0.19695417 0.11025194 0.5164104  0.17638349]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 6250.0]
Fitted coefficients: [0.29029517 0.14659806 0.3617694  0.20133737]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0, 781.0]
Fitted coefficients: [0.32989408 0.19381483 0.23729579 0.2389953 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 100000.0]
Fitted coefficients: [0.18006233 0.03782929 0.66665604 0.11545234]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 1562.0]
Fitted coefficients: [0.37852321 0.04758985 0.28160348 0.29228346]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 25000.0]
Fitted coefficients: [0.27800153 0.02675696 0.44928309 0.24595842]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 391.0]
Fitted coefficients: [0.43808542 0.07065237 0.19351896 0.29774326]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 50000.0]
Fitted coefficients: [0.2676414  0.02139677 0.49343943 0.2175224 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 6250.0]
Fitted coefficients: [0.30181331 0.03035402 0.38698056 0.28085211]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[6250.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0, 781.0]
Fitted coefficients: [0.37842157 0.06321689 0.24310081 0.31526074]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 4.30883695e-01 5.28237467e-01 4.08788383e-02]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 1562.0]
Fitted coefficients: [0.07936635 0.59778277 0.12395094 0.19889994]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 25000.0]
Fitted coefficients: [0.03067084 0.42546432 0.34550026 0.19836458]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 391.0]
Fitted coefficients: [0.06222144 0.65155542 0.06271299 0.22351014]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 50000.0]
Fitted coefficients: [0.01336781 0.4509972  0.35919504 0.17643995]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 6250.0]
Fitted coefficients: [0.03147657 0.53601979 0.23983566 0.19266799]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0, 781.0]
Fitted coefficients: [0.09508767 0.58165957 0.12728723 0.19596552]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 100000.0]
Fitted coefficients: [0.03928053 0.06566678 0.69987057 0.19518212]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 1562.0]
Fitted coefficients: [0.17106731 0.0423907  0.30815644 0.47838555]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 25000.0]
Fitted coefficients: [0.12977192 0.03582569 0.4700474  0.364355  ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 391.0]
Fitted coefficients: [0.13757052 0.09053829 0.19980013 0.57209105]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 50000.0]
Fitted coefficients: [0.09888055 0.04398422 0.50412844 0.35300679]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 6250.0]
Fitted coefficients: [0.12998756 0.02760895 0.45726899 0.3851345 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0, 781.0]
Fitted coefficients: [0.14294118 0.07745401 0.2581486  0.52145622]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.04555251 0.00138524 0.8160792  0.13698304]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0, 1562.0]
Fitted coefficients: [1.69681975e-01 1.09808577e-10 3.80661477e-01 4.49656548e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0, 25000.0]
Fitted coefficients: [1.15039930e-01 1.01397285e-10 5.50179971e-01 3.34780099e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0, 391.0]
Fitted coefficients: [2.10509984e-01 1.00000000e-10 2.19414245e-01 5.70075771e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0, 50000.0]
Fitted coefficients: [1.02510520e-01 1.02079713e-10 5.73546409e-01 3.23943071e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0, 6250.0]
Fitted coefficients: [1.45256291e-01 1.04522316e-10 4.70546746e-01 3.84196963e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0, 781.0]
Fitted coefficients: [1.83781520e-01 1.00000000e-10 2.96291253e-01 5.19927227e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 100000.0]
Fitted coefficients: [1.67479387e-09 3.58470241e-01 5.05827914e-01 1.35701844e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 1562.0]
Fitted coefficients: [0.00146287 0.44401736 0.16160364 0.39291612]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 25000.0]
Fitted coefficients: [1.95952393e-04 3.59230118e-01 3.27003884e-01 3.13570045e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 391.0]
Fitted coefficients: [1.00021191e-10 5.29440667e-01 4.48217258e-02 4.25737608e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 50000.0]
Fitted coefficients: [1.00000000e-10 3.33212136e-01 3.64650699e-01 3.02137164e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 6250.0]
Fitted coefficients: [0.0159244  0.35765059 0.26987699 0.35654802]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0, 781.0]
Fitted coefficients: [1.00000002e-10 5.17304560e-01 7.98910197e-02 4.02804421e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 100000.0]
Fitted coefficients: [0.06459483 0.02257981 0.74257179 0.17025357]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 1562.0]
Fitted coefficients: [0.19917322 0.00160569 0.32665309 0.472568  ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 25000.0]
Fitted coefficients: [1.44765864e-01 1.00000000e-10 4.73203086e-01 3.82031049e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 391.0]
Fitted coefficients: [0.19454129 0.01896208 0.21866819 0.56782843]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 50000.0]
Fitted coefficients: [1.25320774e-01 1.00000000e-10 5.50135237e-01 3.24543989e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 6250.0]
Fitted coefficients: [1.51825094e-01 1.00001350e-10 4.48780089e-01 3.99394816e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0, 781.0]
Fitted coefficients: [0.20319115 0.00696851 0.26977965 0.52006069]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 100000.0]
Fitted coefficients: [1.00001141e-10 3.91128997e-01 5.02028517e-01 1.06842486e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 1562.0]
Fitted coefficients: [2.83936134e-10 5.35140491e-01 1.09497629e-01 3.55361880e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 4.28721846e-01 2.74019885e-01 2.97258269e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 391.0]
Fitted coefficients: [1.00000000e-10 5.87187225e-01 3.21727412e-02 3.80640034e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 50000.0]
Fitted coefficients: [1.00000000e-10 3.83468264e-01 3.48255689e-01 2.68276047e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 6250.0]
Fitted coefficients: [1.00000004e-10 4.51081446e-01 2.24260147e-01 3.24658407e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0, 781.0]
Fitted coefficients: [9.01712930e-10 5.12575506e-01 1.04362295e-01 3.83062196e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 100000.0]
Fitted coefficients: [0.04556638 0.16776548 0.6408995  0.14576864]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 1562.0]
Fitted coefficients: [0.16103537 0.2049615  0.26953379 0.36446934]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 25000.0]
Fitted coefficients: [0.11671066 0.13514987 0.46528904 0.28285043]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 391.0]
Fitted coefficients: [0.15187163 0.24690274 0.18660296 0.41462266]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 50000.0]
Fitted coefficients: [0.10990741 0.14556178 0.4945341  0.24999671]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 6250.0]
Fitted coefficients: [0.11482617 0.19754481 0.35979169 0.32783733]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0, 781.0]
Fitted coefficients: [0.15575446 0.21305561 0.25794419 0.37324574]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.0373057  0.04053693 0.72287472 0.19928264]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 1562.0]
Fitted coefficients: [0.17388708 0.01490153 0.34188757 0.46932382]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 25000.0]
Fitted coefficients: [0.12624459 0.01403507 0.49493485 0.36478549]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 391.0]
Fitted coefficients: [0.17931302 0.04531764 0.21171477 0.56365457]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 50000.0]
Fitted coefficients: [0.11797219 0.0158173  0.53680999 0.32940052]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 6250.0]
Fitted coefficients: [0.15467195 0.02023829 0.41175331 0.41333645]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVA2'], Conc=[781.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0, 781.0]
Fitted coefficients: [0.18433823 0.03314416 0.24503917 0.53747844]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 100000.0]
Fitted coefficients: [0.43832086 0.30980431 0.21720293 0.0346719 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 25000.0]
Fitted coefficients: [0.41430523 0.37755584 0.13144068 0.07669825]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 3125.0]
Fitted coefficients: [0.48256287 0.32219148 0.07645947 0.11878617]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 391.0]
Fitted coefficients: [0.45123684 0.38629221 0.01135203 0.15111892]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 50000.0]
Fitted coefficients: [0.42865394 0.3590565  0.14468373 0.06760583]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 6250.0]
Fitted coefficients: [0.41622905 0.37853647 0.10368787 0.10154662]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0, 781.0]
Fitted coefficients: [0.47081565 0.38206112 0.02308995 0.12403328]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 100000.0]
Fitted coefficients: [0.46980432 0.04447032 0.34911937 0.13660598]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 25000.0]
Fitted coefficients: [0.56567404 0.03967757 0.23455522 0.16009317]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 3125.0]
Fitted coefficients: [0.57807776 0.04713772 0.15388749 0.22089703]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 391.0]
Fitted coefficients: [0.66028532 0.04446656 0.08009674 0.21515138]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 50000.0]
Fitted coefficients: [0.51353908 0.03263721 0.28472163 0.16910208]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 6250.0]
Fitted coefficients: [0.57078372 0.03947178 0.18247354 0.20727097]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0, 781.0]
Fitted coefficients: [0.67580436 0.04721703 0.0893492  0.1876294 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0, 100000.0]
Fitted coefficients: [5.82070492e-01 1.00000000e-10 3.29715007e-01 8.82145013e-02]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0, 25000.0]
Fitted coefficients: [6.41984311e-01 1.00046421e-10 2.25740051e-01 1.32275638e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0, 3125.0]
Fitted coefficients: [6.36976724e-01 5.16144526e-10 1.63379840e-01 1.99643436e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0, 391.0]
Fitted coefficients: [7.39716516e-01 1.00001461e-10 6.73879584e-02 1.92895526e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0, 50000.0]
Fitted coefficients: [5.41655887e-01 1.22319263e-09 3.10137574e-01 1.48206537e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0, 6250.0]
Fitted coefficients: [6.85506530e-01 1.00002317e-10 1.54034566e-01 1.60458904e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0, 781.0]
Fitted coefficients: [7.45734538e-01 1.00000000e-10 9.96778432e-02 1.54587619e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 100000.0]
Fitted coefficients: [0.35774857 0.29405827 0.20912266 0.1390705 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 25000.0]
Fitted coefficients: [0.4046764  0.26354891 0.15237032 0.17940438]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 3125.0]
Fitted coefficients: [0.51150798 0.27236556 0.03180945 0.18431701]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 391.0]
Fitted coefficients: [0.49286123 0.28298843 0.00239271 0.22175762]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 50000.0]
Fitted coefficients: [0.44242792 0.25847316 0.1278664  0.17123252]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 6250.0]
Fitted coefficients: [0.47472021 0.27339688 0.06793372 0.18394919]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0, 781.0]
Fitted coefficients: [0.45183551 0.31545483 0.02014274 0.21256692]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Fitted coefficients: [0.59104885 0.00805798 0.30524784 0.09564532]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 25000.0]
Fitted coefficients: [0.57002239 0.00179239 0.26531438 0.16287084]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 3125.0]
Fitted coefficients: [6.37655940e-01 1.00000000e-10 1.55897542e-01 2.06446518e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 391.0]
Fitted coefficients: [0.7229174  0.02093341 0.06425884 0.19189036]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 50000.0]
Fitted coefficients: [0.53649345 0.00205496 0.30971951 0.15173207]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 6250.0]
Fitted coefficients: [0.64513501 0.00117508 0.17629769 0.17739223]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0, 781.0]
Fitted coefficients: [0.68959767 0.00803649 0.10976315 0.19260269]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 100000.0]
Fitted coefficients: [0.37744967 0.30755344 0.20333987 0.11165702]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 25000.0]
Fitted coefficients: [0.37078495 0.32457954 0.14591359 0.15872192]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 3125.0]
Fitted coefficients: [0.42197714 0.35084231 0.0393759  0.18780465]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 391.0]
Fitted coefficients: [4.39100195e-01 3.48952233e-01 1.00000357e-10 2.11947573e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 50000.0]
Fitted coefficients: [0.42088428 0.31198975 0.12901466 0.13811131]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 6250.0]
Fitted coefficients: [0.48796108 0.29708109 0.06455375 0.15040408]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0, 781.0]
Fitted coefficients: [0.4633529  0.33656097 0.00841729 0.19166884]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 100000.0]
Fitted coefficients: [0.44607165 0.12639599 0.35345411 0.07407825]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 25000.0]
Fitted coefficients: [0.53993807 0.12862185 0.22660296 0.10483713]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 3125.0]
Fitted coefficients: [0.5579778  0.1350438  0.15976483 0.14721357]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 391.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.59424024 0.16807245 0.08315678 0.15453053]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 50000.0]
Fitted coefficients: [0.46706628 0.13518918 0.28228797 0.11545657]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 6250.0]
Fitted coefficients: [0.55449626 0.1333875  0.18900494 0.1231113 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0, 781.0]
Fitted coefficients: [0.59258974 0.15199191 0.12061371 0.13480464]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 100000.0]
Fitted coefficients: [0.55974266 0.0190615  0.30742951 0.11376633]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 25000.0]
Fitted coefficients: [0.58677536 0.0110258  0.25082468 0.15137416]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 3125.0]
Fitted coefficients: [0.6250639  0.02077205 0.14067033 0.21349373]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 391.0]
Fitted coefficients: [0.7011737  0.03968016 0.06692434 0.1922218 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 50000.0]
Fitted coefficients: [0.47759501 0.02969778 0.30784525 0.18486195]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 6250.0]
Fitted coefficients: [0.57308076 0.01810015 0.20935165 0.19946745]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[100000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0, 781.0]
Fitted coefficients: [0.61886551 0.04405285 0.09710982 0.23997182]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 100000.0]
Fitted coefficients: [0.09250034 0.50172838 0.35547747 0.05029381]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 25000.0]
Fitted coefficients: [0.12242524 0.55903438 0.22610526 0.09243512]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 3125.0]
Fitted coefficients: [0.15057521 0.56136076 0.13753937 0.15052466]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 391.0]
Fitted coefficients: [0.16163943 0.60717672 0.04204195 0.18914191]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 50000.0]
Fitted coefficients: [0.11219722 0.53881159 0.26504385 0.08394734]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 6250.0]
Fitted coefficients: [0.18463941 0.5317501  0.16855965 0.11505084]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0, 781.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.1286995  0.6564905  0.06570297 0.14910702]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 100000.0]
Fitted coefficients: [0.10628518 0.08371963 0.59705434 0.21294086]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 25000.0]
Fitted coefficients: [0.17041123 0.09277584 0.43568156 0.30113137]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 3125.0]
Fitted coefficients: [0.20938719 0.09130369 0.29746748 0.40184164]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 391.0]
Fitted coefficients: [0.27610758 0.1484953  0.1540493  0.42134782]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 50000.0]
Fitted coefficients: [0.15576504 0.0883798  0.46522681 0.29062835]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 6250.0]
Fitted coefficients: [0.23247862 0.08026256 0.33855732 0.3487015 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0, 781.0]
Fitted coefficients: [0.243934   0.13058948 0.20875478 0.41672174]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0, 100000.0]
Fitted coefficients: [0.14289998 0.00316609 0.65792599 0.19600794]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0, 25000.0]
Fitted coefficients: [2.50985293e-01 1.00010399e-10 4.75494904e-01 2.73519802e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0, 3125.0]
Fitted coefficients: [3.26676976e-01 1.00000105e-10 2.94411654e-01 3.78911369e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0, 391.0]
Fitted coefficients: [0.47199144 0.04855312 0.13895251 0.34050293]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0, 50000.0]
Fitted coefficients: [2.33161010e-01 1.00000003e-10 5.25171356e-01 2.41667634e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0, 6250.0]
Fitted coefficients: [3.28849913e-01 1.00000000e-10 3.63184669e-01 3.07965417e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0, 781.0]
Fitted coefficients: [0.39149962 0.0261634  0.20724934 0.37508764]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 100000.0]
Fitted coefficients: [1.00000017e-10 4.39940913e-01 3.57071996e-01 2.02987091e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 25000.0]
Fitted coefficients: [0.01861855 0.48406782 0.21129757 0.28601606]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 3125.0]
Fitted coefficients: [0.04740485 0.53175315 0.06423496 0.35660704]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 391.0]
Fitted coefficients: [2.29724986e-02 6.09662630e-01 1.00000000e-10 3.67364871e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 50000.0]
Fitted coefficients: [0.02008734 0.44261622 0.26942171 0.26787473]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 6250.0]
Fitted coefficients: [0.07022253 0.42471338 0.183473   0.32159109]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0, 781.0]
Fitted coefficients: [0.04476114 0.5699982  0.00953558 0.37570508]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 100000.0]
Fitted coefficients: [0.21288998 0.04551501 0.57412752 0.16746749]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 25000.0]
Fitted coefficients: [0.21385492 0.01896748 0.49837159 0.26880601]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 3125.0]
Fitted coefficients: [0.3290012  0.03781144 0.28870898 0.34447838]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 391.0]
Fitted coefficients: [0.29953944 0.09049682 0.16037276 0.44959098]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 50000.0]
Fitted coefficients: [0.20817553 0.04012336 0.4807658  0.2709353 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 6250.0]
Fitted coefficients: [0.27947864 0.03292532 0.36023466 0.32736139]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0, 781.0]
Fitted coefficients: [0.3247631  0.07275528 0.21726664 0.38521498]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 100000.0]
Fitted coefficients: [0.04028829 0.51639454 0.26269672 0.18062045]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 25000.0]
Fitted coefficients: [0.0331381  0.55550159 0.16585635 0.24550395]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 3125.0]
Fitted coefficients: [0.04491939 0.55681798 0.08902962 0.309233  ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 391.0]
Fitted coefficients: [1.84919827e-02 6.33986506e-01 1.00111166e-10 3.47521511e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 50000.0]
Fitted coefficients: [0.02199329 0.50155573 0.2455919  0.23085908]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 6250.0]
Fitted coefficients: [0.07948967 0.51320567 0.13071405 0.27659062]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0, 781.0]
Fitted coefficients: [0.10430266 0.54568631 0.04185479 0.30815625]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 100000.0]
Fitted coefficients: [0.07927854 0.23080698 0.5608337  0.12908078]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 25000.0]
Fitted coefficients: [0.14015613 0.19242453 0.45950353 0.20791582]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 3125.0]
Fitted coefficients: [0.12820373 0.26284325 0.32794178 0.28101124]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 391.0]
Fitted coefficients: [0.23833356 0.30705437 0.18290417 0.27170789]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 50000.0]
Fitted coefficients: [0.13819613 0.23715565 0.4457298  0.17891843]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 6250.0]
Fitted coefficients: [0.17293993 0.22635319 0.36738308 0.2333238 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0, 781.0]
Fitted coefficients: [0.22424509 0.30087538 0.23518358 0.23969595]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 100000.0]
Fitted coefficients: [0.09937359 0.0602429  0.64322154 0.19716197]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 25000.0]
Fitted coefficients: [0.17749192 0.06285607 0.45676851 0.30288351]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 3125.0]
Fitted coefficients: [0.26727851 0.08282187 0.26654645 0.38335317]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 391.0]
Fitted coefficients: [0.30475233 0.1115718  0.14567533 0.43800054]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 50000.0]
Fitted coefficients: [0.17354938 0.04833004 0.50012225 0.27799833]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 6250.0]
Fitted coefficients: [0.21202003 0.04958259 0.37854377 0.35985361]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[1562.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0, 781.0]
Fitted coefficients: [0.28934079 0.08770284 0.2195922  0.40336418]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 100000.0]
Fitted coefficients: [0.29635289 0.41461128 0.28476461 0.00427122]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 25000.0]
Fitted coefficients: [0.33133347 0.43344327 0.18458049 0.05064278]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 3125.0]
Fitted coefficients: [0.3779935  0.42563687 0.10600052 0.09036911]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 391.0]
Fitted coefficients: [0.2858545  0.56606461 0.02834563 0.11973526]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 50000.0]
Fitted coefficients: [0.30102397 0.41971539 0.23072647 0.04853418]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 6250.0]
Fitted coefficients: [0.39874529 0.38848004 0.15225933 0.06051533]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0, 781.0]
Fitted coefficients: [0.3719895  0.45598381 0.07982953 0.09219716]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 100000.0]
Fitted coefficients: [0.38050124 0.06307913 0.4320342  0.12438543]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 25000.0]
Fitted coefficients: [0.44236413 0.08484652 0.29251248 0.18027687]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 3125.0]
Fitted coefficients: [0.48036536 0.09507293 0.19534157 0.22922014]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 391.0]
Fitted coefficients: [0.5411768  0.11428345 0.11320333 0.23133642]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 50000.0]
Fitted coefficients: [0.46451907 0.07849212 0.29717595 0.15981286]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 6250.0]
Fitted coefficients: [0.49219312 0.08127217 0.22715002 0.19938469]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0, 781.0]
Fitted coefficients: [0.55065742 0.08326819 0.15130658 0.21476781]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0, 100000.0]
Fitted coefficients: [0.49150388 0.03170719 0.39946123 0.0773277 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0, 25000.0]
Fitted coefficients: [0.51795752 0.01532356 0.31575405 0.15096486]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0, 3125.0]
Fitted coefficients: [0.54509869 0.0181239  0.21409942 0.22267799]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0, 391.0]
Fitted coefficients: [0.68636849 0.04547197 0.11879084 0.1493687 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0, 50000.0]
Fitted coefficients: [0.4742254  0.01466901 0.37759692 0.13350867]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0, 6250.0]
Fitted coefficients: [0.62678649 0.02683422 0.1966946  0.14968469]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0, 781.0]
Fitted coefficients: [0.65951837 0.03954081 0.14610452 0.1548363 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 100000.0]
Fitted coefficients: [0.2399296  0.36298275 0.2629018  0.13418585]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 25000.0]
Fitted coefficients: [0.30850344 0.34794087 0.15841873 0.18513696]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 3125.0]
Fitted coefficients: [0.35595936 0.38538454 0.04586747 0.21278863]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 391.0]
Fitted coefficients: [0.41693645 0.3439     0.01667918 0.22248436]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 50000.0]
Fitted coefficients: [0.29304077 0.35204912 0.18790081 0.1670093 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 6250.0]
Fitted coefficients: [0.33688055 0.37146097 0.08039267 0.21126581]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0, 781.0]
Fitted coefficients: [0.29589799 0.42867235 0.02709395 0.2483357 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 100000.0]
Fitted coefficients: [0.43704451 0.04655112 0.43052214 0.08588222]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 25000.0]
Fitted coefficients: [0.51700915 0.03717625 0.3091994  0.13661521]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 3125.0]
Fitted coefficients: [0.47345127 0.04024559 0.23135548 0.25494766]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 391.0]
Fitted coefficients: [0.6544676  0.07851763 0.11425488 0.15275988]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 50000.0]
Fitted coefficients: [0.49996302 0.03634722 0.33238435 0.13130541]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 6250.0]
Fitted coefficients: [0.56127996 0.03641553 0.22961557 0.17268893]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0, 781.0]
Fitted coefficients: [0.62223276 0.06206598 0.1331569  0.18254436]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 100000.0]
Fitted coefficients: [0.29025229 0.35753871 0.24903815 0.10317085]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 25000.0]
Fitted coefficients: [0.28489392 0.40521652 0.13698173 0.17290783]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 3125.0]
Fitted coefficients: [0.31481102 0.42753836 0.05942939 0.19822123]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 391.0]
Fitted coefficients: [3.71352140e-01 4.30860408e-01 1.00000007e-10 1.97787452e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 50000.0]
Fitted coefficients: [0.32027928 0.33407998 0.20219666 0.14344409]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 6250.0]
Fitted coefficients: [0.34303971 0.41446334 0.06981229 0.17268466]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0, 781.0]
Fitted coefficients: [0.36288039 0.42351273 0.02350576 0.19010112]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 100000.0]
Fitted coefficients: [0.3486112  0.18858004 0.39617211 0.06663665]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 25000.0]
Fitted coefficients: [0.36358336 0.18179382 0.33020514 0.12441768]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 3125.0]
Fitted coefficients: [0.43880167 0.20658797 0.21112104 0.14348933]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 391.0]
Fitted coefficients: [0.45022772 0.23986171 0.13044621 0.17946436]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 50000.0]
Fitted coefficients: [0.39378339 0.15955646 0.34160685 0.1050533 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 6250.0]
Fitted coefficients: [0.47381069 0.15831067 0.24927773 0.11860091]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0, 781.0]
Fitted coefficients: [0.47858875 0.22533652 0.16218742 0.13388731]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 100000.0]
Fitted coefficients: [0.4034665  0.06393602 0.41287992 0.11971757]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 25000.0]
Fitted coefficients: [0.4343634  0.05260338 0.35203763 0.1609956 ]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 3125.0]
Fitted coefficients: [0.54121557 0.06239092 0.18958318 0.20681033]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 391.0]
Fitted coefficients: [0.56179093 0.09005093 0.10581605 0.24234209]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 50000.0]
Fitted coefficients: [0.41021157 0.03889058 0.40379115 0.14710669]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 6250.0]
Fitted coefficients: [0.5503012  0.07200926 0.21926143 0.15842812]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[25000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0, 781.0]
Fitted coefficients: [0.53292889 0.08915102 0.15410898 0.22381111]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 100000.0]
Fitted coefficients: [1.00770680e-10 5.68723314e-01 2.96638628e-01 1.34638058e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 25000.0]
Fitted coefficients: [1.00020968e-10 5.98481227e-01 2.22511941e-01 1.79006832e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 3125.0]
Fitted coefficients: [1.00036145e-10 6.42221939e-01 1.01916958e-01 2.55861103e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 391.0]
Fitted coefficients: [1.00043563e-10 7.03079346e-01 2.64158930e-04 2.96656495e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 50000.0]
Fitted coefficients: [1.00582911e-10 5.14902940e-01 3.06776285e-01 1.78320775e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 6250.0]
Fitted coefficients: [0.00668419 0.56105031 0.18255172 0.24971377]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0, 781.0]
Fitted coefficients: [1.00000000e-10 6.79821070e-01 5.19813189e-02 2.68197611e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 100000.0]
Fitted coefficients: [1.00380122e-10 4.32518887e-02 6.18042087e-01 3.38706024e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 25000.0]
Fitted coefficients: [1.00000000e-10 6.48328624e-02 4.87402885e-01 4.47764253e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 3125.0]
Fitted coefficients: [1.00000000e-10 6.34021678e-02 3.04168181e-01 6.32429651e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 391.0]
Fitted coefficients: [1.00000004e-10 1.26978032e-01 1.37632521e-01 7.35389447e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 50000.0]
Fitted coefficients: [1.00000000e-10 5.61884771e-02 5.21812592e-01 4.21998931e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 6250.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [1.00000000e-10 7.64677903e-02 3.79495104e-01 5.44037106e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0, 781.0]
Fitted coefficients: [1.00631882e-10 9.15937604e-02 2.22358679e-01 6.86047560e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0, 100000.0]
Fitted coefficients: [1.01076098e-10 1.85961889e-09 6.95513743e-01 3.04486256e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0, 25000.0]
Fitted coefficients: [1.00000000e-10 1.00000000e-10 5.41899283e-01 4.58100717e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0, 3125.0]
Fitted coefficients: [1.00000000e-10 1.18286358e-10 3.68758285e-01 6.31241712e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0, 391.0]
Fitted coefficients: [5.03701354e-02 2.95096762e-04 1.42123867e-01 8.07210901e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0, 50000.0]
Fitted coefficients: [1.00000005e-10 2.07121050e-09 5.62701100e-01 4.37298897e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0, 6250.0]
Fitted coefficients: [1.58267160e-02 1.02059200e-10 4.54558409e-01 5.29614875e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0, 781.0]
Fitted coefficients: [1.00000000e-10 1.01236266e-10 2.41341563e-01 7.58658437e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 100000.0]
Fitted coefficients: [5.57833616e-10 4.59246946e-01 2.50902262e-01 2.89850792e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 25000.0]
Fitted coefficients: [1.00044944e-10 4.19282551e-01 2.15285828e-01 3.65431622e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 3125.0]
Fitted coefficients: [1.00000000e-10 4.81999448e-01 3.95782143e-02 4.78422337e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 391.0]
Fitted coefficients: [1.00000000e-10 5.61535066e-01 1.00000000e-10 4.38464934e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 50000.0]
Fitted coefficients: [1.00003409e-10 4.28405376e-01 2.15816278e-01 3.55778346e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 6250.0]
Fitted coefficients: [1.00169559e-10 4.83268106e-01 1.18541961e-01 3.98189933e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0, 781.0]
Fitted coefficients: [1.00000000e-10 5.27895893e-01 1.00000000e-10 4.72104107e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 100000.0]
Fitted coefficients: [1.01060576e-10 8.43483496e-03 6.51264610e-01 3.40300555e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 25000.0]
Fitted coefficients: [1.00000099e-10 1.40288981e-02 5.32410892e-01 4.53560208e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 3125.0]
Fitted coefficients: [1.00022866e-10 9.93142234e-03 3.27717807e-01 6.62350770e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 391.0]
Fitted coefficients: [1.00026003e-10 5.63202559e-02 1.37579847e-01 8.06099897e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 50000.0]
Fitted coefficients: [1.00000000e-10 5.20382856e-03 5.82682128e-01 4.12114043e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 6250.0]
Fitted coefficients: [0.01038721 0.01486894 0.39438264 0.58036121]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0, 781.0]
Fitted coefficients: [1.00000000e-10 2.37838837e-02 2.09059073e-01 7.67157043e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 4.82579224e-01 2.73653496e-01 2.43767280e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 25000.0]
Fitted coefficients: [1.09573678e-10 5.00935565e-01 1.66896594e-01 3.32167841e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 3125.0]
Fitted coefficients: [1.06065781e-10 5.29288315e-01 5.51663395e-02 4.15545345e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 391.0]
Fitted coefficients: [1.34266268e-10 6.01029654e-01 1.09583441e-10 3.98970346e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 50000.0]
Fitted coefficients: [2.35763624e-09 4.83263252e-01 2.05184193e-01 3.11552555e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 6250.0]
Fitted coefficients: [1.00000000e-10 6.02861634e-01 6.46743045e-02 3.32464062e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0, 781.0]
Fitted coefficients: [1.00629787e-10 5.42702797e-01 4.50267772e-03 4.52794525e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 100000.0]
Fitted coefficients: [1.01096169e-10 1.92515253e-01 5.82949063e-01 2.24535684e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 25000.0]
Fitted coefficients: [1.16530583e-10 2.27056960e-01 4.57432587e-01 3.15510455e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 3125.0]
Fitted coefficients: [1.00027192e-10 2.70561230e-01 3.05010135e-01 4.24428635e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 391.0]
Fitted coefficients: [1.00000056e-10 3.33688344e-01 1.84613259e-01 4.81698396e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 50000.0]
Fitted coefficients: [1.45781057e-10 2.24082105e-01 4.80278399e-01 2.95639498e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 6250.0]
Fitted coefficients: [0.00597893 0.21126391 0.38029853 0.40245863]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0, 781.0]
Fitted coefficients: [1.00000000e-10 2.95236345e-01 2.45692337e-01 4.59071318e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 100000.0]
Fitted coefficients: [1.00000000e-10 3.58962328e-02 6.15904232e-01 3.48199535e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 25000.0]
Fitted coefficients: [1.00000000e-10 3.95307982e-02 4.87640814e-01 4.72828388e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 3125.0]
Fitted coefficients: [1.00000000e-10 4.61339674e-02 3.08321142e-01 6.45544890e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 391.0]
Fitted coefficients: [1.00000000e-10 8.73098128e-02 1.26218039e-01 7.86472148e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 50000.0]
Fitted coefficients: [1.00218435e-10 2.90062808e-02 5.22316444e-01 4.48677275e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 6250.0]
Fitted coefficients: [0.01435976 0.03327579 0.42321703 0.52914742]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[391.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0, 781.0]
Fitted coefficients: [1.00631948e-10 5.77915833e-02 2.04615282e-01 7.37593135e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 100000.0]
Fitted coefficients: [3.99015930e-01 3.70791789e-01 2.30192281e-01 1.00001206e-10]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 25000.0]
Fitted coefficients: [0.41550823 0.41410816 0.14573727 0.02464633]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 3125.0]
Fitted coefficients: [0.44547448 0.43202193 0.06491418 0.05758941]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 391.0]
Fitted coefficients: [0.4175364  0.47520356 0.01721717 0.09004286]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 50000.0]
Fitted coefficients: [0.37157036 0.43909863 0.1582861  0.03104491]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 6250.0]
Fitted coefficients: [0.41408413 0.41842151 0.12500249 0.04249188]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0, 781.0]
Fitted coefficients: [0.46054363 0.41808143 0.04928213 0.07209281]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 100000.0]
Fitted coefficients: [0.48262319 0.07749799 0.33203514 0.10784368]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 25000.0]
Fitted coefficients: [0.45994422 0.07753176 0.29468056 0.16784346]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 3125.0]
Fitted coefficients: [0.61672318 0.08220061 0.13299109 0.16808512]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 391.0]
Fitted coefficients: [0.67368019 0.10286052 0.06439206 0.15906723]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 50000.0]
Fitted coefficients: [0.576289   0.07578735 0.23649959 0.11142408]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 6250.0]
Fitted coefficients: [0.59930909 0.07869918 0.16805433 0.1539374 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0, 781.0]
Fitted coefficients: [0.6280864  0.0950365  0.10377826 0.17309884]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0, 100000.0]
Fitted coefficients: [0.51616013 0.01920088 0.40147113 0.06316786]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0, 25000.0]
Fitted coefficients: [0.58565676 0.00953561 0.28772868 0.11707895]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0, 3125.0]
Fitted coefficients: [0.65815865 0.0167097  0.14367325 0.18145841]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0, 391.0]
Fitted coefficients: [0.76210715 0.04488    0.04893075 0.14408211]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0, 50000.0]
Fitted coefficients: [0.57309251 0.01285211 0.3079398  0.10611558]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0, 6250.0]
Fitted coefficients: [0.68618164 0.01634994 0.16651379 0.13095463]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0, 781.0]
Fitted coefficients: [0.76577168 0.04007192 0.07345017 0.12070623]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 100000.0]
Fitted coefficients: [0.29952272 0.32045673 0.26955761 0.11046294]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 25000.0]
Fitted coefficients: [0.4282199  0.32364739 0.11439541 0.1337373 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 3125.0]
Fitted coefficients: [0.35875402 0.37631188 0.03883747 0.22609663]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 391.0]
Fitted coefficients: [4.43042903e-01 3.63657945e-01 1.00439001e-10 1.93299151e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 50000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.40363712 0.3025769  0.16928176 0.12450422]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 6250.0]
Fitted coefficients: [0.42221222 0.32524569 0.07330664 0.17923546]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0, 781.0]
Fitted coefficients: [0.46801105 0.33584199 0.01410892 0.18203804]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 100000.0]
Fitted coefficients: [0.53099258 0.04407038 0.35806029 0.06687675]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 25000.0]
Fitted coefficients: [0.62525967 0.03922127 0.23481884 0.10070021]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 3125.0]
Fitted coefficients: [0.61484031 0.04190586 0.15067509 0.19257875]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 391.0]
Fitted coefficients: [0.72418711 0.07018843 0.06952716 0.1360973 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 50000.0]
Fitted coefficients: [0.5662189  0.0371739  0.29388964 0.10271756]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 6250.0]
Fitted coefficients: [0.65840481 0.03177664 0.18808196 0.12173659]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0, 781.0]
Fitted coefficients: [0.70775578 0.06108556 0.09164897 0.13950969]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 100000.0]
Fitted coefficients: [0.34456616 0.33920408 0.235773   0.08045675]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 25000.0]
Fitted coefficients: [0.37814161 0.40790997 0.08925294 0.12469548]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 3125.0]
Fitted coefficients: [0.38535328 0.41792093 0.02327945 0.17344634]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 391.0]
Fitted coefficients: [3.07206733e-01 4.86037403e-01 1.00096824e-10 2.06755864e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 50000.0]
Fitted coefficients: [0.44546565 0.34590246 0.11337546 0.09525643]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 6250.0]
Fitted coefficients: [0.37211633 0.39507257 0.06169709 0.17111401]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0, 781.0]
Fitted coefficients: [4.34721783e-01 3.99891267e-01 5.93833760e-10 1.65386956e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 100000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.39968688 0.18710988 0.37202261 0.04118064]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 25000.0]
Fitted coefficients: [0.44914395 0.16149589 0.27572382 0.11363634]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 3125.0]
Fitted coefficients: [0.50495045 0.18026163 0.17651239 0.13827553]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 391.0]
Fitted coefficients: [0.60047514 0.21268591 0.08311178 0.10372717]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 50000.0]
Fitted coefficients: [0.47998834 0.14952154 0.28621129 0.08427883]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 6250.0]
Fitted coefficients: [0.50671224 0.19047117 0.2000126  0.10280399]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0, 781.0]
Fitted coefficients: [0.55582993 0.19107474 0.12688887 0.12620646]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 100000.0]
Fitted coefficients: [0.49002186 0.05102525 0.38722716 0.07172573]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 25000.0]
Fitted coefficients: [0.50613466 0.04765188 0.29997064 0.14624282]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 3125.0]
Fitted coefficients: [0.65229336 0.0615347  0.1321105  0.15406143]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 391.0]
Fitted coefficients: [0.67905559 0.08406695 0.06004152 0.17683594]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 50000.0]
Fitted coefficients: [0.54576866 0.05729411 0.27774475 0.11919249]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 6250.0]
Fitted coefficients: [0.57081144 0.04005623 0.21515391 0.17397842]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[50000.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0, 781.0]
Fitted coefficients: [0.62172566 0.07160088 0.11198138 0.19469209]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 100000.0]
Fitted coefficients: [0.18585932 0.47049043 0.32237885 0.02127139]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 25000.0]
Fitted coefficients: [0.24840677 0.44608807 0.2325112  0.07299396]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 3125.0]
Fitted coefficients: [0.23449845 0.54519424 0.11350814 0.10679917]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 391.0]
Fitted coefficients: [0.22337564 0.55879405 0.06598289 0.15184742]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 50000.0]
Fitted coefficients: [0.20649046 0.44723066 0.271875   0.07440388]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 6250.0]
Fitted coefficients: [0.24489519 0.53830034 0.14830503 0.06849943]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0, 781.0]
Fitted coefficients: [0.27415599 0.51298249 0.09861214 0.11424938]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 100000.0]
Fitted coefficients: [0.22722549 0.07977515 0.53854906 0.15445031]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 25000.0]
Fitted coefficients: [0.26815392 0.083418   0.40257765 0.24585043]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 3125.0]
Fitted coefficients: [0.33597422 0.07429383 0.27962852 0.31010343]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 391.0]
Fitted coefficients: [0.2985127  0.15480889 0.17860467 0.36807373]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 50000.0]
Fitted coefficients: [0.24618142 0.08635917 0.44540794 0.22205146]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 6250.0]
Fitted coefficients: [0.30618439 0.07964331 0.33401452 0.28015778]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0, 781.0]
Fitted coefficients: [0.37390774 0.12865344 0.20311665 0.29432217]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0, 100000.0]
Fitted coefficients: [0.34234    0.02933843 0.51460874 0.11371283]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0, 25000.0]
Fitted coefficients: [0.37026695 0.01507596 0.41751147 0.19714562]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0, 3125.0]
Fitted coefficients: [0.37611805 0.01398406 0.28959504 0.32030285]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0, 391.0]
Fitted coefficients: [0.52403221 0.06062142 0.17145942 0.24388695]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0, 50000.0]
Fitted coefficients: [0.31747894 0.0107942  0.47657986 0.19514701]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0, 6250.0]
Fitted coefficients: [0.44145469 0.01699654 0.31549138 0.2260574 ]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0, 781.0]
Fitted coefficients: [0.51600488 0.04780612 0.22613042 0.21005859]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 100000.0]
Fitted coefficients: [0.11398154 0.44487426 0.27062172 0.17052248]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 25000.0]
Fitted coefficients: [0.14058445 0.39866594 0.21774203 0.24300758]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 3125.0]
Fitted coefficients: [0.15202159 0.49119431 0.06894835 0.28783574]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 391.0]
Fitted coefficients: [0.16901244 0.49509471 0.012217   0.32367585]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 50000.0]
Fitted coefficients: [0.13314266 0.4167998  0.2303398  0.21971774]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 6250.0]
Fitted coefficients: [0.21498104 0.41702389 0.12673407 0.24126101]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0, 781.0]
Fitted coefficients: [0.2147213 0.4557645 0.0539887 0.2755255]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 100000.0]
Fitted coefficients: [0.25181071 0.043048   0.5768388  0.12830249]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 25000.0]
Fitted coefficients: [0.32134274 0.04000027 0.42226609 0.2163909 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 3125.0]
Fitted coefficients: [0.41121003 0.05472516 0.26544715 0.26861765]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 391.0]
Fitted coefficients: [0.46716267 0.09324317 0.17041287 0.26918129]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 50000.0]
Fitted coefficients: [0.27070492 0.03321664 0.48049231 0.21558613]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 6250.0]
Fitted coefficients: [0.34250521 0.03626053 0.36170071 0.25953355]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0, 781.0]
Fitted coefficients: [0.42940144 0.07713056 0.21896425 0.27450375]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 100000.0]
Fitted coefficients: [0.12685575 0.40529167 0.32692159 0.14093099]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 25000.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.12032545 0.51729271 0.14126854 0.2211133 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 3125.0]
Fitted coefficients: [0.19075756 0.4731207  0.09344279 0.24267895]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 391.0]
Fitted coefficients: [0.15752835 0.54148392 0.00602126 0.29496647]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 50000.0]
Fitted coefficients: [0.10448947 0.47030082 0.22614871 0.19906101]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 6250.0]
Fitted coefficients: [0.18783584 0.47309957 0.13100969 0.2080549 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0, 781.0]
Fitted coefficients: [0.138505   0.54557223 0.0396006  0.27632216]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 100000.0]
Fitted coefficients: [0.20464908 0.1959808  0.49778207 0.10158806]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 25000.0]
Fitted coefficients: [0.31325373 0.19573072 0.36987325 0.1211423 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 3125.0]
Fitted coefficients: [0.31577368 0.21417895 0.2679129  0.20213448]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 391.0]
Fitted coefficients: [0.3827031  0.27693371 0.17341108 0.16695211]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 50000.0]
Fitted coefficients: [0.25910351 0.16894519 0.44040762 0.13154368]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 6250.0]
Fitted coefficients: [0.30988243 0.2176809  0.31011972 0.16231695]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0, 781.0]
Fitted coefficients: [0.33741618 0.25874089 0.22198093 0.181862  ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 100000.0]
Fitted coefficients: [0.26720091 0.07477098 0.51942902 0.13859909]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 25000.0]
Fitted coefficients: [0.25719531 0.04829443 0.4420796  0.25243066]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 3125.0]
Fitted coefficients: [0.40748341 0.07999582 0.26460021 0.24792057]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 391.0]
Fitted coefficients: [0.40825568 0.11225003 0.16036272 0.31913157]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 50000.0]
Fitted coefficients: [0.2399827  0.0464346  0.49218445 0.22139826]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 6250.0]
Fitted coefficients: [0.36341075 0.04991749 0.34483259 0.24183917]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[6250.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0, 781.0]
Fitted coefficients: [0.39556358 0.10122574 0.21327949 0.28993118]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 100000.0]
Fitted coefficients: [0.01368959 0.55750487 0.31571096 0.11309458]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 25000.0]
Fitted coefficients: [0.05427765 0.58128869 0.20566219 0.15877147]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 3125.0]
Fitted coefficients: [0.05100971 0.59981105 0.11764109 0.23153815]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 391.0]
Fitted coefficients: [0.05890227 0.67262134 0.02451598 0.24396041]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 50000.0]
Fitted coefficients: [0.04885183 0.53215968 0.26841168 0.15057681]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 6250.0]
Fitted coefficients: [0.08127267 0.56481294 0.1593111  0.19460329]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0, 781.0]
Fitted coefficients: [0.0598711  0.67350355 0.05795012 0.20867524]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 100000.0]
Fitted coefficients: [0.01847939 0.08691047 0.60388362 0.29072652]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 25000.0]
Fitted coefficients: [0.06255543 0.07041176 0.4556335  0.41139932]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 3125.0]
Fitted coefficients: [0.05267956 0.08697305 0.30156133 0.55878606]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 391.0]
Fitted coefficients: [0.10755788 0.13059856 0.14508667 0.61675689]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 50000.0]
Fitted coefficients: [0.06047133 0.06378617 0.49307423 0.38266827]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 6250.0]
Fitted coefficients: [0.10861526 0.0698482  0.33358471 0.48795182]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0, 781.0]
Fitted coefficients: [0.04980469 0.12858463 0.2325918  0.58901888]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0, 100000.0]
Fitted coefficients: [5.36336608e-02 1.87766462e-09 6.69270788e-01 2.77095551e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0, 25000.0]
Fitted coefficients: [1.21131299e-01 1.00531009e-10 5.04380288e-01 3.74488413e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0, 3125.0]
Fitted coefficients: [1.23378669e-01 1.00000000e-10 3.16501243e-01 5.60120088e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0, 391.0]
Fitted coefficients: [0.26303824 0.02545169 0.14065034 0.57085973]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0, 50000.0]
Fitted coefficients: [8.76858633e-02 1.00321112e-10 5.31758590e-01 3.80555547e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0, 6250.0]
Fitted coefficients: [1.39419855e-01 1.00859695e-10 4.19491156e-01 4.41088989e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0, 781.0]
Fitted coefficients: [0.19816049 0.00573552 0.20050349 0.59560049]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 100000.0]
Fitted coefficients: [1.00000000e-10 3.77649229e-01 3.67442604e-01 2.54908167e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 25000.0]
Fitted coefficients: [1.00000000e-10 4.40342662e-01 1.89635281e-01 3.70022057e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 3125.0]
Fitted coefficients: [1.00610454e-10 5.29523254e-01 3.96689007e-02 4.30807845e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 391.0]
Fitted coefficients: [1.00000000e-10 5.64145916e-01 1.00000000e-10 4.35854084e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 50000.0]
Fitted coefficients: [1.00000875e-10 4.10619864e-01 2.61350648e-01 3.28029488e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 6250.0]
Fitted coefficients: [4.70994583e-10 4.87594254e-01 1.10160592e-01 4.02245154e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0, 781.0]
Fitted coefficients: [1.00297197e-10 5.49175385e-01 1.00000000e-10 4.50824615e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 100000.0]
Fitted coefficients: [0.04273303 0.03151443 0.62879398 0.29695856]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 25000.0]
Fitted coefficients: [0.1006688 0.0081475 0.5214159 0.3697678]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 3125.0]
Fitted coefficients: [0.1404384  0.01526343 0.29539949 0.54889868]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 391.0]
Fitted coefficients: [0.19925039 0.07399551 0.13853708 0.58821702]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 50000.0]
Fitted coefficients: [0.10402739 0.01383357 0.49361019 0.38852886]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 6250.0]
Fitted coefficients: [0.14166755 0.00630832 0.36973701 0.48228712]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0, 781.0]
Fitted coefficients: [0.17630404 0.04976472 0.19503683 0.57889442]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 100000.0]
Fitted coefficients: [1.00000015e-10 4.34066037e-01 3.40483055e-01 2.25450907e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 25000.0]
Fitted coefficients: [1.14548040e-09 5.02360017e-01 1.70880995e-01 3.26758990e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 3125.0]
Fitted coefficients: [1.00059858e-10 5.29724810e-01 7.21161872e-02 3.98159006e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 391.0]
Fitted coefficients: [1.00222807e-10 6.11573370e-01 1.00223940e-10 3.88426629e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 50000.0]
Fitted coefficients: [6.65688108e-10 4.93536934e-01 2.12637243e-01 2.93825823e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 6250.0]
Fitted coefficients: [1.00000041e-10 5.49649919e-01 1.09719196e-01 3.40630885e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0, 781.0]
Fitted coefficients: [1.01357718e-10 6.38029843e-01 1.00278182e-10 3.61970157e-01]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 100000.0]
Fitted coefficients: [0.03745615 0.23972188 0.50771873 0.21510323]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 25000.0]
Fitted coefficients: [0.08635502 0.19164819 0.43483767 0.28715912]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 3125.0]
Fitted coefficients: [0.07778063 0.28524284 0.28220666 0.35476987]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 391.0]
Fitted coefficients: [0.09575103 0.322289   0.17662032 0.40533965]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 50000.0]
Fitted coefficients: [0.0472647  0.22460773 0.45102101 0.27710656]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 6250.0]
Fitted coefficients: [0.08143356 0.2554341  0.33532441 0.32780793]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0, 781.0]
Fitted coefficients: [0.09538759 0.28217451 0.23929083 0.38314707]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 100000.0]
Fitted coefficients: [0.0260879  0.06420937 0.58769153 0.3220112 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 25000.0]
Fitted coefficients: [0.08853544 0.05084211 0.43386355 0.4267589 ]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 3125.0]
Fitted coefficients: [0.11350734 0.04251509 0.29169888 0.55227868]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 391.0]
Fitted coefficients: [0.11320731 0.08818748 0.15250135 0.64610387]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 50000.0]
Fitted coefficients: [0.05072859 0.05190751 0.51118888 0.38617501]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 6250.0]
Fitted coefficients: [0.11609616 0.04072556 0.35599994 0.48717834]

Processing sample: Label=['CoVNL63', 'H3N2', 'RSVB1'], Conc=[781.0, 781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0, 781.0]
Fitted coefficients: [0.11462197 0.08219009 0.20488986 0.59829809]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 100.0]
Fitted coefficients: [0.72345311 0.00087657 0.27567032]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [0.4116422  0.50340839 0.0849494 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.63641962 0.25937408 0.10420629]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.76394608 0.07083539 0.16521853]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [0.80001997 0.01162116 0.18835887]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.45093236 0.3886311  0.16043655]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.77054827 0.09495925 0.13449248]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.82633651 0.04435627 0.12930722]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.43735304 0.41148813 0.15115882]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.72991069 0.16864368 0.10144563]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.78434998 0.06053986 0.15511016]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 100.0]
Fitted coefficients: [0.68199653 0.06096375 0.25703972]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.3519285  0.58497488 0.06309662]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.49249929 0.35086931 0.1566314 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.67834931 0.13240557 0.18924513]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.70031574 0.08027157 0.21941269]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.31382292 0.48212338 0.2040537 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.65602265 0.16716114 0.17681621]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.69341187 0.10270237 0.20388576]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.29195954 0.52565462 0.18238585]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.60000023 0.24678955 0.15321022]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[12500.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.68584061 0.11913222 0.19502718]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 100.0]
Fitted coefficients: [0.60104408 0.05439069 0.34456524]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.21980149 0.69416108 0.08603743]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.31159785 0.48243838 0.20596377]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.58582087 0.14887755 0.26530158]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.62688026 0.07815855 0.29496119]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.16782763 0.6067679  0.22540448]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.57437068 0.19985819 0.22577113]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.60059024 0.12140582 0.27800394]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.14489138 0.64825468 0.20685395]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.53023427 0.30322968 0.16653604]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.58141132 0.13993629 0.27865238]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 100.0]
Fitted coefficients: [0.12154812 0.00682267 0.87162921]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [1.64817248e-10 5.83779931e-01 4.16220069e-01]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [9.14294995e-10 3.15738724e-01 6.84261275e-01]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [0.1136463  0.09021579 0.79613791]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.16043833 0.02708567 0.812476  ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [1.11905415e-10 4.33617785e-01 5.66382215e-01]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [0.09631276 0.12169105 0.78199619]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [0.1352895  0.06443425 0.80027625]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [1.21986477e-09 4.76630352e-01 5.23369647e-01]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [0.065212   0.21748021 0.71730779]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[195.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [0.12746953 0.07615293 0.79637754]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 100.0]
Fitted coefficients: [0.75501764 0.05524751 0.18973484]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [0.40338281 0.56371591 0.03290128]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.55963896 0.33388743 0.10647361]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 1562.0]
Fitted coefficients: [0.73430326 0.12217488 0.14352186]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.79463817 0.05926888 0.14609295]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.36322061 0.46853898 0.16824041]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.71464952 0.15576372 0.12958675]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.7394016  0.09842509 0.16217331]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.32290802 0.53199803 0.14509396]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.67126581 0.23476551 0.09396868]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.76764253 0.10852273 0.12383474]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 100.0]
Fitted coefficients: [0.64879327 0.07296792 0.27823881]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.2828956  0.65333124 0.06377317]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.40809325 0.4443409  0.14756585]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.61178571 0.15481295 0.23340134]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.65520838 0.09394543 0.2508462 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.23086339 0.56790749 0.20122912]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.61830192 0.19801458 0.1836835 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.63991819 0.12932047 0.23076135]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.18178841 0.64063027 0.17758133]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.56473718 0.30058381 0.13467901]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[3125.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.64570892 0.14441766 0.20987342]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 100.0]
Fitted coefficients: [0.28598873 0.02812856 0.68588272]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.02867197 0.6373722  0.33395583]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.04156129 0.34846472 0.60997398]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.24358998 0.11826649 0.63814352]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.26077147 0.03878772 0.70044081]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [1.42969503e-09 5.00670469e-01 4.99329529e-01]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.19384782 0.16390198 0.6422502 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.22059037 0.08237215 0.69703748]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [1.00000004e-10 5.10794995e-01 4.89205005e-01]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.15259444 0.26064971 0.58675585]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[391.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.20550092 0.10517041 0.68932867]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 100.0]
Fitted coefficients: [0.79740994 0.04612709 0.15646297]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [4.39170349e-01 5.60379106e-01 4.50545467e-04]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.63997559 0.31386162 0.04616279]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.79411812 0.11455856 0.09132332]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [0.83990033 0.06410233 0.09599734]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.44124585 0.45801587 0.10073828]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.76506339 0.15492599 0.08001062]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.81390043 0.0920911  0.09400847]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.40265916 0.50147452 0.09586632]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.72552323 0.23484006 0.0396367 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.80903418 0.1041188  0.08684702]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 100.0]
Fitted coefficients: [0.67589598 0.06584632 0.25825769]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.32900714 0.60060336 0.0703895 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.47041866 0.39165673 0.13792461]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.63515724 0.14596911 0.21887365]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.68886369 0.0829232  0.22821311]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.25567808 0.53540562 0.20891629]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.61977142 0.20118184 0.17904675]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.67659288 0.11328883 0.2101183 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.24649789 0.56928478 0.18421733]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.60458122 0.26033806 0.13508072]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.61743171 0.13922876 0.24333953]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 100.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 100.0]
Fitted coefficients: [0.46018159 0.04906482 0.49075359]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.12093993 0.66613041 0.21292966]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 12500.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.16618099 0.40232017 0.43149885]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.3880905  0.13361415 0.47829535]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 195.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.41923034 0.0628094  0.51796026]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.00525669 0.55442242 0.4403209 ]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.34539719 0.18709379 0.46750902]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 391.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.38455692 0.10649172 0.50895136]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.01748038 0.57944314 0.40307648]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.30933308 0.28458568 0.40608124]

Processing sample: Label=['CoVNL63', 'H3N2'], Conc=[781.0, 781.0]
Parsed viruses: ['CoVNL63', 'H3N2']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.39814331 0.1157127  0.48614399]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [0.50908    0.45462183 0.03629817]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.59155387 0.27085797 0.13758816]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.67232046 0.18073817 0.14694137]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [0.71212945 0.1004054  0.18746515]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.57940062 0.30451416 0.11608522]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.64841693 0.20057229 0.15101078]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.66866876 0.13656215 0.19476909]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.60326113 0.28871924 0.10801963]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.58615138 0.26082239 0.15302623]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.67434388 0.16429338 0.16136275]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.40379786 0.56286731 0.03333484]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.52785147 0.35610628 0.11604225]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.58424515 0.27632804 0.13942681]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.61465254 0.19757542 0.18777204]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.52931712 0.35865812 0.11202476]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.54320717 0.29570104 0.1610918 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.58148235 0.23607687 0.18244078]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.5285133  0.37772157 0.09376514]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.54487163 0.32366827 0.1314601 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[12500.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.56483874 0.2688288  0.16633245]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.28091574 0.69677377 0.02231048]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.41520479 0.42322441 0.1615708 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.46323673 0.32405266 0.21271061]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.51829072 0.21217607 0.26953321]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.41134294 0.44922268 0.13943438]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.47658501 0.32975171 0.19366327]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.50462442 0.25304696 0.24232862]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.38376994 0.47369289 0.14253717]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.44918847 0.38238505 0.16842648]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.47793385 0.29799581 0.22407033]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [3.57452957e-10 5.67214650e-01 4.32785350e-01]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [0.03478397 0.3452146  0.62000143]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [0.06882522 0.24820441 0.68297037]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.09574698 0.12897386 0.77527916]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [0.03347157 0.38593056 0.58059787]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [0.05275799 0.2771384  0.67010361]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [0.09184218 0.16781607 0.74034175]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [0.0232995  0.4005982  0.57610229]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [0.05207514 0.31601837 0.63190649]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[195.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [0.06224719 0.22901664 0.70873617]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [4.73094735e-01 5.26905255e-01 1.29839764e-08]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.57442154 0.326562   0.09901646]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.63778302 0.24403584 0.11818113]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.65639972 0.16215807 0.18144221]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.55519185 0.34719323 0.09761491]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.63934588 0.25302189 0.10763223]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.66060676 0.18823955 0.15115369]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.57524031 0.35860002 0.06615967]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.58855736 0.29575635 0.11568628]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.63128622 0.22524517 0.14346861]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.37106289 0.6123042  0.0166329 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.45556116 0.42369456 0.12074428]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.48386156 0.33362577 0.18251267]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.56658774 0.22193225 0.21148   ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.43268456 0.4362183  0.13109714]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.51928817 0.32899281 0.15171902]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.52597082 0.25550749 0.21852169]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.41745315 0.47800344 0.10454341]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.48959253 0.3866128  0.12379468]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[3125.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.5167211  0.30877734 0.17450156]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.07955478 0.61185676 0.30858846]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.14308149 0.35918026 0.49773825]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.18873172 0.26212459 0.5491437 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.22529354 0.14201058 0.63269588]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.13242128 0.3921044  0.47547432]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.16798841 0.26921551 0.56279609]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.20341103 0.18718698 0.60940199]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.1192903  0.42522176 0.45548794]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.14812075 0.31947015 0.5324091 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[391.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.16987232 0.24018171 0.58994597]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [5.73536400e-01 4.26463601e-01 2.18854730e-10]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.64086751 0.2998307  0.05930179]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.69560172 0.21352185 0.09087643]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [0.73949783 0.13686819 0.12363398]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.62286692 0.31871787 0.05841521]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.65307237 0.2468608  0.10006682]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.69139301 0.17445731 0.13414968]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.65979017 0.30601384 0.03419599]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.66839984 0.26502577 0.06657439]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.71620387 0.18517273 0.09862341]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.42269931 0.56645339 0.0108473 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.46117129 0.40429397 0.13453474]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.54775173 0.28929727 0.162951  ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.57980784 0.21546889 0.20472327]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.49405038 0.39724921 0.10870041]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.47013272 0.34688942 0.18297786]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.58103158 0.23288774 0.18608068]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.46094677 0.43269922 0.10635401]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.5023623  0.35816814 0.13946956]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.54032736 0.28146556 0.17820708]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.18444508 0.61357643 0.2019785 ]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.24416151 0.39745446 0.35838403]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 1562.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.31940944 0.27023365 0.41035692]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.33446023 0.1794986  0.48604117]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.25049064 0.41253011 0.33697925]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.3105884  0.29228796 0.39712364]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.34415044 0.2042001  0.45164945]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.25553532 0.42341644 0.32104824]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.2524017  0.38397476 0.36362354]

Processing sample: Label=['CoVNL63', 'RSVA2'], Conc=[781.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVA2']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.32887275 0.24184398 0.42928326]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [0.54854099 0.41830217 0.03315684]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.57822178 0.3032286  0.11854962]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.61312471 0.20119882 0.18567647]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [0.56536771 0.00208523 0.43254706]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.59893713 0.32913684 0.07192602]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.59847769 0.22325359 0.17826872]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.60365546 0.11775944 0.2785851 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.6033276  0.32564455 0.07102785]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.62714689 0.25269589 0.12015722]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[100000.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.6041895  0.18242173 0.21338877]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.40126949 0.54219659 0.05653391]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.42787615 0.42620884 0.14591501]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.51356015 0.28653691 0.19990294]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.50066371 0.07278233 0.42655396]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.4640689  0.42428193 0.11164917]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.48819035 0.31533546 0.1964742 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.52795416 0.19675308 0.27529276]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.47415205 0.42413435 0.1017136 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.51371602 0.35398454 0.13229944]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[12500.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.53308093 0.25242101 0.21449806]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.34050674 0.58440281 0.07509045]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.38530508 0.45229036 0.16240456]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.39341683 0.31605012 0.29053305]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.41417397 0.03106928 0.55475675]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.38931505 0.46333247 0.14735248]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.38845963 0.34100834 0.27053203]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 391.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.41638921 0.19168813 0.39192265]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.40156189 0.46556872 0.1328694 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.41829761 0.38528593 0.19641646]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[1562.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.43387371 0.25740659 0.30871971]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [0.00899112 0.48935688 0.501652  ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [0.02258811 0.35543223 0.62197966]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [0.08101567 0.20480843 0.7141759 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.08348203 0.00845271 0.90806527]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [0.02455873 0.36554807 0.6098932 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [0.04761254 0.24840042 0.70398704]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [0.15239572 0.15320208 0.6944022 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [0.0163274  0.41445685 0.56921575]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [0.0512486 0.3075495 0.6412019]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[195.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [0.09626386 0.19254082 0.71119532]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [0.54228455 0.45184714 0.00586831]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.59197022 0.31829461 0.08973517]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.61221378 0.21490383 0.17288239]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.56650547 0.03936334 0.39413119]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.55581101 0.36674258 0.07744641]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.5639202  0.25687992 0.17919988]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.58383174 0.14619396 0.26997429]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.5233634 0.4016936 0.074943 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.60743877 0.28621638 0.10634486]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[25000.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.56868118 0.20876    0.22255881]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.39022307 0.5700322  0.03974473]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.40857369 0.45065492 0.14077139]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.43060828 0.32859517 0.24079655]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.47783185 0.06513069 0.45703746]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.45398065 0.45158329 0.09443606]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.4552462  0.33662378 0.20813001]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.46284515 0.20695466 0.33020019]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.43563208 0.46712692 0.09724101]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 6250.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Fitted coefficients: [0.47800925 0.3752772  0.14671356]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[3125.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.45776767 0.28470162 0.25753071]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.05857847 0.55844859 0.38297294]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.123984   0.36194539 0.5140706 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.13906369 0.24457709 0.61635922]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.18581582 0.02012406 0.79406012]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.0970137  0.41290659 0.49007971]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.11608184 0.28802494 0.59589322]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.21654157 0.14766236 0.63579607]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.09407003 0.47683479 0.42909519]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.14890032 0.29373343 0.55736626]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[391.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.16867961 0.20229408 0.62902632]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [6.05244720e-01 3.94755284e-01 2.21687743e-10]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.63466175 0.29392478 0.07141348]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.65462203 0.1846312  0.16074676]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [0.60462065 0.0012305  0.39414885]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.60567182 0.33437108 0.0599571 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.68353127 0.19144538 0.12502335]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.6211116  0.10802222 0.27086618]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.58880616 0.35087973 0.06031412]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.67254894 0.24711231 0.08033875]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[50000.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.65286285 0.1599259  0.18721125]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.37952487 0.57833624 0.04213889]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.46561327 0.40872623 0.1256605 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.43674754 0.3214655  0.24178696]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.52373619 0.06548278 0.41078103]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.46837414 0.42030355 0.11132232]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.46094663 0.32903933 0.21001404]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.50926005 0.19541511 0.29532484]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.42857566 0.48352069 0.08790365]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.50303729 0.35885252 0.13811019]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[6250.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.48283022 0.27296285 0.24420693]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 100000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.16885112 0.58195518 0.2491937 ]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 12500.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.21748563 0.42218392 0.36033045]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 1562.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.26727875 0.25474841 0.47797284]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 195.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.28932383 0.02553024 0.68514593]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 25000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.24996333 0.41850281 0.33153386]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 3125.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.23755037 0.29961426 0.46283536]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 391.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.29522176 0.16550555 0.53927269]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 50000.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.22011142 0.45602794 0.32386064]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 6250.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.25815385 0.36262561 0.37922054]

Processing sample: Label=['CoVNL63', 'RSVB1'], Conc=[781.0, 781.0]
Parsed viruses: ['CoVNL63', 'RSVB1']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.26826718 0.23344387 0.49828895]

Processing sample: Label=['CoVNL63'], Conc=[100.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [100.0]
Fitted coefficients: [0.26583035 0.73416965]

Processing sample: Label=['CoVNL63'], Conc=[100000.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999986e-01 1.41914211e-08]

Processing sample: Label=['CoVNL63'], Conc=[12500.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.92689012 0.07310988]

Processing sample: Label=['CoVNL63'], Conc=[1562.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.89787809 0.10212191]

Processing sample: Label=['CoVNL63'], Conc=[195.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [195.0]
Fitted coefficients: [0.25779973 0.74220027]

Processing sample: Label=['CoVNL63'], Conc=[25000.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.89350721 0.10649279]

Processing sample: Label=['CoVNL63'], Conc=[3125.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.95448685 0.04551315]

Processing sample: Label=['CoVNL63'], Conc=[391.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [391.0]
Fitted coefficients: [0.54342659 0.45657341]

Processing sample: Label=['CoVNL63'], Conc=[50.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [50.0]
Fitted coefficients: [0.24807406 0.75192594]

Processing sample: Label=['CoVNL63'], Conc=[50000.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [50000.0]
Fitted coefficients: [1.00000000e+00 1.00000008e-10]

Processing sample: Label=['CoVNL63'], Conc=[6250.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.94860683 0.05139317]

Processing sample: Label=['CoVNL63'], Conc=[781.0]
Parsed viruses: ['CoVNL63']
Parsed concentrations: [781.0]
Fitted coefficients: [0.64489981 0.35510019]

Processing sample: Label=['CoVOC43'], Conc=[100.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [100.0]
Fitted coefficients: [0.15253142 0.84746858]

Processing sample: Label=['CoVOC43'], Conc=[100000.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999987e-01 1.25305095e-08]

Processing sample: Label=['CoVOC43'], Conc=[12500.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.80048358 0.19951642]

Processing sample: Label=['CoVOC43'], Conc=[1562.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.55911247 0.44088753]

Processing sample: Label=['CoVOC43'], Conc=[195.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [195.0]
Fitted coefficients: [0.32631518 0.67368482]

Processing sample: Label=['CoVOC43'], Conc=[25000.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.84566941 0.15433059]

Processing sample: Label=['CoVOC43'], Conc=[3125.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.62932564 0.37067436]

Processing sample: Label=['CoVOC43'], Conc=[391.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [391.0]
Fitted coefficients: [0.38739701 0.612603  ]

Processing sample: Label=['CoVOC43'], Conc=[50.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [50.0]
Fitted coefficients: [0.15106757 0.84893243]

Processing sample: Label=['CoVOC43'], Conc=[50000.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.92520019 0.07479981]

Processing sample: Label=['CoVOC43'], Conc=[6250.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.73727133 0.26272867]

Processing sample: Label=['CoVOC43'], Conc=[781.0]
Parsed viruses: ['CoVOC43']
Parsed concentrations: [781.0]
Fitted coefficients: [0.4774996 0.5225004]

Processing sample: Label=['FluB'], Conc=[100.0]
Parsed viruses: ['FluB']
Parsed concentrations: [100.0]
Fitted coefficients: [0.26876811 0.73123189]

Processing sample: Label=['FluB'], Conc=[100000.0]
Parsed viruses: ['FluB']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999995e-01 4.89265539e-09]

Processing sample: Label=['FluB'], Conc=[12500.0]
Parsed viruses: ['FluB']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.81682591 0.18317409]

Processing sample: Label=['FluB'], Conc=[1562.0]
Parsed viruses: ['FluB']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.70309721 0.29690279]

Processing sample: Label=['FluB'], Conc=[195.0]
Parsed viruses: ['FluB']
Parsed concentrations: [195.0]
Fitted coefficients: [0.63246842 0.36753158]

Processing sample: Label=['FluB'], Conc=[25000.0]
Parsed viruses: ['FluB']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.85830427 0.14169572]

Processing sample: Label=['FluB'], Conc=[3125.0]
Parsed viruses: ['FluB']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.74522266 0.25477734]

Processing sample: Label=['FluB'], Conc=[391.0]
Parsed viruses: ['FluB']
Parsed concentrations: [391.0]
Fitted coefficients: [0.63727551 0.36272449]

Processing sample: Label=['FluB'], Conc=[50000.0]
Parsed viruses: ['FluB']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.93399603 0.06600397]

Processing sample: Label=['FluB'], Conc=[6250.0]
Parsed viruses: ['FluB']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.76943193 0.23056807]

Processing sample: Label=['FluB'], Conc=[781.0]
Parsed viruses: ['FluB']
Parsed concentrations: [781.0]
Fitted coefficients: [0.66394417 0.33605583]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 100000.0]
Fitted coefficients: [1.00000005e-10 5.47594001e-01 4.52405999e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 12500.0]
Fitted coefficients: [1.00000000e-10 3.66390262e-01 6.33609738e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 1562.0]
Fitted coefficients: [1.00660217e-10 2.72952195e-01 7.27047803e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 195.0]
Fitted coefficients: [1.00000000e-10 1.49808867e-01 8.50191132e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 25000.0]
Fitted coefficients: [1.00000000e-10 3.62477585e-01 6.37522417e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 3125.0]
Fitted coefficients: [1.00487936e-10 2.42330197e-01 7.57669803e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 391.0]
Fitted coefficients: [1.01220665e-10 1.71360002e-01 8.28639996e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 50000.0]
Fitted coefficients: [1.00000000e-10 3.64758338e-01 6.35241662e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 6250.0]
Fitted coefficients: [1.02486679e-10 3.31193511e-01 6.68806489e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100.0, 781.0]
Fitted coefficients: [1.00000000e-10 2.06222002e-01 7.93777996e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [6.86087655e-01 3.13912323e-01 2.36889611e-08]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.74678415 0.18135082 0.07186503]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.76108228 0.13382468 0.10509305]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [0.79087029 0.07321366 0.13591605]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.72193547 0.20538951 0.07267502]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.74289311 0.15591864 0.10118825]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.77624614 0.09745042 0.12630344]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.71007392 0.23438455 0.05554153]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.76468805 0.15945381 0.07585814]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[100000.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.76233448 0.12662667 0.11103886]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.26533665 0.53770067 0.19696268]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.29456015 0.35603881 0.34940104]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.30157573 0.28860272 0.40982155]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.33829106 0.18974364 0.4719653 ]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.3066963  0.35984695 0.33345675]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.31192737 0.29359211 0.39448051]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.33694967 0.20736131 0.45568902]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.29188532 0.39736149 0.31075319]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.30408283 0.32221626 0.37370091]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[12500.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.31944108 0.25138996 0.42916896]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.15799418 0.5415337  0.30047213]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.19098357 0.32354566 0.48547078]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.19641387 0.2594358  0.54415033]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.19799983 0.1743863  0.62761387]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.18679136 0.34469885 0.46850979]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.18761122 0.28676527 0.52562351]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.21015893 0.18278986 0.60705121]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.18012295 0.37478967 0.44508738]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.17579456 0.34515802 0.47904742]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[1562.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.21204265 0.21294084 0.57501651]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [1.00000005e-10 5.55060023e-01 4.44939977e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [3.71435660e-04 3.55875716e-01 6.43752848e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [1.00000000e-10 2.70328405e-01 7.29671595e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.00259614 0.15313398 0.84426988]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [1.00015328e-10 3.78495911e-01 6.21504088e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [1.00000521e-10 2.96656024e-01 7.03343978e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [1.00000000e-10 1.89270488e-01 8.10729512e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [1.00028973e-10 3.96333904e-01 6.03666093e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [1.00000542e-10 3.49395177e-01 6.50604821e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[195.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [1.00002894e-10 2.22453076e-01 7.77546926e-01]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [0.3518967  0.50151007 0.14659323]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.38735398 0.3384015  0.27424452]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0]
Fitted coefficients: [0.40964478 0.26345414 0.32690108]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.41756367 0.19189313 0.39054319]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.3836234  0.34611347 0.27026313]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.37674089 0.30575913 0.31749999]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.40996517 0.21534172 0.37469311]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.35375763 0.4021804  0.24406197]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.37039277 0.33387934 0.2957279 ]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[25000.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.38942232 0.25550031 0.35507736]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.20378421 0.53914515 0.25707064]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.23087238 0.34559006 0.42353756]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.24052238 0.27495998 0.48451764]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.27471044 0.16427175 0.56101782]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.23752757 0.35136019 0.41111225]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.24314703 0.276875   0.47997797]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.2654302  0.19024151 0.54432829]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.22766362 0.39052617 0.38181021]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.2301966  0.32210732 0.44769608]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[3125.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.26232772 0.23007387 0.50759841]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.03620028 0.56285317 0.40094655]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.05147241 0.32924101 0.61928658]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.05424459 0.24732769 0.69842772]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.06225365 0.15355156 0.78419479]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.05164125 0.35593528 0.59242347]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.04864586 0.27837838 0.67297576]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.05966319 0.18653718 0.75379963]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.04432352 0.38373214 0.57194433]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.05356568 0.3006231  0.64581122]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[391.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.05254059 0.23031403 0.71714537]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [0.44381444 0.45911727 0.09706829]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.4969422  0.26753253 0.23552527]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.52623128 0.19770461 0.27606411]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [0.52957973 0.13750709 0.33291318]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.48690372 0.29427204 0.21882425]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.50552316 0.22542893 0.26904791]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.5302485  0.15761715 0.31213434]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.48645133 0.30793727 0.2056114 ]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.46829829 0.28048579 0.25121592]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[50000.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.5008858  0.20747341 0.29164078]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.23177251 0.52489807 0.24332942]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.26047715 0.33819552 0.40132733]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.27237466 0.25977853 0.46784681]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.29646086 0.16535558 0.53818356]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.26892888 0.33086    0.40021112]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.29048722 0.25164821 0.45786457]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.28358592 0.20301647 0.51339761]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.26090199 0.35677984 0.38231817]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.26185561 0.3274519  0.41069249]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[6250.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.27292759 0.24955331 0.4775191 ]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.10411634 0.54260289 0.35328077]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.12726074 0.33573686 0.5370024 ]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.13514918 0.26303832 0.6018125 ]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 195.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.14869393 0.15646193 0.69484413]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.1297662  0.34508299 0.52515082]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.13514029 0.26594226 0.59891745]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 391.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.14924733 0.18052587 0.6702268 ]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.12748901 0.37697197 0.49553902]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.13782273 0.28932388 0.57285339]

Processing sample: Label=['H1N1', 'RSVA2'], Conc=[781.0, 781.0]
Parsed viruses: ['H1N1', 'RSVA2']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.14313343 0.20770852 0.64915805]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 100000.0]
Fitted coefficients: [1.00186897e-10 6.12899204e-01 3.87100796e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 12500.0]
Fitted coefficients: [1.18301327e-10 4.07994420e-01 5.92005580e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 1562.0]
Fitted coefficients: [1.07765989e-10 2.38422591e-01 7.61577409e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 195.0]
Fitted coefficients: [0.00776604 0.00302302 0.98921094]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 25000.0]
Fitted coefficients: [1.19968063e-09 4.72437772e-01 5.27562227e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 3125.0]
Fitted coefficients: [1.00000000e-10 2.75764079e-01 7.24235920e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 391.0]
Fitted coefficients: [0.00783885 0.19459646 0.79756469]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 50000.0]
Fitted coefficients: [1.13177789e-09 4.93654245e-01 5.06345753e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 6250.0]
Fitted coefficients: [1.00000000e-10 3.99577417e-01 6.00422583e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100.0, 781.0]
Fitted coefficients: [1.00000000e-10 2.54460757e-01 7.45539243e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [0.46835471 0.49947544 0.03216985]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.46282184 0.3885736  0.14860456]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.49949371 0.2584654  0.24204089]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [4.67639289e-01 2.49945714e-10 5.32360712e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.47901796 0.39926814 0.12171391]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.50072049 0.27697584 0.22230367]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.4788009  0.15122044 0.36997867]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.46923886 0.42460788 0.10615326]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.51701388 0.32730558 0.15568054]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[100000.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.48701342 0.23069454 0.28229204]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.21522787 0.57995819 0.20481393]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.23351435 0.43015749 0.33632816]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.23106241 0.30231102 0.46662657]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.22431673 0.03246636 0.74321691]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.21523675 0.46416936 0.32059389]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.22972127 0.3080804  0.46219832]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.24536119 0.1395565  0.61508232]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.22784975 0.48602982 0.28612043]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.23202884 0.39657953 0.37139163]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[12500.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.21531044 0.27185778 0.51283178]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.11788508 0.57348802 0.3086269 ]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.12007503 0.44292664 0.43699834]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.13440135 0.29470143 0.57089722]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.15197646 0.02763609 0.82038744]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.12548492 0.46637989 0.40813518]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.12290246 0.31751018 0.55958736]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.13333811 0.16771271 0.69894918]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.13031579 0.48438284 0.38530137]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.11747765 0.41275367 0.46976868]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[1562.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.14912294 0.22884792 0.62202914]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [4.92274215e-09 5.87874795e-01 4.12125200e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [1.00000000e-10 4.27777444e-01 5.72222556e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [1.02935627e-10 2.84977425e-01 7.15022573e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.01698018 0.01474461 0.96827521]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [1.00000004e-10 4.72312377e-01 5.27687623e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [1.00000000e-10 3.25065636e-01 6.74934361e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [0.00395648 0.19622975 0.79981377]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [3.53730642e-09 4.97558919e-01 5.02441078e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [1.00168484e-10 3.95574831e-01 6.04425169e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[195.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [1.02493153e-10 2.62139485e-01 7.37860515e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [0.29457395 0.54688337 0.15854268]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.28300145 0.4295333  0.28746525]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0]
Fitted coefficients: [0.2985848  0.2992474  0.40216781]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.29427581 0.01067503 0.69504916]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.29953636 0.44328524 0.2571784 ]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.28703039 0.31652875 0.39644085]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.29198798 0.15443816 0.55357386]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.32396491 0.43527385 0.24076124]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.32229048 0.36673916 0.31097036]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[25000.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.31459594 0.24603997 0.4393641 ]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.15666125 0.58982887 0.25350988]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.15777542 0.44647542 0.39574916]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.17874537 0.28360517 0.53764946]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.18675669 0.01344354 0.79979977]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.17512306 0.45597291 0.36890403]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.17387566 0.31911023 0.50701411]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.18050136 0.15503209 0.66446656]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.15681299 0.51177635 0.33141065]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.17959069 0.38621238 0.43419692]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[3125.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.19339602 0.23057505 0.57602892]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.01191939 0.61627614 0.37180447]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.01262567 0.41484968 0.57252466]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.01002055 0.29817792 0.69180153]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.05893648 0.01857131 0.92249221]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.01853843 0.46956386 0.51189771]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.00422867 0.3391748  0.65659653]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.03465507 0.18376053 0.7815844 ]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.01022649 0.50464776 0.48512575]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.02383948 0.39309855 0.58306197]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[391.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.01070879 0.24895964 0.74033157]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [0.37685893 0.48591339 0.13722768]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.41268116 0.35419995 0.23311889]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.4369663  0.23285523 0.33017847]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [3.83886012e-01 1.00109829e-10 6.16113985e-01]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.44439074 0.34594307 0.20966619]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.43268851 0.24857536 0.31873612]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.42031489 0.14299691 0.4366882 ]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.38071569 0.42451107 0.19477324]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.39801246 0.34018873 0.26179881]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[50000.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.40109543 0.21648353 0.38242104]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.16892206 0.60970062 0.22137732]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.18493402 0.43055346 0.38451252]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.20223201 0.28129233 0.51647566]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.20258774 0.02157559 0.77583667]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.18184451 0.46989937 0.34825612]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.1919088  0.32148058 0.48661062]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.18358886 0.15682174 0.6595894 ]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.18179877 0.50249005 0.31571118]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.19915606 0.37677082 0.42407312]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[6250.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.19819584 0.24846247 0.55334169]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 100000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.0924471 0.543109  0.3644439]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 12500.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.07831863 0.43333089 0.48835048]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 1562.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.0971071  0.25493718 0.64795572]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 195.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.11223375 0.01663241 0.87113384]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 25000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.09293559 0.43836488 0.46869953]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 3125.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.07609877 0.30384797 0.62005327]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 391.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.10634241 0.174848   0.7188096 ]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 50000.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.0769383 0.5196152 0.4034465]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 6250.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.09684563 0.363489   0.53966537]

Processing sample: Label=['H1N1', 'RSVB1'], Conc=[781.0, 781.0]
Parsed viruses: ['H1N1', 'RSVB1']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.0729761  0.25753281 0.66949109]

Processing sample: Label=['H1N1'], Conc=[100.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [100.0]
Fitted coefficients: [0.00818371 0.99181629]

Processing sample: Label=['H1N1'], Conc=[100000.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999979e-01 2.14633056e-08]

Processing sample: Label=['H1N1'], Conc=[12500.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.60636244 0.39363757]

Processing sample: Label=['H1N1'], Conc=[1562.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.38045719 0.61954281]

Processing sample: Label=['H1N1'], Conc=[195.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [195.0]
Fitted coefficients: [0.05339284 0.94660715]

Processing sample: Label=['H1N1'], Conc=[25000.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.71154502 0.28845498]

Processing sample: Label=['H1N1'], Conc=[3125.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.47287553 0.52712447]

Processing sample: Label=['H1N1'], Conc=[391.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [391.0]
Fitted coefficients: [0.12165311 0.87834689]

Processing sample: Label=['H1N1'], Conc=[50000.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.78872551 0.21127449]

Processing sample: Label=['H1N1'], Conc=[6250.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.51326932 0.48673068]

Processing sample: Label=['H1N1'], Conc=[781.0]
Parsed viruses: ['H1N1']
Parsed concentrations: [781.0]
Fitted coefficients: [0.29088442 0.70911558]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 100000.0]
Fitted coefficients: [1.26323491e-08 7.33191023e-01 2.66808964e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 12500.0]
Fitted coefficients: [3.36531477e-09 4.95013458e-01 5.04986539e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 1562.0]
Fitted coefficients: [1.04770911e-10 4.04655543e-01 5.95344453e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 195.0]
Fitted coefficients: [1.00000000e-10 2.64580915e-01 7.35419083e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 25000.0]
Fitted coefficients: [8.20119858e-09 5.14380098e-01 4.85619894e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 3125.0]
Fitted coefficients: [1.02519754e-10 4.16465761e-01 5.83534235e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 391.0]
Fitted coefficients: [1.00000000e-10 3.02108595e-01 6.97891405e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 50000.0]
Fitted coefficients: [1.04013109e-10 5.54555671e-01 4.45444329e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 6250.0]
Fitted coefficients: [1.00750240e-08 4.67992752e-01 5.32007238e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100.0, 781.0]
Fitted coefficients: [1.01050130e-10 3.57724615e-01 6.42275382e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [5.98118604e-01 4.01881395e-01 1.00000000e-10]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.65883299 0.23838249 0.10278453]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.67662927 0.17232151 0.15104922]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [0.71777    0.09473367 0.18749633]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.654885   0.25636104 0.08875396]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.6780984  0.18851572 0.13338588]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.71100367 0.11284851 0.17614782]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.644015   0.27291568 0.08306933]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.66593687 0.2170408  0.11702233]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[100000.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.69416525 0.14419535 0.16163941]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.28452256 0.620294   0.09518344]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.31801985 0.41119982 0.27078033]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.33836796 0.3231573  0.33847474]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [0.37089337 0.20705088 0.42205574]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.32065017 0.42572079 0.25362903]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.33549323 0.33606388 0.32844289]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.34826232 0.25342205 0.39831562]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.31039622 0.45338615 0.23621763]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.32951551 0.39109542 0.27938908]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[12500.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.35192169 0.2818908  0.36618752]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.05633383 0.78557847 0.1580877 ]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.06999043 0.55835333 0.37165624]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.07832195 0.45662078 0.46505727]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.08436871 0.3430572  0.57257408]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.07458535 0.56895163 0.35646302]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.07767223 0.47722839 0.44509938]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.07992253 0.38326217 0.5368153 ]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.06601551 0.61289057 0.32109392]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.07776197 0.52387552 0.39836251]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[1562.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.07370726 0.42830165 0.49799109]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [1.00314413e-10 8.20795827e-01 1.79204173e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [1.18825632e-08 5.88035661e-01 4.11964327e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [1.08810119e-10 4.85650939e-01 5.14349061e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [1.00434373e-10 3.54114091e-01 6.45885909e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [9.18075252e-09 6.05121219e-01 3.94878772e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [1.03867058e-10 5.01111740e-01 4.98888260e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [1.00000000e-10 3.94592715e-01 6.05407281e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [1.01043397e-10 6.28487098e-01 3.71512902e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [1.00000005e-10 5.56460329e-01 4.43539671e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[195.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [7.55744541e-10 4.46498230e-01 5.53501770e-01]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [0.42332236 0.47523842 0.10143922]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.46911032 0.27764409 0.25324559]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 1562.0]
Fitted coefficients: [0.49090385 0.19339684 0.31569932]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [0.53220869 0.07497032 0.39282098]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.47276492 0.28110682 0.24612826]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.48918768 0.19727066 0.31354166]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.511      0.11632208 0.37267793]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.45889996 0.31185315 0.22924689]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 6250.0]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Fitted coefficients: [0.48171687 0.24132632 0.27695682]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[25000.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.49795508 0.16431246 0.33773246]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.10126012 0.77725424 0.12148564]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.12161755 0.53669756 0.34168489]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.13089032 0.44955571 0.41955396]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.12625225 0.34241746 0.53133029]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.12285311 0.55061426 0.32653262]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.11984345 0.46281967 0.41733689]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.12133704 0.37777117 0.50089178]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.11385645 0.59060954 0.29553401]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.11254074 0.51680523 0.37065403]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[3125.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.12216752 0.41433282 0.46349966]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.0333517  0.80505507 0.16159323]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.04385236 0.5799414  0.37620624]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.04603476 0.47056684 0.48339841]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.04234459 0.34730797 0.61034744]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.04217909 0.57474257 0.38307834]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [0.03647278 0.49055267 0.47297455]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [0.04470941 0.39112036 0.56417023]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.03643134 0.62340598 0.34016268]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.04496625 0.53468219 0.42035156]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[391.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.04007408 0.44301222 0.5169137 ]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [0.48038121 0.44397182 0.07564697]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.5336926  0.23538878 0.23091863]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.55326437 0.15801159 0.28872404]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [0.58687255 0.06885823 0.34426923]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.53746588 0.23947358 0.22306054]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.54918826 0.17525446 0.27555727]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.57257742 0.09989778 0.3275248 ]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.51705006 0.29052828 0.19242166]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.53695209 0.2194059  0.24364202]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[50000.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.56077376 0.13915691 0.30006933]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.1834902  0.73995898 0.07655083]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.21214043 0.50921952 0.27864005]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.22719461 0.42779958 0.34500581]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.2405378  0.32188995 0.43757226]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.2124214  0.52963645 0.25794216]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.2245405  0.43620182 0.33925769]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.23203443 0.35441961 0.41354596]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.21113064 0.554824   0.23404536]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.21994251 0.49264617 0.28741132]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[6250.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.23024682 0.40026243 0.36949075]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.04594823 0.80660308 0.14744868]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.06064194 0.55718446 0.3821736 ]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.06225481 0.46110207 0.47664312]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 195.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.06649279 0.35160223 0.58190498]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.05006766 0.58675111 0.36318123]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.05671458 0.4822821  0.46100332]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 391.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.058911   0.38339144 0.55769756]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.04498391 0.60913675 0.34587934]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.0528618  0.52897938 0.41815882]

Processing sample: Label=['H3N2', 'RSVA2'], Conc=[781.0, 781.0]
Parsed viruses: ['H3N2', 'RSVA2']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.05777528 0.43490164 0.50732308]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 100000.0]
Fitted coefficients: [2.37896359e-08 7.05356185e-01 2.94643791e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 12500.0]
Fitted coefficients: [6.99585819e-09 5.40168088e-01 4.59831905e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 1562.0]
Fitted coefficients: [1.24962404e-10 3.57315453e-01 6.42684545e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 195.0]
Fitted coefficients: [8.88800967e-04 6.19414261e-03 9.92917056e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 25000.0]
Fitted coefficients: [1.00000005e-10 5.62377643e-01 4.37622358e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 3125.0]
Fitted coefficients: [1.00000000e-10 3.90290856e-01 6.09709144e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 391.0]
Fitted coefficients: [1.01118299e-10 2.04016571e-01 7.95983429e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 50000.0]
Fitted coefficients: [1.14159662e-10 6.06159927e-01 3.93840073e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 6250.0]
Fitted coefficients: [1.07681240e-10 4.89541033e-01 5.10458967e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100.0, 781.0]
Fitted coefficients: [1.01402321e-10 3.07812171e-01 6.92187829e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 100000.0]
Fitted coefficients: [0.62245671 0.34697002 0.03057328]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 12500.0]
Fitted coefficients: [0.64658235 0.25571237 0.09770528]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 1562.0]
Fitted coefficients: [0.65613466 0.1511317  0.19273364]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 195.0]
Fitted coefficients: [6.06636327e-01 1.70468978e-10 3.93363673e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 25000.0]
Fitted coefficients: [0.65385676 0.26462083 0.08152241]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 3125.0]
Fitted coefficients: [0.66233775 0.17132033 0.16634193]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 391.0]
Fitted coefficients: [0.64299517 0.0665274  0.29047743]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 50000.0]
Fitted coefficients: [0.64886154 0.29166754 0.05947092]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 6250.0]
Fitted coefficients: [0.66436264 0.22653645 0.10910091]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[100000.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [100000.0, 781.0]
Fitted coefficients: [0.65538104 0.13241275 0.21220621]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 100000.0]
Fitted coefficients: [0.30411622 0.55364705 0.14223673]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 12500.0]
Fitted coefficients: [0.31659377 0.41418272 0.26922352]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 1562.0]
Fitted coefficients: [0.32283011 0.27861831 0.39855157]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 195.0]
Fitted coefficients: [2.88200310e-01 1.00129335e-10 7.11799689e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 25000.0]
Fitted coefficients: [0.3149029  0.43620577 0.24889133]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 3125.0]
Fitted coefficients: [0.32686526 0.28849329 0.38464145]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 391.0]
Fitted coefficients: [0.33556105 0.11795533 0.54648362]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 50000.0]
Fitted coefficients: [0.32258869 0.45644973 0.22096159]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 6250.0]
Fitted coefficients: [0.33477175 0.36311219 0.30211606]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[12500.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [12500.0, 781.0]
Fitted coefficients: [0.31906164 0.23097247 0.44996589]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 100000.0]
Fitted coefficients: [0.04373376 0.78204914 0.1742171 ]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 12500.0]
Fitted coefficients: [0.03864725 0.62857376 0.33277899]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 1562.0]
Fitted coefficients: [0.04627773 0.44905231 0.50466996]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 195.0]
Fitted coefficients: [0.0679611  0.01027182 0.92176708]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 25000.0]
Fitted coefficients: [0.04220358 0.64582014 0.31197628]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 3125.0]
Fitted coefficients: [0.02572928 0.48761638 0.48665433]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 391.0]
Fitted coefficients: [0.0299686  0.25745201 0.71257939]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 50000.0]
Fitted coefficients: [0.03670227 0.68736326 0.27593447]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 6250.0]
Fitted coefficients: [0.04351743 0.57939522 0.37708735]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[1562.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [1562.0, 781.0]
Fitted coefficients: [0.03392561 0.40238977 0.56368461]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 100000.0]
Fitted coefficients: [2.05060923e-08 8.21350660e-01 1.78649320e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 12500.0]
Fitted coefficients: [1.43676585e-08 6.34415736e-01 3.65584250e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 1562.0]
Fitted coefficients: [1.25835445e-10 4.58841859e-01 5.41158141e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 195.0]
Fitted coefficients: [0.02664659 0.04289787 0.93045554]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 25000.0]
Fitted coefficients: [2.86554759e-08 6.75819812e-01 3.24180160e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 3125.0]
Fitted coefficients: [1.33411720e-10 5.00930955e-01 4.99069045e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 391.0]
Fitted coefficients: [1.05645608e-10 2.35425524e-01 7.64574476e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 50000.0]
Fitted coefficients: [1.94921540e-08 7.03573658e-01 2.96426323e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 6250.0]
Fitted coefficients: [9.23646964e-09 5.82149577e-01 4.17850414e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[195.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [195.0, 781.0]
Fitted coefficients: [1.00000000e-10 4.00077623e-01 5.99922374e-01]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 100000.0]
Fitted coefficients: [0.45518954 0.3550811  0.18972936]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 12500.0]
Fitted coefficients: [0.47362892 0.21994688 0.30642421]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 1562.0]
Fitted coefficients: [0.48715858 0.10282856 0.41001286]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 195.0]
Fitted coefficients: [4.06308412e-01 1.00000000e-10 5.93691588e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 25000.0]
Fitted coefficients: [0.48691187 0.23552801 0.27756012]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 3125.0]
Fitted coefficients: [0.49662743 0.11376847 0.38960411]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 391.0]
Fitted coefficients: [0.47252745 0.01568842 0.51178413]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 50000.0]
Fitted coefficients: [0.47661998 0.26774246 0.25563756]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 6250.0]
Fitted coefficients: [0.49558447 0.18029419 0.32412134]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[25000.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [25000.0, 781.0]
Fitted coefficients: [0.47394086 0.09866848 0.42739066]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 100000.0]
Fitted coefficients: [0.07973447 0.7713126  0.14895292]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 12500.0]
Fitted coefficients: [0.07347521 0.617359   0.30916579]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 1562.0]
Fitted coefficients: [0.07593805 0.45677277 0.46728918]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 195.0]
Fitted coefficients: [0.09659522 0.03208427 0.87132051]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 25000.0]
Fitted coefficients: [0.08062016 0.64035    0.27902984]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 3125.0]
Fitted coefficients: [0.08385309 0.46447619 0.45167072]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 391.0]
Fitted coefficients: [0.07729025 0.24292076 0.67978899]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:441: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  g = append(wrapped_grad(x), 0.0)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:495: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  a_eq = vstack([con['jac'](x, *con['args'])
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 50000.0]
Fitted coefficients: [0.08041577 0.67585726 0.24372697]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 6250.0]
Fitted coefficients: [0.07660233 0.56925716 0.35414051]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[3125.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [3125.0, 781.0]
Fitted coefficients: [0.06910004 0.39969706 0.5312029 ]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 100000.0]
Fitted coefficients: [0.01478334 0.80278758 0.18242908]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 12500.0]
Fitted coefficients: [0.01378234 0.63283849 0.35337917]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 1562.0]
Fitted coefficients: [0.01399027 0.44912979 0.53687994]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 195.0]
Fitted coefficients: [0.04289821 0.01951162 0.93759017]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 25000.0]
Fitted coefficients: [0.01267664 0.66775789 0.31956547]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 3125.0]
Fitted coefficients: [3.81113289e-10 4.94069390e-01 5.05930610e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 391.0]
Fitted coefficients: [1.00002941e-10 2.46150035e-01 7.53849963e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 50000.0]
Fitted coefficients: [0.01200112 0.6901889  0.29780998]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 6250.0]
Fitted coefficients: [0.01273024 0.57479622 0.41247354]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[391.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [391.0, 781.0]
Fitted coefficients: [0.00083857 0.41008892 0.58907251]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 100000.0]
Fitted coefficients: [0.50918829 0.32454145 0.16627026]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 12500.0]
Fitted coefficients: [0.53546791 0.22553104 0.23900105]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 1562.0]
Fitted coefficients: [0.52980258 0.12328405 0.34691337]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 195.0]
Fitted coefficients: [4.75008131e-01 1.87777819e-10 5.24991870e-01]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 25000.0]
Fitted coefficients: [0.53968754 0.21954591 0.24076655]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 3125.0]
Fitted coefficients: [0.54068057 0.12175086 0.33756857]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 391.0]
Fitted coefficients: [0.52621551 0.00525163 0.46853287]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 50000.0]
Fitted coefficients: [0.51952511 0.26322123 0.21725366]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 6250.0]
Fitted coefficients: [0.54044186 0.17579042 0.28376772]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[50000.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [50000.0, 781.0]
Fitted coefficients: [0.53916792 0.07771654 0.38311554]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 100000.0]
Fitted coefficients: [0.15583473 0.7483805  0.09578476]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 12500.0]
Fitted coefficients: [0.17248237 0.59482252 0.23269511]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 1562.0]
Fitted coefficients: [0.16503099 0.45468241 0.38028659]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 195.0]
Fitted coefficients: [0.18265582 0.01026515 0.80707903]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 25000.0]
Fitted coefficients: [0.16678523 0.6217471  0.21146767]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 3125.0]
Fitted coefficients: [0.17146889 0.45879584 0.36973527]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 391.0]
Fitted coefficients: [0.17818942 0.25621876 0.56559182]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 50000.0]
Fitted coefficients: [0.17415233 0.64377671 0.18207096]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 6250.0]
Fitted coefficients: [0.17905972 0.54513352 0.27580676]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[6250.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [6250.0, 781.0]
Fitted coefficients: [0.16862515 0.39539893 0.43597592]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 100000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 100000.0]
Fitted coefficients: [0.02408169 0.79908566 0.17683265]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 12500.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 12500.0]
Fitted coefficients: [0.01713052 0.6285655  0.35430398]

/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)
/home/zhao/myenv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py:437: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  fx = wrapped_fun(x)

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 1562.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 1562.0]
Fitted coefficients: [0.02085101 0.45962749 0.5195215 ]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 195.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 195.0]
Fitted coefficients: [0.04356186 0.00212693 0.95431122]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 25000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 25000.0]
Fitted coefficients: [0.03422019 0.64982559 0.31595422]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 3125.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 3125.0]
Fitted coefficients: [0.01864728 0.48575989 0.49559284]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 391.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 391.0]
Fitted coefficients: [0.01090873 0.25230584 0.73678543]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 50000.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 50000.0]
Fitted coefficients: [0.0247523  0.68583569 0.28941201]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 6250.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 6250.0]
Fitted coefficients: [0.02125914 0.58728941 0.39145145]

Processing sample: Label=['H3N2', 'RSVB1'], Conc=[781.0, 781.0]
Parsed viruses: ['H3N2', 'RSVB1']
Parsed concentrations: [781.0, 781.0]
Fitted coefficients: [0.01766909 0.39953167 0.58279924]

Processing sample: Label=['H3N2'], Conc=[100.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [100.0]
Fitted coefficients: [0.07376112 0.92623888]

Processing sample: Label=['H3N2'], Conc=[100000.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999979e-01 2.08242956e-08]

Processing sample: Label=['H3N2'], Conc=[12500.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.73675922 0.26324078]

Processing sample: Label=['H3N2'], Conc=[1562.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.48758925 0.51241075]

Processing sample: Label=['H3N2'], Conc=[195.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [195.0]
Fitted coefficients: [0.16282097 0.83717903]

Processing sample: Label=['H3N2'], Conc=[25000.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.85464418 0.14535582]

Processing sample: Label=['H3N2'], Conc=[3125.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.59034 0.40966]

Processing sample: Label=['H3N2'], Conc=[391.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [391.0]
Fitted coefficients: [0.20830573 0.79169427]

Processing sample: Label=['H3N2'], Conc=[50000.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.9517416 0.0482584]

Processing sample: Label=['H3N2'], Conc=[6250.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.68898969 0.31101031]

Processing sample: Label=['H3N2'], Conc=[781.0]
Parsed viruses: ['H3N2']
Parsed concentrations: [781.0]
Fitted coefficients: [0.29133614 0.70866386]

Processing sample: Label=['HMPVA'], Conc=[100.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [100.0]
Fitted coefficients: [0.18792842 0.81207158]

Processing sample: Label=['HMPVA'], Conc=[100000.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999992e-01 7.65517405e-09]

Processing sample: Label=['HMPVA'], Conc=[12500.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.81169652 0.18830348]

Processing sample: Label=['HMPVA'], Conc=[1562.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.57128731 0.42871269]

Processing sample: Label=['HMPVA'], Conc=[195.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [195.0]
Fitted coefficients: [0.18933619 0.81066381]

Processing sample: Label=['HMPVA'], Conc=[25000.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.87570656 0.12429344]

Processing sample: Label=['HMPVA'], Conc=[3125.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.65800391 0.34199609]

Processing sample: Label=['HMPVA'], Conc=[391.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [391.0]
Fitted coefficients: [0.38546761 0.61453239]

Processing sample: Label=['HMPVA'], Conc=[50.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [50.0]
Fitted coefficients: [0.06512105 0.93487895]

Processing sample: Label=['HMPVA'], Conc=[50000.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.94322021 0.05677979]

Processing sample: Label=['HMPVA'], Conc=[6250.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.72974901 0.27025099]

Processing sample: Label=['HMPVA'], Conc=[781.0]
Parsed viruses: ['HMPVA']
Parsed concentrations: [781.0]
Fitted coefficients: [0.48434119 0.51565881]

Processing sample: Label=['HMPVB'], Conc=[100.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [100.0]
Fitted coefficients: [0.20855135 0.79144865]

Processing sample: Label=['HMPVB'], Conc=[100000.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999974e-01 2.61695836e-08]

Processing sample: Label=['HMPVB'], Conc=[12500.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.8512515 0.1487485]

Processing sample: Label=['HMPVB'], Conc=[1562.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.66217852 0.33782148]

Processing sample: Label=['HMPVB'], Conc=[195.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [195.0]
Fitted coefficients: [0.20862337 0.79137663]

Processing sample: Label=['HMPVB'], Conc=[25000.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.91106935 0.08893065]

Processing sample: Label=['HMPVB'], Conc=[3125.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.7340869 0.2659131]

Processing sample: Label=['HMPVB'], Conc=[391.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [391.0]
Fitted coefficients: [0.44886964 0.55113036]

Processing sample: Label=['HMPVB'], Conc=[50.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [50.0]
Fitted coefficients: [0.06531593 0.93468407]

Processing sample: Label=['HMPVB'], Conc=[50000.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.9532456 0.0467544]

Processing sample: Label=['HMPVB'], Conc=[6250.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.82587269 0.17412731]

Processing sample: Label=['HMPVB'], Conc=[781.0]
Parsed viruses: ['HMPVB']
Parsed concentrations: [781.0]
Fitted coefficients: [0.58898448 0.41101551]

Processing sample: Label=['RSVA2'], Conc=[100.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [100.0]
Fitted coefficients: [0.18227725 0.81772275]

Processing sample: Label=['RSVA2'], Conc=[100000.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [100000.0]
Fitted coefficients: [9.99999997e-01 2.53557730e-09]

Processing sample: Label=['RSVA2'], Conc=[12500.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.7447884 0.2552116]

Processing sample: Label=['RSVA2'], Conc=[1562.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.62550835 0.37449165]

Processing sample: Label=['RSVA2'], Conc=[195.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [195.0]
Fitted coefficients: [0.4785084 0.5214916]

Processing sample: Label=['RSVA2'], Conc=[25000.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.76195198 0.23804802]

Processing sample: Label=['RSVA2'], Conc=[3125.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.64122538 0.35877462]

Processing sample: Label=['RSVA2'], Conc=[50.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [50.0]
Fitted coefficients: [0.09803131 0.90196869]

Processing sample: Label=['RSVA2'], Conc=[50000.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.79886039 0.20113961]

Processing sample: Label=['RSVA2'], Conc=[6250.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.70890969 0.29109031]

Processing sample: Label=['RSVA2'], Conc=[781.0]
Parsed viruses: ['RSVA2']
Parsed concentrations: [781.0]
Fitted coefficients: [0.58454039 0.41545961]

Processing sample: Label=['RSVB1'], Conc=[100.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [100.0]
Fitted coefficients: [0.14347134 0.85652866]

Processing sample: Label=['RSVB1'], Conc=[100000.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [100000.0]
Fitted coefficients: [1.00000000e+00 1.00000008e-10]

Processing sample: Label=['RSVB1'], Conc=[12500.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [12500.0]
Fitted coefficients: [0.80159263 0.19840737]

Processing sample: Label=['RSVB1'], Conc=[1562.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [1562.0]
Fitted coefficients: [0.5815584 0.4184416]

Processing sample: Label=['RSVB1'], Conc=[195.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [195.0]
Fitted coefficients: [0.2146715 0.7853285]

Processing sample: Label=['RSVB1'], Conc=[25000.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [25000.0]
Fitted coefficients: [0.82445965 0.17554036]

Processing sample: Label=['RSVB1'], Conc=[3125.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [3125.0]
Fitted coefficients: [0.61209481 0.38790519]

Processing sample: Label=['RSVB1'], Conc=[391.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [391.0]
Fitted coefficients: [0.31958347 0.68041653]

Processing sample: Label=['RSVB1'], Conc=[50.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [50.0]
Fitted coefficients: [0.07422414 0.92577586]

Processing sample: Label=['RSVB1'], Conc=[50000.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [50000.0]
Fitted coefficients: [0.87568932 0.12431068]

Processing sample: Label=['RSVB1'], Conc=[6250.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [6250.0]
Fitted coefficients: [0.72726067 0.27273933]

Processing sample: Label=['RSVB1'], Conc=[781.0]
Parsed viruses: ['RSVB1']
Parsed concentrations: [781.0]
Fitted coefficients: [0.50266095 0.49733905]

In [36]:
# Step 6: Sort the wavenumber columns if needed
if not predicted_df.empty:
    wavenumber_cols = [col for col in predicted_df.columns if col not in ['Label', 'Conc']]
    wavenumber_cols_sorted = sorted(wavenumber_cols, key=float)
    desired_order_cols = ['Label', 'Conc'] + wavenumber_cols_sorted
    predicted_df = predicted_df[desired_order_cols]

predicted_df

,Label,Conc,450.0,451.0,452.0,453.0,454.0,455.0,456.0,457.0,...,1691.0,1692.0,1693.0,1694.0,1695.0,1696.0,1697.0,1698.0,1699.0,1700.0
0,['Ad5'],[100.0],0.146968,0.153877,0.161078,0.168916,0.177164,0.185491,0.195904,0.201364,...,0.797566,0.781133,0.765924,0.751674,0.739240,0.725515,0.710731,0.693833,0.677220,0.660722
1,['Ad5'],[100000.0],0.108017,0.115627,0.123576,0.132051,0.140915,0.149695,0.160068,0.166644,...,1.058237,1.045763,1.033407,1.020407,1.007390,0.992627,0.976119,0.957441,0.937000,0.914610
2,['Ad5'],[12500.0],0.117221,0.124666,0.132438,0.140762,0.149481,0.158154,0.168536,0.174848,...,0.996639,0.983229,0.970199,0.956904,0.944025,0.929507,0.913406,0.895149,0.875613,0.854615
3,['Ad5'],[1562.0],0.127901,0.135153,0.142721,0.150870,0.159420,0.167968,0.178362,0.184368,...,0.925168,0.910672,0.896860,0.883222,0.870503,0.856270,0.840641,0.822872,0.804385,0.785003
4,['Ad5'],[195.0],0.143631,0.150600,0.157866,0.165757,0.174058,0.182424,0.192834,0.198389,...,0.819898,0.803804,0.788840,0.774696,0.762213,0.748399,0.733467,0.716416,0.699475,0.682473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2574,['RSVB1'],[391.0],0.159109,0.165067,0.170919,0.177092,0.183435,0.189692,0.197186,0.201110,...,0.794861,0.779894,0.766236,0.753827,0.743455,0.731863,0.719226,0.704624,0.690286,0.676152
2575,['RSVB1'],[50.0],0.157547,0.164095,0.170834,0.178158,0.185841,0.193597,0.203340,0.208221,...,0.745012,0.728130,0.712714,0.698642,0.686804,0.673781,0.659838,0.643829,0.628506,0.613731
2576,['RSVB1'],[50000.0],0.162649,0.167270,0.171110,0.174676,0.177982,0.180843,0.183237,0.184993,...,0.907845,0.897215,0.887544,0.878905,0.871857,0.863505,0.853827,0.842418,0.830310,0.817629
2577,['RSVB1'],[6250.0],0.161704,0.166682,0.171059,0.175321,0.179437,0.183205,0.186960,0.189294,...,0.877689,0.865901,0.855166,0.845521,0.837586,0.828369,0.817901,0.805640,0.792936,0.779868
2578,['RSVB1'],[781.0],0.160274,0.165792,0.170982,0.176297,0.181640,0.186779,0.192593,0.195804,...,0.832057,0.818517,0.806172,0.795005,0.785727,0.775201,0.763538,0.749988,0.736383,0.722728

In [37]:
result_df

,Label,Conc,Coefficients,Intercept,MAE,RMSE,R2,VIFs
0,['Ad5'],[100.0],"[0.20600990733159996, 0.7939900911335066]",0,5.040000e-02,6.268144e-02,0.988069,"[1.2393174134508542, 1.2393174134508544]"
1,['Ad5'],[100000.0],"[0.9999999247687703, 7.523122991237585e-08]",0,3.838299e-08,4.822219e-08,1.000000,"[1.2393174134508542, 1.2393174134508544]"
2,['Ad5'],[12500.0],"[0.812376534461888, 0.18762346561883003]",0,5.025815e-02,6.322162e-02,0.975363,"[1.2393174134508542, 1.2393174134508544]"
3,['Ad5'],[1562.0],"[0.5946771859918338, 0.40532281098829875]",0,1.055268e-01,1.332815e-01,0.913586,"[1.2393174134508542, 1.2393174134508544]"
4,['Ad5'],[195.0],"[0.27403126111066306, 0.725968738889337]",0,9.737364e-02,1.238858e-01,0.954032,"[1.2393174134508542, 1.2393174134508544]"
...,...,...,...,...,...,...,...,...
2574,['RSVB1'],[391.0],"[0.31958347302586476, 0.6804165269741352]",0,8.454475e-02,1.081358e-01,0.976600,"[2.604941074035777, 2.6049410740357786]"
2575,['RSVB1'],[50.0],"[0.07422413634395475, 0.9257758636560453]",0,3.616650e-02,5.415651e-02,0.993632,"[2.604941074035777, 2.6049410740357786]"
2576,['RSVB1'],[50000.0],"[0.8756893240199906, 0.12431067606757835]",0,5.275504e-02,6.881450e-02,0.988676,"[2.604941074035777, 2.6049410740357786]"
2577,['RSVB1'],[6250.0],"[0.7272606699824804, 0.27273932798545336]",0,1.031624e-01,1.427801e-01,0.950685,"[2.604941074035777, 2.6049410740357786]"
2578,['RSVB1'],[781.0],"[0.5026609548099481, 0.49733904519005195]",0,9.832640e-02,1.262325e-01,0.965916,"[2.604941074035777, 2.6049410740357786]"

In [38]:
# Step 7: Save the processed data
print("\nSaving processed data...")
pd.DataFrame(predicted_df).to_csv(RESULT_FOLDER + f"/{DATE} - reconstructed_spectra_(only_GLF)_constraint_1e-10.csv", index=False)
pd.DataFrame(result_df).to_csv(RESULT_FOLDER + f"/{DATE} - coefficients_(only_GLF)_constraint_1e-10.csv", index=False)

Saving processed data...

In [39]:
# Step 8: Calculate group average of predicted data
print("\nCalculating group average of predicted data...")
avg_predicted_df = calculate_group_average(predicted_df)
print(f"Average predicted DataFrame shape: {avg_predicted_df.shape}")
avg_predicted_df

Calculating group average of predicted data...
Average predicted DataFrame shape: (2579, 1251)

                         450.0     451.0     452.0     453.0     454.0  \
Label     Conc
['Ad5']   [100.0]     0.146968  0.153877  0.161078  0.168916  0.177164
          [100000.0]  0.108017  0.115627  0.123576  0.132051  0.140915
          [12500.0]   0.117221  0.124666  0.132438  0.140762  0.149481
          [1562.0]    0.127901  0.135153  0.142721  0.150870  0.159420
          [195.0]     0.143631  0.150600  0.157866  0.165757  0.174058
...                        ...       ...       ...       ...       ...
['RSVB1'] [391.0]     0.159109  0.165067  0.170919  0.177092  0.183435
          [50.0]      0.157547  0.164095  0.170834  0.178158  0.185841
          [50000.0]   0.162649  0.167270  0.171110  0.174676  0.177982
          [6250.0]    0.161704  0.166682  0.171059  0.175321  0.179437
          [781.0]     0.160274  0.165792  0.170982  0.176297  0.181640

                         455.0     456.0     457.0     458.0     459.0  ...  \
Label     Conc                                                          ...
['Ad5']   [100.0]     0.185491  0.195904  0.201364  0.205159  0.207942  ...
          [100000.0]  0.149695  0.160068  0.166644  0.171949  0.176271  ...
          [12500.0]   0.158154  0.168536  0.174848  0.179797  0.183755  ...
          [1562.0]    0.167968  0.178362  0.184368  0.188902  0.192439  ...
          [195.0]     0.182424  0.192834  0.198389  0.202314  0.205228  ...
...                        ...       ...       ...       ...       ...  ...
['RSVB1'] [391.0]     0.189692  0.197186  0.201110  0.203707  0.205627  ...
          [50.0]      0.193597  0.203340  0.208221  0.211437  0.213713  ...
          [50000.0]   0.180843  0.183237  0.184993  0.186188  0.187300  ...
          [6250.0]    0.183205  0.186960  0.189294  0.190864  0.192192  ...
          [781.0]     0.186779  0.192593  0.195804  0.197940  0.199593  ...

                        1691.0    1692.0    1693.0    1694.0    1695.0  \
Label     Conc
['Ad5']   [100.0]     0.797566  0.781133  0.765924  0.751674  0.739240
          [100000.0]  1.058237  1.045763  1.033407  1.020407  1.007390
          [12500.0]   0.996639  0.983229  0.970199  0.956904  0.944025
          [1562.0]    0.925168  0.910672  0.896860  0.883222  0.870503
          [195.0]     0.819898  0.803804  0.788840  0.774696  0.762213
...                        ...       ...       ...       ...       ...
['RSVB1'] [391.0]     0.794861  0.779894  0.766236  0.753827  0.743455
          [50.0]      0.745012  0.728130  0.712714  0.698642  0.686804
          [50000.0]   0.907845  0.897215  0.887544  0.878905  0.871857
          [6250.0]    0.877689  0.865901  0.855166  0.845521  0.837586
          [781.0]     0.832057  0.818517  0.806172  0.795005  0.785727

                        1696.0    1697.0    1698.0    1699.0    1700.0
Label     Conc
['Ad5']   [100.0]     0.725515  0.710731  0.693833  0.677220  0.660722
          [100000.0]  0.992627  0.976119  0.957441  0.937000  0.914610
          [12500.0]   0.929507  0.913406  0.895149  0.875613  0.854615
          [1562.0]    0.856270  0.840641  0.822872  0.804385  0.785003
          [195.0]     0.748399  0.733467  0.716416  0.699475  0.682473
...                        ...       ...       ...       ...       ...
['RSVB1'] [391.0]     0.731863  0.719226  0.704624  0.690286  0.676152
          [50.0]      0.673781  0.659838  0.643829  0.628506  0.613731
          [50000.0]   0.863505  0.853827  0.842418  0.830310  0.817629
          [6250.0]    0.828369  0.817901  0.805640  0.792936  0.779868
          [781.0]     0.775201  0.763538  0.749988  0.736383  0.722728

[2579 rows x 1251 columns]

In [40]:
# Step 9: Get highest concentration rows from predicted data
highest_single_virus_conc_predicted_df = get_single_virus_highest_concentration_rows(avg_predicted_df)
highest_single_virus_conc_predicted_df

Extracting single virus data...
Found 149 single virus samples
Example concentration values:
['[100.0]', '[100000.0]', '[12500.0]', '[1562.0]', '[195.0]']
After parsing concentrations:
     Label        Conc  Conc_parsed
0  ['Ad5']     [100.0]        100.0
1  ['Ad5']  [100000.0]     100000.0
2  ['Ad5']   [12500.0]      12500.0
3  ['Ad5']    [1562.0]       1562.0
4  ['Ad5']     [195.0]        195.0
Found 13 unique single virus types
Highest concentration for ['Ad5']: [100000.0]
Highest concentration for ['CoV2']: [100000.0]
Highest concentration for ['CoV229E']: [100000.0]
Highest concentration for ['CoV2B1']: [100000.0]
Highest concentration for ['CoVNL63']: [100000.0]
Highest concentration for ['CoVOC43']: [100000.0]
Highest concentration for ['FluB']: [100000.0]
Highest concentration for ['H1N1']: [100000.0]
Highest concentration for ['H3N2']: [100000.0]
Highest concentration for ['HMPVA']: [100000.0]
Highest concentration for ['HMPVB']: [100000.0]
Highest concentration for ['RSVA2']: [100000.0]
Highest concentration for ['RSVB1']: [100000.0]
Final result has 13 rows

,Label,Conc,450.0,451.0,452.0,453.0,454.0,455.0,456.0,457.0,...,1691.0,1692.0,1693.0,1694.0,1695.0,1696.0,1697.0,1698.0,1699.0,1700.0
1,['Ad5'],[100000.0],0.108017,0.115627,0.123576,0.132051,0.140915,0.149695,0.160068,0.166644,...,1.058237,1.045763,1.033407,1.020407,1.007390,0.992627,0.976119,0.957441,0.937000,0.914610
12,['CoV2'],[100000.0],0.143678,0.158237,0.170542,0.182068,0.192441,0.201322,0.209508,0.215186,...,0.970017,0.953678,0.940966,0.930339,0.924712,0.915695,0.904000,0.887271,0.871712,0.857068
23,['CoV229E'],[100000.0],0.026228,0.023702,0.023737,0.024930,0.027228,0.030421,0.036719,0.038281,...,1.206211,1.187544,1.167246,1.145368,1.122035,1.097088,1.070860,1.042912,1.014982,0.987281
35,['CoV2B1'],[100000.0],0.309544,0.322877,0.337579,0.353386,0.369930,0.386789,0.407053,0.419105,...,1.195842,1.181596,1.163491,1.141491,1.114737,1.087912,1.061368,1.034211,1.010965,0.990649
2036,['CoVNL63'],[100000.0],0.059492,0.065085,0.071356,0.077983,0.084492,0.090576,0.098661,0.100508,...,1.009051,1.005831,0.999797,0.991441,0.979644,0.967000,0.953153,0.938627,0.922085,0.903356
2048,['CoVOC43'],[100000.0],0.131847,0.137356,0.146068,0.156712,0.168932,0.182966,0.200000,0.214000,...,1.144441,1.152814,1.158136,1.161000,1.160203,1.157237,1.151763,1.143576,1.132695,1.118966
2060,['FluB'],[100000.0],0.109414,0.115172,0.122069,0.129431,0.137362,0.145586,0.154707,0.162293,...,1.108776,1.088431,1.070414,1.053431,1.040483,1.022914,1.001603,0.973517,0.946621,0.920534
2291,['H1N1'],[100000.0],0.055175,0.060404,0.066579,0.073368,0.080491,0.087807,0.096965,0.102035,...,1.770947,1.741158,1.709351,1.675930,1.640737,1.603491,1.564316,1.522561,1.480333,1.437632
2522,['H3N2'],[100000.0],0.071136,0.082153,0.091068,0.099373,0.106763,0.112949,0.118864,0.121186,...,1.734593,1.702339,1.668220,1.632780,1.595763,1.557542,1.518068,1.477373,1.435153,1.391475
2533,['HMPVA'],[100000.0],0.040729,0.044136,0.048949,0.054610,0.060898,0.067644,0.076390,0.081068,...,0.961932,0.952593,0.941746,0.929186,0.915051,0.899339,0.882271,0.863085,0.844153,0.825271
2545,['HMPVB'],[100000.0],0.279271,0.295559,0.310780,0.325644,0.339881,0.353508,0.366085,0.378864,...,1.076373,1.072373,1.068119,1.063458,1.058949,1.051441,1.041220,1.026610,1.011712,0.996288
2557,['RSVA2'],[100000.0],0.319789,0.334526,0.346123,0.356263,0.364596,0.370772,0.374404,0.377140,...,0.753018,0.747860,0.740825,0.732754,0.721368,0.713825,0.709316,0.710228,0.709439,0.707053
2568,['RSVB1'],[100000.0],0.163441,0.167763,0.171153,0.174136,0.176763,0.178864,0.180119,0.181390,...,0.933102,0.923441,0.914661,0.906864,0.900559,0.892932,0.883915,0.873220,0.861610,0.849254

In [41]:
# Step 10: Save highest concentration predicted data
pd.DataFrame(highest_single_virus_conc_predicted_df).to_csv(
    RESULT_FOLDER + f"/{DATE} - reconstructed_spectra_highest_concentration_(only_GLF)_constraint_1e-10.csv", 
    index=False
)

# Pred vs Real spectra

In [42]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import ast
import seaborn as sns

In [43]:
# Set up folders
DIFF_FOLDER = f"{WORKING_PATH}/{DATE} - difference_analysis"
R2_MAE_FOLDER = f"{WORKING_PATH}/{DATE} - r2_mae_analysis"

# Make sure folders exist
os.makedirs(DIFF_FOLDER, exist_ok=True)
os.makedirs(R2_MAE_FOLDER, exist_ok=True)

In [44]:
# 1. Basic font configuration
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']

# 2. Function to explicitly set font sizes and family on all text elements
def set_explicit_text_properties(fig, fontsize=None):
    """
    Sets font properties on all text elements in the figure.
    """
    for ax in fig.axes:
        # Set title font
        if ax.get_title():
            ax.set_title(ax.get_title(), fontname='Times New Roman', fontsize=28 if fontsize is None else fontsize)
        
        # Set axis label fonts
        ax.set_xlabel(ax.get_xlabel(), fontname='Times New Roman', fontsize=32 if fontsize is None else fontsize)
        ax.set_ylabel(ax.get_ylabel(), fontname='Times New Roman', fontsize=32 if fontsize is None else fontsize)
        
        # Set tick label fonts
        for tick in ax.get_xticklabels():
            tick.set_fontname('Times New Roman')
            tick.set_fontsize(28 if fontsize is None else fontsize)
        
        for tick in ax.get_yticklabels():
            tick.set_fontname('Times New Roman')
            tick.set_fontsize(28 if fontsize is None else fontsize)
        
        # Set legend font
        if ax.get_legend():
            for text in ax.get_legend().get_texts():
                text.set_fontname('Times New Roman')
                text.set_fontsize(20 if fontsize is None else fontsize)
    
    return fig

In [45]:
# Function to format concentration as integer if possible
def format_concentration(conc):
    try:
        # Check if it can be converted to an integer without loss
        if float(conc) == int(float(conc)):
            return str(int(float(conc)))
        return str(conc)
    except:
        return str(conc)

# Function to fix original data format for mixed viruses
def fix_original_data(original_df):
    """
    Fix mixed virus entries where part of the concentration is in the label
    """
    print("\nFixing the mixed virus format in the original data...")
    
    # Function to fix a mixed virus label and concentration
    def fix_mixed_virus_entry(label, conc):
        """
        Fix mixed virus entries where part of the concentration is in the label
        
        Args:
            label: The possibly corrupted label
            conc: The current concentration value
            
        Returns:
            tuple: (fixed_label, fixed_conc)
        """
        # Check if this is a corrupted mixed virus entry
        if isinstance(label, str) and '_[' in label:
            # Split at the '_[' which separates the virus names from the concentration
            parts = label.split('_[')
            if len(parts) >= 2:
                # First part is the fixed label
                fixed_label = parts[0]
                
                # Second part combined with conc is the fixed concentration
                fixed_conc = f"[{parts[1]}{conc}".rstrip("]") + "]"
                
                # If multiple '_[' sequences, handle more complex cases
                if len(parts) > 2:
                    # More complex parsing might be needed
                    pass
                    
                return fixed_label, fixed_conc
        
        # If not a corrupted entry or parsing fails, return original values
        return label, conc
    
    # Create a new dataframe with fixed labels and concentrations
    original_df_fixed = original_df.copy()
    
    # Apply the fix to each row
    fixed_rows = []
    for idx, row in original_df.iterrows():
        # Make a copy of the row
        new_row = row.copy()
        
        # Fix the label and concentration
        fixed_label, fixed_conc = fix_mixed_virus_entry(row['Label'], row['Conc'])
        
        # Update the row with fixed values
        new_row['Label'] = fixed_label
        new_row['Conc'] = fixed_conc
        
        # Add to the list of fixed rows
        fixed_rows.append(new_row)
    
    # Create a new dataframe from the fixed rows
    original_df_fixed = pd.DataFrame(fixed_rows)
    
    # Check that the fixing worked
    print("\nChecking fixed data:")
    mixed_virus_count = 0
    for idx, row in original_df_fixed.iterrows():
        label = row['Label']
        conc = row['Conc']
        
        if isinstance(label, str) and "'__'" in str(label) and '_[' not in str(label):
            mixed_virus_count += 1
            
            if mixed_virus_count <= 5:  # Show first 5 examples
                print(f"Fixed mixed virus: Label={label}, Conc={conc}")
    
    print(f"\nFound {mixed_virus_count} properly formatted mixed virus entries in the fixed data")
    
    return original_df_fixed

# Function to find matching concentration in another DataFrame
def find_matching_conc(label, conc_str, df):
    """
    Find a matching concentration for the given label in the DataFrame,
    using flexible matching to handle different string representations.
    """
    # Get all concentrations for this label in the DataFrame
    if not isinstance(df, pd.DataFrame) or df.empty:
        return None
        
    label_rows = df[df['Label'] == label]
    if label_rows.empty:
        return None
        
    # Try exact match
    if conc_str in label_rows['Conc'].values:
        return conc_str
        
    # Try comparing the actual values
    try:
        # Parse input concentration
        if isinstance(conc_str, str) and conc_str.startswith('[') and conc_str.endswith(']'):
            input_values = ast.literal_eval(conc_str)
            
            # Compare with each concentration in the DataFrame
            for df_conc in label_rows['Conc'].values:
                if isinstance(df_conc, str) and df_conc.startswith('[') and df_conc.endswith(']'):
                    try:
                        df_values = ast.literal_eval(df_conc)
                        # Check if values match, ignoring the string format
                        if input_values == df_values:
                            return df_conc
                    except:
                        continue
    except:
        pass
        
    # No match found
    return None

# Function to calculate wavelength regions with large differences
def find_difference_regions(real_spectrum, predicted_spectrum, wavenumbers, threshold_percentage=10):
    # Calculate absolute differences
    differences = np.abs(predicted_spectrum - real_spectrum)
    
    # Find the max difference value
    max_diff = np.max(differences)
    
    # Set a threshold as a percentage of the maximum difference
    threshold = max_diff * (threshold_percentage/100)
    
    # Find regions where difference exceeds threshold
    significant_regions = []
    in_region = False
    start_idx = None
    
    for i, diff in enumerate(differences):
        if diff > threshold and not in_region:
            in_region = True
            start_idx = i
        elif diff <= threshold and in_region:
            in_region = False
            significant_regions.append((wavenumbers[start_idx], wavenumbers[i-1]))
    
    # Handle case where the last region extends to the end
    if in_region:
        significant_regions.append((wavenumbers[start_idx], wavenumbers[-1]))
    
    return significant_regions, differences

# Create lookup dictionary for the real data for efficient matching
def create_lookup_dictionary(df):
    """
    Create a lookup dictionary for a DataFrame for efficient flexible matching.
    """
    lookup_dict = {}
    
    # For each label and concentration, store the actual data row index for fast lookup
    for idx, row in df.reset_index().iterrows():
        if 'Label' not in row or 'Conc' not in row:
            continue
            
        label = row['Label']
        conc = row['Conc']
        
        # Skip if label or conc is missing
        if pd.isna(label) or pd.isna(conc):
            continue
        
        # Store this row's index
        if label not in lookup_dict:
            lookup_dict[label] = {}
        
        # Store the original concentration
        lookup_dict[label][conc] = idx
        
        # Also store normalized versions of the concentration
        if isinstance(conc, str):
            # Store without brackets
            clean_conc = conc.strip('[]')
            lookup_dict[label][clean_conc] = idx
            
            # Store with double brackets (common parsing artifact)
            lookup_dict[label][f"[{conc}]"] = idx
            
            # For concentrations with underscores, store each possible format
            if '_' in conc:
                # Handle [100000.0_100000.0] format
                if conc.startswith('[') and conc.endswith(']'):
                    values = conc.strip('[]').split('_')
                    
                    # Store as list format
                    list_format = str(values)
                    lookup_dict[label][list_format] = idx
                    
                    # Store as tuple format
                    tuple_format = str(tuple(values))
                    lookup_dict[label][tuple_format] = idx
    
    return lookup_dict

# Fix and prepare data function - modified to handle MultiIndex consistently
def fix_and_prepare_data():
    """
    Fix any anomalies in the data and prepare lookup dictionaries for efficient matching.
    Ensures the returned DataFrame has the expected format for later use.
    """
    print("\nFixing data anomalies and preparing lookup dictionaries...")
    
    # First check if we need to fix the original data
    needs_fixing = False
    
    # Find all mixed virus entries in the original data
    mixed_virus_count = 0
    for idx, row in df.iterrows():
        if isinstance(row['Label'], str) and '_[' in row['Label']:
            mixed_virus_count += 1
            needs_fixing = True
            if mixed_virus_count <= 3:  # Show just a few examples
                print(f"Found corrupted mixed virus entry: {row['Label']}, {row['Conc']}")
    
    # If we found corrupted entries, fix the original data
    if needs_fixing:
        print(f"Found {mixed_virus_count} corrupted mixed virus entries, fixing...")
        fixed_original_df = fix_original_data(df)
        
        # Create new grouped data
        new_grouped_df = fixed_original_df.groupby(['Label', 'Conc']).mean()
        
        # Reset index to make Label and Conc columns for easier filtering
        new_grouped_df_reset = new_grouped_df.reset_index()
        
        # Create lookup dictionary from the original MultiIndex form
        real_lookup_dict = create_lookup_dictionary(new_grouped_df)
        
        return new_grouped_df_reset, real_lookup_dict
    else:
        print("No data anomalies found, using existing data.")
        
        # Check if grouped_df is a MultiIndex DataFrame
        if isinstance(grouped_df.index, pd.MultiIndex) and 'Label' in grouped_df.index.names:
            # Reset index to make Label and Conc columns for easier filtering
            grouped_df_reset = grouped_df.reset_index()
            real_lookup_dict = create_lookup_dictionary(grouped_df)
            return grouped_df_reset, real_lookup_dict
        else:
            # Already in the right format
            real_lookup_dict = create_lookup_dictionary(grouped_df)
            return grouped_df, real_lookup_dict

In [54]:
# Function to create standard comparison plots (real vs predicted)
def create_comparison_plot(label, conc, predicted_df, grouped_df_fixed, real_lookup_dict=None):
    """
    Create standard comparison plots showing real vs predicted spectra.
    """
    print(f"\nCreating comparison plot for {label} at {conc}")
    
    # Get predicted data
    pred_data = predicted_df[(predicted_df['Label'] == label) & (predicted_df['Conc'] == conc)]
    if pred_data.empty:
        print(f"  No predicted data found for {label} at {conc}")
        return
    
    # Get real data if available
    real_data = None
    comparison_possible = False
    
    if isinstance(grouped_df_fixed, pd.DataFrame):
        # First try direct match
        real_data = grouped_df_fixed[(grouped_df_fixed['Label'] == label) & (grouped_df_fixed['Conc'] == conc)]
        
        # If no direct match, try using the lookup dictionary
        if real_data.empty and real_lookup_dict is not None and label in real_lookup_dict:
            for alt_conc in real_lookup_dict.get(label, {}):
                idx = real_lookup_dict[label][alt_conc]
                real_data = grouped_df_fixed.iloc[[idx]]
                if not real_data.empty:
                    print(f"  Found real data using lookup dictionary with concentration: {alt_conc}")
                    break
        
        if not real_data.empty:
            comparison_possible = True
    
    # Extract wavenumbers
    wavenumbers = pred_data.columns[2:].astype(float)
    
    # Create figure for the plot
    fig = plt.figure(figsize=(8.7, 8))
    plt.xlabel('Wavenumbers')
    plt.ylabel('Intensity')
    
    # Plot real spectrum first (blue, solid)
    if comparison_possible and real_data is not None:
        real_spectrum = real_data.iloc[0, 2:].values
        plt.plot(wavenumbers, real_spectrum, color='blue', linewidth=2, linestyle='-', label='Real Spectrum')
    
    # Plot predicted spectrum (orange, dashed)
    predicted_spectrum = pred_data.iloc[0, 2:].values
    plt.plot(wavenumbers, predicted_spectrum, color='orange', linewidth=2, linestyle='--', label='Reconstructed Spectrum')
    
    # Calculate MAE if comparison is possible
    if comparison_possible and real_data is not None:
        mae = np.mean(np.abs(real_spectrum - predicted_spectrum))
        plt.title(f"MAE: {mae:.4f}")
        
        # Add to MAE records
        mae_records.append({
            'Label': label,
            'Concentration': conc,
            'MAE': mae
        })
    
    # Adjusting x-axis ticks
    tick_interval = 200.0
    plt.xticks(np.arange(start=450, stop=1701, step=tick_interval))
    
    # Add legend
    plt.legend(loc='best')
    set_explicit_text_properties(fig)
    plt.tight_layout()
    
    # Create a safe filename
    safe_label = str(label).replace('/', '_').replace('\\', '_').replace(':', '_')
    safe_conc = str(conc).replace('/', '_').replace('\\', '_').replace(':', '_')
    
    # Save the plot
    filename = f"{RESULT_FOLDER}/{DATE} - {safe_label}_Concentration_{safe_conc}.png"
    plt.savefig(filename, dpi=300)
    plt.show()
    plt.close('all')
    plt.clf()
    plt.cla()
    
    # Create difference plot if comparison is possible
    if comparison_possible and real_data is not None:
        fig_diff = plt.figure(figsize=(8.7, 8))
        plt.xlabel('Wavenumbers')
        plt.ylabel('Intensity Difference')
        
        difference = predicted_spectrum - real_spectrum
        plt.plot(wavenumbers, difference, color='purple', linewidth=2, label='Reconstructed - Real')
        
        # Add a zero line for reference
        plt.axhline(y=0, color='r', linestyle='-', alpha=0.3)
        
        # Adjusting x-axis ticks
        plt.xticks(np.arange(start=450, stop=1701, step=tick_interval))
        plt.legend()
        set_explicit_text_properties(fig_diff)
        plt.tight_layout()
        
        # Filename for difference plot
        diff_filename = f"{RESULT_FOLDER}/{DATE} - {safe_label}_Concentration_{safe_conc}_difference.png"
        plt.savefig(diff_filename, dpi=300)
        plt.show()
        plt.close('all')
        plt.clf()
        plt.cla()

# Function to create enhanced plots for all samples
def create_enhanced_plot(label, conc, predicted_df, grouped_df, highest_single_virus_conc_df, reference_series, real_lookup_dict=None):
    """
    Create enhanced plots for ALL samples (single and mixed virus) that include:
    1. Predicted spectrum (orange, dashed)
    2. Real spectrum (blue, solid) - if available
    3. All component spectra at their respective highest concentrations
    4. SiO2 reference component
    
    Args:
        label: Virus label (e.g., "['Ad5']" or "['CoVNL63', 'FluB']")
        conc: Concentration string or value
        predicted_df: DataFrame with predicted data
        grouped_df: DataFrame with real data
        highest_single_virus_conc_df: DataFrame with highest concentration single virus data
        reference_series: Series with SiO2 reference data
        real_lookup_dict: Dictionary for flexible matching of real data (optional)
    """
    import ast
    print(f"\nCreating enhanced plot for {label} at {conc}")
    
    # Get predicted data
    pred_data = predicted_df[(predicted_df['Label'] == label) & (predicted_df['Conc'] == conc)]
    if pred_data.empty:
        print(f"  No predicted data found for {label} at {conc}")
        return
    
    # Get real data if available
    real_data = None
    comparison_possible = False
    
    if isinstance(grouped_df, pd.DataFrame):
        # First try direct match
        real_data = grouped_df[(grouped_df['Label'] == label) & (grouped_df['Conc'] == conc)]
        
        # If no direct match, try using the lookup dictionary
        if real_data.empty and real_lookup_dict is not None and label in real_lookup_dict:
            for alt_conc in real_lookup_dict.get(label, {}):
                idx = real_lookup_dict[label][alt_conc]
                real_data = grouped_df.iloc[[idx]]
                if not real_data.empty:
                    print(f"  Found real data using lookup dictionary with concentration: {alt_conc}")
                    break
        
        if not real_data.empty:
            comparison_possible = True
    
    # Extract wavenumbers
    wavenumbers = pred_data.columns[2:].astype(float)
    
    # Parse component viruses from the label
    component_viruses = []
    
    try:
        # Try to use ast.literal_eval first to parse the label
        if isinstance(label, str) and label.startswith('[') and label.endswith(']'):
            try:
                parsed_label = ast.literal_eval(label)
                if isinstance(parsed_label, list):
                    component_viruses = parsed_label
                else:
                    component_viruses = [str(parsed_label)]
            except (SyntaxError, ValueError):
                # If that fails, use string splitting
                if "'__'" in label:
                    # Mixed virus case
                    clean_label = label.strip("[]' ")
                    parts = clean_label.split("'__'")
                    component_viruses = [part.strip("'") for part in parts]
                else:
                    # Single virus case
                    clean_label = label.strip("[]' ")
                    component_viruses = [clean_label]
        else:
            # Non-standard format, just use the label as is
            component_viruses = [label]
    except Exception as e:
        print(f"  Error parsing virus label: {e}")
        component_viruses = [str(label)]  # Fallback
    
    print(f"  Component viruses: {component_viruses}")
    
    # Create figure for the plot
    fig = plt.figure(figsize=(12, 10))  # Larger figure for more elements
    plt.xlabel('Wavenumbers')
    plt.ylabel('Intensity')
    
    # Plot component virus spectra
    component_spectra = []
    legend_labels = []
    
    # Add each virus component spectrum
    for i, virus in enumerate(component_viruses):
        # Format the virus label for lookup
        virus_label = f"['{virus}']"
        
        # Find the virus in the highest concentration data
        if virus_label in highest_single_virus_conc_df['Label'].values:
            # Get data for this virus
            virus_data = highest_single_virus_conc_df[highest_single_virus_conc_df['Label'] == virus_label]
            
            # Get the spectrum
            if not virus_data.empty:
                virus_spectrum = virus_data.iloc[0, 2:].values
                component_spectra.append(virus_spectrum)
                
                # Get the highest concentration for this virus
                virus_conc = virus_data.iloc[0]['Conc']
                
                # Plot with a distinctive color and line style
                colors = ['green', 'purple', 'red', 'brown', 'cyan']  # Colors for components
                line_style = '-.'  # Different line style for components
                color = colors[i % len(colors)]  # Cycle through colors
                
                plt.plot(wavenumbers, virus_spectrum, color=color, linestyle=line_style, 
                         linewidth=1.5, alpha=0.7)
                
                # Add to legend labels - include the actual highest concentration
                legend_label = f"{virus} Component (Highest conc: {virus_conc})"
                legend_labels.append(legend_label)
                print(f"  Added component: {legend_label}")
    
    # Add SiO2 reference component
    plt.plot(wavenumbers, reference_series.values, color='dimgray', linestyle='-.', 
             linewidth=1.5, alpha=0.8)
    legend_labels.append("SiO2 Reference")
    print("  Added component: SiO2 Reference")
    
    # Plot real spectrum first (blue, solid)
    if comparison_possible and real_data is not None:
        real_spectrum = real_data.iloc[0, 2:].values
        plt.plot(wavenumbers, real_spectrum, color='blue', linewidth=2, linestyle='-', label='Real Spectrum')
    
    # Plot predicted spectrum (orange, dashed)
    predicted_spectrum = pred_data.iloc[0, 2:].values
    plt.plot(wavenumbers, predicted_spectrum, color='orange', linewidth=2, linestyle='--', label='Reconstructed Spectrum')
    
    # Calculate MAE if comparison is possible
    if comparison_possible and real_data is not None:
        mae = np.mean(np.abs(real_spectrum - predicted_spectrum))
        # plt.title(f"MAE: {mae:.4f}")
        
        # Add to MAE records if not already added by the comparison plot
        mae_record_exists = False
        for record in mae_records:
            if record['Label'] == label and record['Concentration'] == conc:
                mae_record_exists = True
                break
                
        if not mae_record_exists:
            mae_records.append({
                'Label': label,
                'Concentration': conc,
                'MAE': mae
            })
    
    # Add component legend labels
    for i, label_text in enumerate(legend_labels):
        if "SiO2" in label_text:
            color = 'gray'
            line_style = ':'
        else:
            colors = ['green', 'purple', 'red', 'brown', 'cyan']
            color = colors[i % len(colors) if i < len(colors) else 0]
            line_style = '-.'
        plt.plot([], [], color=color, linestyle=line_style, linewidth=1.5, alpha=0.7, label=label_text)
    
    # Adjusting x-axis ticks
    tick_interval = 200.0
    plt.xticks(np.arange(start=450, stop=1701, step=tick_interval))
    
    # Add legend
    plt.legend(loc='best')
    set_explicit_text_properties(fig)
    plt.tight_layout()
    
    # Create a safe filename
    safe_label = str(label).replace('/', '_').replace('\\', '_').replace(':', '_')
    safe_conc = str(conc).replace('/', '_').replace('\\', '_').replace(':', '_')
    
    # Save the plot
    filename = f"{RESULT_FOLDER}/{DATE} - {safe_label}_Concentration_{safe_conc}_enhanced.png"
    plt.savefig(filename, dpi=300)
    plt.show()
    plt.close('all')
    plt.clf()
    plt.cla()
    
    # Create difference plot if comparison is possible
    if comparison_possible and real_data is not None:
        fig_diff = plt.figure(figsize=(10, 8))
        plt.xlabel('Wavenumbers')
        plt.ylabel('Intensity Difference')
        
        difference = predicted_spectrum - real_spectrum
        plt.plot(wavenumbers, difference, color='purple', linewidth=2, label='Reconstructed - Real')
        
        # Add a zero line for reference
        plt.axhline(y=0, color='r', linestyle='-', alpha=0.3)
        
        # Adjusting x-axis ticks
        plt.xticks(np.arange(start=450, stop=1701, step=tick_interval))
        plt.legend()
        set_explicit_text_properties(fig_diff)
        plt.tight_layout()
        
        # Filename for difference plot
        diff_filename = f"{RESULT_FOLDER}/{DATE} - {safe_label}_Concentration_{safe_conc}_enhanced_difference.png"
        plt.savefig(diff_filename, dpi=300)
        plt.show()
        plt.close('all')
        plt.clf()
        plt.cla()

# Main processing loop for all virus samples
def process_all_virus_samples(predicted_df, grouped_df_fixed, highest_single_virus_conc_df, reference_series, real_lookup_dict):
    """
    Process all virus samples, creating both standard comparison plots and enhanced plots.
    
    Returns:
        List of MAE records for each processed sample
    """
    global mae_records  # Using the global mae_records list
    mae_records = []
    
    print("\nProcessing all virus samples...")
    # Get all unique virus labels
    all_virus_labels = predicted_df['Label'].unique()
    
    # Categorize labels
    single_virus_labels = [label for label in all_virus_labels if isinstance(label, str) and not "'__'" in label]
    mixed_virus_labels = [label for label in all_virus_labels if isinstance(label, str) and "'__'" in label]
    
    print(f"Found {len(single_virus_labels)} single virus labels and {len(mixed_virus_labels)} mixed virus labels")
    
    # Process single virus samples first
    print("\nProcessing single virus samples...")
    for label in single_virus_labels:
        print(f"Working on {label}")
        # Get concentrations for this label
        conc_values = predicted_df[predicted_df['Label'] == label]['Conc'].unique()
        
        for conc in conc_values:
            conc_str = str(conc)
            print(f"Working on {label}, conc = {conc_str}")
            
            # # Create standard comparison plot
            # create_comparison_plot(label, conc, predicted_df, grouped_df_fixed, real_lookup_dict)
            
            # Create enhanced plot with components
            create_enhanced_plot(label, conc, predicted_df, grouped_df_fixed, 
                                highest_single_virus_conc_df, reference_series, real_lookup_dict)
    
    # Process mixed virus samples
    print("\nProcessing mixed virus samples...")
    for label in mixed_virus_labels:
        print(f"Working on {label}")
        # Get concentrations for this label
        conc_values = predicted_df[predicted_df['Label'] == label]['Conc'].unique()
        
        for conc in conc_values:
            conc_str = str(conc)
            print(f"Working on {label}, conc = {conc_str}")
            
            # Create standard comparison plot
            create_comparison_plot(label, conc, predicted_df, grouped_df_fixed, real_lookup_dict)
            
            # Create enhanced plot with components
            create_enhanced_plot(label, conc, predicted_df, grouped_df_fixed, 
                                highest_single_virus_conc_df, reference_series, real_lookup_dict)
    
    return mae_records

# Function to set explicit text properties for heatmaps
def set_explicit_text_properties_for_heatmap(fig):
    # Set font sizes for all text elements
    for ax in fig.axes:
        ax.title.set_fontsize(24)  # Title font size
        ax.xaxis.label.set_fontsize(22)  # X-axis label font size
        ax.yaxis.label.set_fontsize(22)  # Y-axis label font size
        ax.tick_params(axis='both', which='major', labelsize=20)  # Tick label font size
        
        # Set legend font size if legend exists
        if ax.get_legend() is not None:
            for text in ax.get_legend().get_texts():
                text.set_fontsize(20)

# Function to process difference regions and create analysis visualizations
def analyze_difference_regions(mae_records, predicted_df, grouped_df_fixed):
    """
    Analyze significant difference regions between real and predicted spectra.
    
    Returns:
        List of dictionaries with difference region information
    """
    difference_regions_data = []
    print("\nAnalyzing significant difference regions...")
    
    if not mae_records:
        print("No MAE records to analyze.")
        return difference_regions_data
    
    for record in mae_records:
        label = record['Label']
        conc = record['Concentration']
        
        # Get the data
        real_data = grouped_df_fixed[(grouped_df_fixed['Label'] == label) & (grouped_df_fixed['Conc'] == conc)]
        predicted_data = predicted_df[(predicted_df['Label'] == label) & (predicted_df['Conc'] == conc)]
        
        if real_data.empty or predicted_data.empty:
            continue
        
        # Get wavenumbers and spectra
        wavenumbers = real_data.columns[2:].astype(float)
        real_spectrum = real_data.iloc[0, 2:].values
        predicted_spectrum = predicted_data.iloc[0, 2:].values
        
        # Find regions with significant differences
        regions, differences = find_difference_regions(real_spectrum, predicted_spectrum, wavenumbers)
        
        # Parse virus names from label using ast.literal_eval for reliable parsing
        virus_names = []
        try:
            if isinstance(label, str) and label.startswith('[') and label.endswith(']'):
                try:
                    parsed_label = ast.literal_eval(label)
                    if isinstance(parsed_label, list):
                        virus_names = parsed_label
                    else:
                        virus_names = [str(parsed_label)]
                except (SyntaxError, ValueError):
                    # Fall back to string splitting
                    if "'__'" in label:
                        clean_label = label.strip("[]' ")
                        parts = clean_label.split("'__'")
                        virus_names = [part.strip("'") for part in parts]
                    else:
                        clean_label = label.strip("[]'")
                        virus_names = [clean_label]
            else:
                virus_names = [label]
        except:
            virus_names = [label]  # Default fallback
        
        # Store the difference regions for each virus name
        for virus_name in virus_names:
            for region_start, region_end in regions:
                difference_regions_data.append({
                    'Label': label,
                    'Focus_Virus': virus_name,
                    'Concentration': conc,
                    'Region_Start': region_start,
                    'Region_End': region_end,
                    'MAE_in_Region': np.mean(np.abs(predicted_spectrum[(wavenumbers >= region_start) & 
                                                                    (wavenumbers <= region_end)] - 
                                                real_spectrum[(wavenumbers >= region_start) & 
                                                            (wavenumbers <= region_end)]))
                })
    
    return difference_regions_data

# Function to create difference heatmaps
def create_difference_heatmaps(difference_regions_data, folder):
    """
    Create heatmaps visualizing the differences between real and predicted spectra.
    
    Args:
        difference_regions_data: List of dictionaries with difference region information
        folder: Folder to save the heatmaps
    """
    if not difference_regions_data:
        print("No difference regions data to visualize.")
        return
    
    print("\nCreating difference heatmaps...")
    
    # Group by virus
    virus_groups = {}
    for record in difference_regions_data:
        virus = record['Focus_Virus']
        if virus not in virus_groups:
            virus_groups[virus] = []
        virus_groups[virus].append(record)
    
    # Process each virus group
    for virus, records in virus_groups.items():
        print(f"Creating heatmap for {virus}...")
        
        # Group by label and concentration
        label_conc_groups = {}
        for record in records:
            key = (record['Label'], record['Concentration'])
            if key not in label_conc_groups:
                label_conc_groups[key] = []
            label_conc_groups[key].append(record)
        
        # Sort keys for consistent ordering
        sorted_keys = sorted(label_conc_groups.keys())
        
        # Create a matrix for the heatmap
        # Each row is a label+concentration, each column is a wavenumber
        wavenumbers = np.arange(450, 1701)
        heatmap_matrix = np.zeros((len(sorted_keys), len(wavenumbers)))
        
        # Fill the matrix with MAE values
        for i, key in enumerate(sorted_keys):
            for record in label_conc_groups[key]:
                start_idx = int(record['Region_Start'] - 450)
                end_idx = int(record['Region_End'] - 450)
                if start_idx < 0:
                    start_idx = 0
                if end_idx >= len(wavenumbers):
                    end_idx = len(wavenumbers) - 1
                
                # Set the MAE value for this region
                heatmap_matrix[i, start_idx:end_idx+1] = record['MAE_in_Region']
        
        # Create the heatmap
        fig, ax = plt.subplots(figsize=(12, 8))
        im = ax.imshow(heatmap_matrix, aspect='auto', cmap='viridis', interpolation='nearest')
        
        # Set axis labels
        ax.set_xlabel('Wavenumber')
        ax.set_ylabel('Sample')
        
        # Set y-tick labels
        ax.set_yticks(np.arange(len(sorted_keys)))
        # Create more descriptive y labels
        y_labels = []
        for key in sorted_keys:
            label, conc = key
            # Format label for display
            if isinstance(label, str) and "'__'" in label:
                # For mixed virus, show a simplified format
                clean_label = "Mixed"
            else:
                # For single virus, just show the virus name
                clean_label = "Single"
            y_labels.append(f"{clean_label} {conc}")
        ax.set_yticklabels(y_labels)
        
        # Create custom x-ticks for wavenumbers
        num_ticks = 7  # Number of ticks to show
        tick_indices = np.linspace(0, len(wavenumbers) - 1, num_ticks, dtype=int)
        ax.set_xticks(tick_indices)
        ax.set_xticklabels([str(wavenumbers[i]) for i in tick_indices])
        
        # Add colorbar
        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label('Mean Absolute Error')
        
        # Set title
        ax.set_title(f'Difference Analysis Heatmap for {virus}')
        
        # Apply text properties
        set_explicit_text_properties_for_heatmap(fig)
        
        # Save the figure
        plt.tight_layout()
        safe_virus = str(virus).replace('/', '_').replace('\\', '_').replace(':', '_')
        plt.savefig(os.path.join(folder, f"{safe_virus}_difference_heatmap.png"), dpi=300)
        plt.show()
        plt.close('all')
        plt.clf()
        plt.cla()

# Function to create MAE summary visualizations
def create_mae_summary_plots(mae_records, folder):
    """
    Create summary plots for MAE values.
    
    Args:
        mae_records: List of dictionaries with MAE information
        folder: Folder to save the plots
    """
    if not mae_records:
        print("No MAE records to visualize.")
        return
    
    print("\nCreating summary plots for MAE values...")
    
    # Convert to DataFrame
    mae_df = pd.DataFrame(mae_records)
    
    # Group by label
    label_groups = mae_df.groupby('Label')
    
    # Create a summary figure for single vs mixed virus MAE
    fig, ax = plt.subplots(figsize=(10, 8))
    
    # Categorize labels as single or mixed
    mae_df['Type'] = mae_df['Label'].apply(lambda x: 'Mixed' if "'__'" in str(x) else 'Single')
    
    # Calculate mean MAE for each type
    type_mae = mae_df.groupby('Type')['MAE'].mean()
    
    # Create bar chart
    type_mae.plot(kind='bar', ax=ax, color=['blue', 'orange'])
    ax.set_ylabel('Mean Absolute Error')
    ax.set_title('Average MAE by Virus Type')
    
    # Apply text properties
    set_explicit_text_properties(fig)
    
    # Save the figure
    plt.tight_layout()
    plt.savefig(os.path.join(folder, f"{DATE} - virus_type_mae_summary.png"), dpi=300)
    plt.show()
    plt.close('all')
    plt.clf()
    plt.cla()
    
    # Create individual plots for each virus
    for label, group in label_groups:
        if len(group) > 1:  # Only create plot if multiple concentrations
            print(f"Creating MAE summary plot for {label}...")
            
            # Sort by concentration if possible
            try:
                # Convert concentration to numeric if possible
                group = group.copy()
                group['NumericConc'] = group['Concentration'].apply(
                    lambda x: float(x.strip('[]')) if isinstance(x, str) else float(x))
                group = group.sort_values('NumericConc')
            except:
                # If conversion fails, keep original order
                pass
            
            # Create the plot
            fig, ax = plt.subplots(figsize=(10, 8))
            ax.plot(range(len(group)), group['MAE'], 'o-', linewidth=2, markersize=8)
            
            # Set tick labels
            ax.set_xticks(range(len(group)))
            ax.set_xticklabels(group['Concentration'], rotation=45)
            
            # Set labels and title
            ax.set_xlabel('Concentration')
            ax.set_ylabel('Mean Absolute Error')
            
            # Format label for title
            display_label = label
            if isinstance(label, str) and label.startswith('[') and label.endswith(']'):
                # Clean up the label for display
                if "'__'" in label:
                    # Mixed virus case, format with +
                    clean_label = label.strip("[]' ")
                    parts = clean_label.split("'__'")
                    display_label = " + ".join([part.strip("'") for part in parts])
                else:
                    # Single virus case
                    display_label = label.strip("[]'")
            
            ax.set_title(f'MAE vs. Concentration for {display_label}')
            
            # Apply text properties
            set_explicit_text_properties(fig)
            
            # Save the figure
            plt.tight_layout()
            safe_label = str(label).replace('/', '_').replace('\\', '_').replace(':', '_')
            plt.savefig(os.path.join(folder, f"{DATE} - {safe_label}_mae_summary.png"), dpi=300)
            plt.show()
            plt.close('all')
            plt.clf()
            plt.cla()

In [55]:
# Fix data anomalies and prepare lookup dictionaries
grouped_df_fixed, real_lookup_dict = fix_and_prepare_data()
print("Fixed DataFrame shape:", grouped_df_fixed.shape)
grouped_df_fixed

Fixing data anomalies and preparing lookup dictionaries...
No data anomalies found, using existing data.
Fixed DataFrame shape: (2580, 1253)

,Label,Conc,450.0,451.0,452.0,453.0,454.0,455.0,456.0,457.0,...,1691.0,1692.0,1693.0,1694.0,1695.0,1696.0,1697.0,1698.0,1699.0,1700.0
0,['Ad5'],[100.0],0.188456,0.193579,0.199298,0.205842,0.214035,0.222088,0.230509,0.238614,...,0.724246,0.706123,0.688772,0.672316,0.656649,0.642035,0.628474,0.616544,0.603561,0.589719
1,['Ad5'],[100000.0],0.108017,0.115627,0.123576,0.132051,0.140915,0.149695,0.160068,0.166644,...,1.058237,1.045763,1.033407,1.020407,1.007390,0.992627,0.976119,0.957441,0.937000,0.914610
2,['Ad5'],[12500.0],0.125390,0.136017,0.145695,0.155153,0.164305,0.172593,0.181102,0.186508,...,1.031186,1.019051,1.007000,0.994695,0.982814,0.969153,0.953915,0.936441,0.918119,0.898695
3,['Ad5'],[1562.0],0.144458,0.155678,0.165746,0.175237,0.184034,0.191864,0.199475,0.204407,...,1.011746,1.001780,0.990966,0.979593,0.967610,0.954356,0.939966,0.923898,0.907797,0.891576
4,['Ad5'],[195.0],0.142603,0.152603,0.161483,0.169983,0.177655,0.184931,0.192069,0.197793,...,0.880224,0.866776,0.852776,0.838741,0.824276,0.809707,0.795000,0.779914,0.764931,0.750431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,['RSVB1'],[50.0],0.136810,0.138224,0.141741,0.146172,0.151672,0.158603,0.166310,0.174000,...,0.744603,0.726397,0.707000,0.688672,0.671207,0.653741,0.637914,0.623000,0.611241,0.598483
2576,['RSVB1'],[50000.0],0.154390,0.162458,0.167458,0.171000,0.172881,0.173220,0.170322,0.170288,...,0.860475,0.851661,0.843661,0.836492,0.831085,0.823475,0.813983,0.801017,0.789203,0.778390
2577,['RSVB1'],[6250.0],0.177224,0.182293,0.185483,0.187879,0.189190,0.189483,0.187948,0.187966,...,0.815948,0.802086,0.791810,0.783845,0.781293,0.775534,0.767638,0.754776,0.744207,0.735483
2578,['RSVB1'],[781.0],0.126759,0.135397,0.141224,0.145879,0.149379,0.151500,0.151138,0.153155,...,0.735293,0.720603,0.709017,0.699397,0.694690,0.686190,0.675052,0.658069,0.643534,0.630948
2579,['Reference'],[0.0],0.159350,0.167391,0.175635,0.184376,0.193345,0.202345,0.213487,0.219716,...,0.884071,0.872670,0.861655,0.850949,0.841188,0.829807,0.817056,0.801919,0.786701,0.771223

In [ ]:
# Process all virus samples (creates both standard comparison and enhanced plots)
mae_records = process_all_virus_samples(predicted_df, grouped_df_fixed, highest_single_virus_conc_df, 
                                      reference_series, real_lookup_dict)
mae_records

In [57]:
# Save MAE records to CSV
if mae_records:
    mae_df = pd.DataFrame(mae_records)
    mae_csv_path = os.path.join(R2_MAE_FOLDER, f"{DATE} - reconstruction_mae_summary.csv")
    mae_df.to_csv(mae_csv_path, index=False)
    print(f"MAE summary saved to {mae_csv_path}")
else:
    print("No MAE records collected, skipping MAE summary CSV.")

MAE summary saved to /home/zhao/Jiaheng Cui/Coefficient_fitting/04042025 - r2_mae_analysis/04042025 - reconstruction_mae_summary.csv